### ISSUE TITLE
Dependencies are incorrectly tracked when using ConfigFile

### ISSUE THREAD

**Issue by manast** [pulumi/pulumi-kubernetes#1315] opened 2020-09-11 13:24 UTC
### Problem description

This one took me some time to isolate, not sure if it is the only case where dependencies are incorrectly tracked, but I noticed that wrong dependencies leads to a lot of errors when deploying the stacks, in some cases broken stacks as a result.

In this isolated case what I found is that resources that "dependsOn" the  ```k8s.yaml.ConfigFile``` resource, will not be deployed *after* the config file, but before instead. I created a repository with minimum required resources to easily reproduce the issue (see link below).

From the index.ts:
```ts
import * as gcp from "@pulumi/gcp";
import * as k8s from "@pulumi/kubernetes";
import { ComponentResource, CustomResourceOptions } from "@pulumi/pulumi";
import { Cluster } from "./cluster";

export class MyComponent extends ComponentResource {
  constructor(name: string, opts: CustomResourceOptions = {}) {
    super("my:component", name, {}, opts);

    const bucket = new gcp.storage.Bucket(`${name}`, undefined, {
      parent: this,
    });

    this.registerOutputs({
      bucket,
    });
  }
}

const cluster = new Cluster("my-cluster");

const certManager = new k8s.yaml.ConfigFile(
  "certManager2",
  {
    file:
      "https://github.com/jetstack/cert-manager/releases/download/v1.0.1/cert-manager.yaml",
  },
  { provider: cluster.provider, dependsOn: [cluster] }
);

export const componentA = new MyComponent("astrid", {
  dependsOn: [certManager],
});
```

I would expect the component "astrid" to be deployed *after* the certManager, however this is not the case:
![image](https://user-images.githubusercontent.com/95200/92930380-48864780-f442-11ea-8fd9-19e7a65db211.png)

I made several other experiments with dependencies and as far as I could find, the issue is with the ConfigFile and not with the Bucket or ComponentResource objects.

### Affected product version(s)

I tested with 2-3 previous versions including newest one v2.10.0

### Reproducing the issue

Just clone this repo, replace the gcp project with a valid one and do a pulumi up:

https://github.com/taskforcesh/pulumi-issues

**Comment by leezen** [comment] 2020-09-14 18:20
Dupe of https://github.com/pulumi/pulumi-kubernetes/issues/861

**Closed by leezen** 2020-09-14 18:20 UTC

**Comment by manast** [comment] 2020-09-14 20:02
At least some documentation on the ConfigFile explaining about this shortcoming would be really great, and in the rest of the resources that are not working properly with the dependency tracking so that we can avoid problems that in many cases results in hours of wasted work...

**Comment by tricky42** [comment] 2020-11-06 10:16
> At least some documentation on the ConfigFile explaining about this shortcoming would be really great, and in the rest of the resources that are not working properly with the dependency tracking so that we can avoid problems that in many cases results in hours of wasted work...

I second that, there should a not in the documentation clearly stating the current limitation of `dependsOn` in the context of `ConfigFile` & `HelmCharts` (and any other Resource affected by the problem). 

There is more information on the problem also in the community slack: https://pulumi-community.slack.com/archives/C84L4E3N1/p1604620349492900?thread_ts=1604604723.483000&cid=C84L4E3N1
