### ISSUE TITLE
Helm releases installation random failures

### ISSUE THREAD

**Issue by raelix** [pulumi/pulumi-kubernetes#2524] opened 2023-08-03 17:09 UTC
### What happened?

Hi everyone, I'm installing with Pulumi ~**150 charts** using helm v3 ```NewRelease```. These charts have dependencies each other but every ```pulumi up``` at least one fails with ```failed to become available within allocated timeout, the server could not find the requested resource```.

The Burst is set to 10 and Qps to 5. I also run Pulumi with verbose output but without getting a good hint if not a recurrent one which says:
```
  kubernetes:helm.sh/v3:Release (central/istio-system/istio-base):
    warning: Helm release "istio-base" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then retry. Reason: 1 error occurred:
    	* the server could not find the requested resource
    error: 1 error occurred:
    	* Helm release "istio-system/istio-base" was created, but failed to initialize completely. Use Helm CLI to investigate.: failed to become available within allocated timeout. Error: Helm Release istio-system/istio-base: 1 error occurred:
    	* the server could not find the requested resource

  kubernetes:helm.sh/v3:Release (central/monitoring/nla-fluent-operator):
    warning: Helm release "nla-fluent-operator" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then retry. Reason: 1 error occurred:
    	* the server could not find the requested resource
    error: 1 error occurred:
    	* Helm release "explorer/nla-fluent-operator" was created, but failed to initialize completely. Use Helm CLI to investigate.: failed to become available within allocated timeout. Error: Helm Release explorer/nla-fluent-operator: 1 error occurred:
    	* the server could not find the requested resource
```
And a recurrent one which doesn't seem to be problematic:
```
I0803 18:31:34.023699 1890438 log.go:75] error copying .pulumi/stacks/production.json.gz to .pulumi/stacks/production.json.gz.bak: blob (key ".pulumi/stacks/production.json.gz -> .pulumi/stacks/production.json.gz.bak") (code=NotFound): stat /home/user/dev/pulumi/vars/.pulumi/stacks/production.json.gz: no such file or directory
I0803 18:31:34.024348 1890438 log.go:75] error deleting source object after rename: .pulumi/stacks/production.json.gz (blob (key ".pulumi/stacks/production.json.gz") (code=NotFound): remove /home/user/dev/pulumi/vars/.pulumi/stacks/production.json.gz: no such file or directory) skipping
```

### Expected Behavior

Pulumi up command should not fail randomly

### Steps to reproduce

Installing multiple helm charts in a loop could trigger this issue

### Output of `pulumi about`

```
CLI          
Version      3.60.0
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME  VERSION
go    unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in go: executable='/usr/local/go/bin/go' version='go version go1.20.6 linux/amd64'

Found no pending operations associated with production

Backend        
Name           user
URL            file://./vars
User           user
Organizations  

No dependencies found

Pulumi locates its logs in /tmp by default
```

### Additional context

I can confirm that the fix mentioned in this issue solves the failures:
https://github.com/pulumi/pulumi-kubernetes/issues/2481

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment] 2023-08-04 15:56
Hi @raelix - thank you for filing this issue. We're glad to hear the workaround is working for you.

We will close it as a duplicate of #2481. I've also triggered the tests on the related kubernetes/kubernetes PR, but of course need the original author to address the thread safety question.

**Closed by guineveresaenger** 2023-08-04 15:56 UTC
Labels: kind/bug, resolution/duplicate

**Comment by gopripe** [comment] 2023-10-12 04:39
Hi, would you share the workaround?
