### ISSUE TITLE
Python exports fail on preview for .metadata.name

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#547] opened 2019-04-26 19:55 UTC
This appears to be a bug with resource autonaming in the Python SDK. In the following program, the export will raise an error during preview.

```py3
import pulumi
from pulumi_kubernetes.core.v1 import Pod

pod = Pod(
    "foo",
    spec={"containers": [{"name": "nginx", "image": "nginx"}]}
)

# Works fine
pulumi.export("podname", pod.metadata['name'])

pod2 = Pod(
    "bar",
    metadata={"labels": {"foo": "bar"}},
    spec={"containers": [{"name": "nginx", "image": "nginx"}]}
)

# Fails with KeyError: 'name'
pulumi.export("podname", pod2.metadata['name'])
```
```
     Type                    Name             Plan       Info
 +   pulumi:pulumi:Stack     python-test-dev  create     3 errors
 +   ├─ kubernetes:core:Pod  foo              create
 +   └─ kubernetes:core:Pod  bar              create

Diagnostics:
  pulumi:pulumi:Stack (python-test-dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
        return future.result()
      File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 38, in run_in_stack
        await RPC_MANAGER.unhandled_exeception()
      File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pulumi/runtime/rpc_manager.py", line 68, in rpc_wrapper
        result = await rpc_function(*args, **kwargs)
      File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 226, in do_register_resource_outputs
        serialized_props = await rpc.serialize_properties(outputs, {})
      File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 57, in serialize_properties
        result = await serialize_property(v, deps, input_transformer)
      File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 145, in serialize_property
        value = await serialize_property(value.future(), deps, input_transformer)
      File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 135, in serialize_property
        future_return = await asyncio.ensure_future(value)
      File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pulumi/output.py", line 129, in run
        transformed: Input[U] = func(value)
      File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pulumi/output.py", line 179, in <lambda>
        return self.apply(lambda v: v[key])
    KeyError: 'name'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```
Running `pulumi up --skip-preview` or explicitly setting `.metadata.name` work as expected.

~My guess is that the autonaming step is happening after the preview stage in the SDK, hence the `KeyError`.~

Edit:
The error only seems to trigger if the `metadata` field is set.

/cc @swgillespie @metral

**Comment by swgillespie** [comment] 2019-04-29 23:18
Does this happen in the node SDK too? Is `pod.metadata.name` `undefined`?

**Comment by lblackstone** [comment] 2019-04-30 19:32
@swgillespie No, it works as expected on the node SDK. Strangely, I can't seem to reproduce in Python now. Not sure if something changed since last Thursday?

**Comment by lblackstone** [comment] 2019-05-01 16:22
Ok, was still able to reproduce with the following program:
```py3
import pulumi
from pulumi_kubernetes.apps.v1 import Deployment

app_labels = {"app": "nginx"}

deployment = Deployment(
    "nginx",
    spec={
        "selector": {"match_labels": app_labels},
        "replicas": 1,
        "template": {
            "metadata": {"labels": app_labels},
            "spec": {"containers": [{"name": "nginx", "image": "nginx"}]}
        }
    })

pulumi.export("name", deployment.metadata["name"])
```

**Comment by lblackstone** [comment] 2019-05-01 16:25
Ok, was able to reproduce with the following program:

```py3
import pulumi
from pulumi_kubernetes.apps.v1 import Deployment

name = 'foo'

appLabels = {"appClass": name}
deployment = Deployment(
    name,
    metadata={
        "labels": appLabels
    },
    spec={
        "selector": {
            "match_labels": appLabels
        },
        "replicas": 1,
        "template": {
            "metadata": {
                "labels": appLabels
            },
            "spec": {
                "containers": [
                    {
                        "name": name,
                        "image": "nginx",
                        "ports": [
                            {
                                "name": "http",
                                "containerPort": 80
                            }
                        ]
                    }
                ]
            }
        }
    }
)

pulumi.export('deployment_name', deployment.metadata['name'])
```

**Comment by lblackstone** [comment] 2019-05-01 16:52
Updated the description with a minimal repro. The error seems to be related to setting the `metadata` field.

**Comment by lblackstone** [comment] 2019-05-17 17:39
I won't have time to fix in M23.

**Comment by joeduffy** [comment] 2019-05-18 01:34
We can't let panics in the CLI go for another sprint. Assigning @ellismg for load balancing.

**Comment by hausdorff** [comment] 2019-05-18 04:34
@swgillespie @lblackstone Looking more closely I am not sure this is a pulumi-kubernetes issue.

`Output#__getitem__` is calling `self.apply(lambda v: v[key])` which is failing because `key == "name"` and that's undefined. The Kubernetes package has no way of statically knowing that this is a computed value, so I don't think anything untoward is being reported from it.

My guess based on my reading of the code (NOTE: could be horribly mistaken) is that what the Python SDK thinks is correct here is actually wrong. I think in the preview stage, it actually does _not_ want to try to resolve this key, but instead, to say that `None` keys are TBD.

Anything completely out of line here, @swgillespie?

**Comment by ellismg** [comment] 2019-05-24 00:48
> My guess based on my reading of the code (NOTE: could be horribly mistaken) is that what the Python SDK thinks is correct here is actually wrong. I think in the preview stage, it actually does not want to try to resolve this key, but instead, to say that None keys are TBD.

I think there is a more fundamental problem here, and it is due to https://github.com/pulumi/pulumi/issues/2433.

What is happening here is that since we are running a preview, we actually run very little code during the [application](https://github.com/pulumi/pulumi/blob/a80d29c89780fa23d5cf6beabb2f64cccdb676c8/pkg/resource/deploy/step.go#L176-L217) of the CreateStep that the step generator generated.  Critically, this means that the `Outputs` value of the state object is never created (which is reasonable, since we can't know what the outputs are without actually doing the operation).  This means that during a preview, there are no output properties for a resource.

However, we have [code in the SDK](https://github.com/pulumi/pulumi/blob/a80d29c89780fa23d5cf6beabb2f64cccdb676c8/sdk/python/lib/pulumi/runtime/rpc.py#L339-L348) (there is similar code in NodeJS) that says if an output property has not been set, and we had a corresponding input with the same name, we should resolve this value using the value that was passed as input.

This means, that, for this example:

```python
pod = Pod(
    "foo",
    spec={"containers": [{"name": "nginx", "image": "nginx"}]}
)

# Works fine
pulumi.export("podname", pod.metadata['name'])
```

Things "work" because the `metadata` property is an output with an unknown value, so the logical apply that `pod.metadata['name']` is doing does not actually run, so we never try to index into the metadata array.  You can convince yourself of this by writing code like `pod.metadata.apply(lambda v: print(f"value is {v}))` and observing that the print does not happen during a preview.

However, when you explicitly pass a metadata bag:

```python
pod2 = Pod(
    "bar",
    metadata={"labels": {"foo": "bar"}},
    spec={"containers": [{"name": "nginx", "image": "nginx"}]}
)

# Fails with KeyError: 'name'
pulumi.export("podname", pod2.metadata['name'])
```

We now resolve the `metadata` output property to `{"labels": {"foo": "bar"}}`.  This means that the implicit apply from:  `pod2.metadata['name'])` now runs, and we blow up.

The node SDK behaves the same way, but the reason the behavior differs is that in Node, instead of throwing, the expression `metadata['name']` returns `undefined`.

**Comment by ellismg** [comment] 2019-05-24 01:45
As a workaround, you can write the following:

```python
pulumi.export("podname", pod.metadata.apply(lambda v: v["name"] if "name" in v else None))
```

Which will work with Pulumi as is today.

**Comment by ellismg** [comment] 2019-05-24 01:53
Closing this as a dupe of pulumi/pulumi#2433, which will address the underlying issue (and make the above workaround no longer needed)

**Closed** 2019-05-24 01:53 UTC
Labels: kind/bug, language/python, priority/P1
