### ISSUE TITLE
Unrecognised getenv function for fluent-bit chart

### ISSUE THREAD

**Issue by Dysproz** [pulumi/pulumi-kubernetes#1941] opened 2022-03-28 08:51 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I'm trying to install [fluent-bit](https://fluent.github.io/helm-charts) helm chart with pulumi using automation API.
However, helm chart fails with error that there's no `getenv` function in daemonset template (exactly [here](https://github.com/fluent/helm-charts/blob/fluent-bit-0.19.20/charts/fluent-bit/templates/daemonset.yaml#L26) referencing to [this](https://github.com/fluent/helm-charts/blob/fluent-bit-0.19.20/charts/fluent-bit/templates/configmap.yaml#L13) configmap template due to error log)

Error log:
```
error: Unhandled exception: Error: invocation of kubernetes:helm:template returned an error:
  failed to generate YAML for specified Helm chart:
  failed to create chart from template: template: fluent-bit/templates/daemonset.yaml:26:28:
  executing "fluent-bit/templates/daemonset.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>:
  error calling include: template: fluent-bit/templates/configmap.yaml:13:9:
  executing "fluent-bit/templates/configmap.yaml" at <tpl .Values.config.inputs $>:
  error calling tpl: error during tpl function execution for "
  [INPUT]
    Name              tail
    Tag               kube.*
    Path              /var/log/containers/*.log
    Refresh_Interval  0.10000000
    {{- if eq (getenv \"CLOUD\") \"aws\"}}
    Parser            docker
    {{- else }}
    Parser            custom-cri
    {{- end }}
    DB                /var/log/flb_kube.db
    DB.locking        true
    Docker_Mode       On
    Read_from_Head    True
    Skip_Long_Lines   On
    storage.type      filesystem
[INPUT]
    Name        tcp
    Listen      0.0.0.0
    Port        5170
    Chunk_Size  8192
    Buffer_Size 2048
    Format      json
":
parse error at (fluent-bit/templates/daemonset.yaml:6): function "getenv" not defined
```

### Steps to reproduce

Component resource for Fluent-bit chart:
```
import { all, ComponentResource, ComponentResourceOptions, Config, Input, output, Output } from "@pulumi/pulumi";
import { Chart } from '@pulumi/kubernetes/helm/v3';
import { Namespace } from '@pulumi/kubernetes/core/v1';
import { Cluster } from "@pulumi/aws/eks";
import { Provider } from "@pulumi/kubernetes";
import { generateKubeconfig } from "../../aws/eks/utils";
import { readFileSync } from "fs";
import { resolve } from "path";
import { getSecrets } from "../../secrets";

export interface TestHelmInputs {
    cluster: Cluster
}

export class TestHelm extends ComponentResource {

    ExternalDNSNamespace: Output<Namespace>;
    ExternalDNSChart: Output<Chart>;

    constructor(
        name: string,
        args: TestHelmInputs,
        opts?: ComponentResourceOptions
    ) {
        super("test:helm:dependencies:dependencies", name, {}, opts);
        let config = new Config();
        let cloud = config.require("cloud");
        let region = config.require(`region`);
        let env = config.require(`env`);

        const kubeconfig = output(generateKubeconfig(args.cluster.name, args.cluster.endpoint, args.cluster.certificateAuthority.data)).apply(JSON.stringify)
        const provider = new Provider("dependencies-custom-provider", { kubeconfig: kubeconfig });

        this.LoggingNamespace = output(new Namespace("logging", {
            metadata: {
                name: "logging"
            }
        }, {
            provider: provider,
            dependsOn: args.cluster
        }))

        this.FluentBitChart = output(new Chart("fluent-bit-chart", {
            chart: "fluent-bit",
            namespace: "logging",
            version: "0.19.20",
            fetchOpts: {
                repo: "https://fluent.github.io/helm-charts",
            },
            values: {
                image: {
                    repository: "fluent/fluent-bit",
                    tag: "1.8.4"
                },
                securityContext: {
                    capabilities: {
                        drop: ["ALL"]
                    },
                    readOnlyRootFilesystem: true
                },
                resources: {
                    limits: {
                        memory: "256Mi"
                    },
                    requests: {
                        cpu: "100m",
                        memory: "128Mi"
                    }
                },
                podAnnotations: {
                    "logging.starburstdata.io/es-index-group": "fluent-bit",
                    "ad.datadoghq.com/fluent-bit.check_names": '["openmetrics"]',
                    "ad.datadoghq.com/fluent-bit.init_configs": "[{}]",
                    "ad.datadoghq.com/fluent-bit.instances": JSON.stringify([
                        {
                            "prometheus_url": "http://%%host%%:2020/api/v1/metrics/prometheus",
                            "metrics": [
                                "fluentbit_input_records_total",
                                "fluentbit_output_proc_records_total",
                                "fluentbit_output_dropped_records_total",
                                "fluentbit_output_retries_total",
                                "fluentbit_output_retries_failed_total",
                                "fluentbit_output_errors_total"
                            ],
                            "namespace": "",
                            "labels_mapper": {
                                "name": "plugin"
                            }
                        }
                    ])
                },
                extraPorts: [
                    {
                        port: 5170,
                        containerPort: 5170,
                        protocol: "TCP",
                        name: "tcp"
                    }
                ],
                tolerations: [
                    {
                        key: "dedicated",
                        operator: "Exists",
                        effect: "NoSchedule"
                    }
                ],
                env: [
                    {
                        name: "CLUSTER_NAME",
                        value: args.cluster.name
                    },
                    {
                        name: "FLUENT_ELASTICSEARCH_HOST",
                        value: getSecret("elasticHost")
                    },
                    {
                        name: "FLUENT_ELASTICSEARCH_PORT",
                        value: getSecret("elasticPort")
                    },
                    {
                        name: "ELASTIC_USER",
                        value: getSecret("elasticUser")
                    },
                    {
                        name: "ELASTIC_PASSWORD",
                        value: getSecret("elasticPassword")
                    },
                    {
                        name: "ENVIRONMENT",
                        value: getSecret("env")
                    },
                    {
                        name: "CLOUD_PROVIDER",
                        value: getSecret("cloud")
                    },
                ],
                luaScripts: {
                    "add_service_field.lua": readFileSync(resolve("./src/lib/helm/fluentBit/configs/add_service_field.lua"), "utf8")
                },
                config: {
                    service: readFileSync(resolve("./src/lib/helm/fluentBit/configs/service_config"), "utf8"),
                    inputs: readFileSync(resolve("./src/lib/helm/fluentBit/configs/inputs_config"), "utf8"),
                    filters: readFileSync(resolve("./src/lib/helm/fluentBit/configs/filters_config"), "utf8"),
                    outputs: readFileSync(resolve("./src/lib/helm/fluentBit/configs/outputs_config"), "utf8"),
                    customParsers: readFileSync(resolve("./src/lib/helm/fluentBit/configs/customParsers_config"), "utf8")
                },
                command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]
            },
        }, {
            provider: provider,
            dependsOn: [args.cluster, this.LoggingNamespace]
        }))



        this.registerOutputs()
    }
}
```

automation API implementation:
```
const pulumiProgram = async () => {
        return await createResource();
    }
    const args: InlineProgramArgs = {
      stackName: "stack",
      projectName: "project",
      program: pulumiProgram,
    };
    const stack = await LocalWorkspace.createOrSelectStack(args);
    console.info("successfully initialized stack");
    console.info("installing plugins...");
    await stack.workspace.installPlugin(cloud, "v4.0.0");
    await stack.workspace.installPlugin("eks", "v0.37.1");
    console.info("plugins installed");
    console.info("setting up config");
    await stack.setConfig(`${cloud}:region`, { value: regionConfig.region });
    console.info("config set");
    console.info("refreshing stack...");
    await stack.refresh({ onOutput: console.info });
    ...

```

**Comment by yann-soubeyrand** [comment] 2022-08-27 08:12
Hello @Dysproz, unless I’m mistaken, it seems that you used the `getenv` function in your `./src/lib/helm/fluentBit/configs/inputs_config` file, but the `getenv` function isn’t supported by Helm (for security reasons).

**Comment by lblackstone** [comment] 2023-07-14 21:24
From https://github.com/pulumi/pulumi-kubernetes/issues/1941#issuecomment-1229148259 it sounds like this is expected behavior of Helm. Closing as "by design" since it's not a provider issue

**Closed by lblackstone** 2023-07-14 21:24 UTC
Labels: kind/bug, resolution/by-design
