### ISSUE TITLE
Deploy cert-manager with Helm: unexpected keyword argument 'status'

### ISSUE THREAD

**Issue by ppawiggers** [pulumi/pulumi-kubernetes#1440] opened 2021-01-21 09:36 UTC
### Problem description

When trying to deploy the cert-manager Helm chart including the CRDs, it results in the following error:

```
CustomResourceDefinition(f"{x}", opts, **obj)))]
TypeError: __init__() got an unexpected keyword argument 'status'
```

### Affected product version(s)

Python:
pulumi            2.17.2
pulumi-gcp        4.7.0
pulumi-kubernetes 2.7.6

CLI: v2.17.2

### Reproducing the issue

```
namespace = Namespace(
    "cert-manager",
    metadata=dict(
        name="cert-manager",
    ),
)

# status field should be removed, see https://github.com/kubernetes-sigs/controller-tools/issues/456
chart = Chart(
    "cert-manager",
    config=ChartOpts(
        chart="cert-manager",
        version="1.1.0",
        namespace=namespace.metadata.name,
        fetch_opts=FetchOpts(
            repo="https://charts.jetstack.io",
        ),
        values=dict(
            installCRDs=True,
        ),
    ),
)
```

**Comment by leezen** [comment] 2021-01-21 19:23
Dupe of https://github.com/pulumi/pulumi-kubernetes/issues/800#issuecomment-697944262

**Closed by leezen** 2021-01-21 19:23 UTC
Labels: resolution/duplicate
