### ISSUE TITLE
Support helm.values.schema for strong typing of values field

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-kubernetes#1866] opened 2022-01-12 15:11 UTC
Some helm charts publish schema options for values files:

https://artifacthub.io/packages/helm/artifact-hub/artifact-hub?modal=values-schema

It would be nice to be able to strongly type those, similar to crd2pulumi

**Comment by jaxxstorm** [comment] 2022-01-12 15:22
Duplicate of #167

**Comment by lblackstone** [comment] 2022-12-21 17:38
Closing as dupe of #167

**Closed by lblackstone** 2022-12-21 17:38 UTC
Labels: kind/enhancement, resolution/duplicate
