### ISSUE TITLE
Deployment diff details doesn't show exact changes

### ISSUE THREAD

**Issue by shinebayar-g** [pulumi/pulumi-kubernetes#1625] opened 2021-06-18 16:07 UTC
## Steps to reproduce

1. Create kubernetes deployment with a single container.
2. Change container specs

I'm changing container's cpu limit in this case. Pulumi diff details doesn't really show the exact changes.

Expected: Pulumi diff details shows exact changes
Actual: Vague change details 

![image](https://user-images.githubusercontent.com/3091558/122589007-bdb82600-d02d-11eb-867c-b3aa86075c8d.png)

**Comment by leezen** [comment] 2021-06-22 22:43
Duplicate of https://github.com/pulumi/pulumi-kubernetes/issues/1576

This looks like a dupe of #1576 and closing as such

**Closed by leezen** 2021-06-22 22:43 UTC
Labels: kind/bug, resolution/duplicate
