### ISSUE TITLE
Hi @gencube, this looks specific to the Helm support in the Kubernetes provider. I’m going to transfer the issue to that repo and someone will take a look.

### ISSUE THREAD

**Issue by gencube** [pulumi/pulumi-kubernetes#2329] opened 2023-02-24 10:53 UTC
Hi @gencube, this looks specific to the Helm support in the Kubernetes provider. I’m going to transfer the issue to that repo and someone will take a look.

_Originally posted by @justinvp in https://github.com/pulumi/pulumi-kubernetes/issues/2328#issuecomment-1442840067_
            
            Hi, this issue is also repeating(same error output) for ingress-nginx, 4.4.2; repo: https://kubernetes.github.io/ingress-nginx.
            
            
![image](https://user-images.githubusercontent.com/663792/221165783-31e6e070-7d98-4264-b4fd-861535bdd054.png)

If you have an email, send me an email and I will attached the sample source code.
ongbp@yahoo.com

**Comment by kpitzen** [comment] 2023-02-27 15:31
This seems to be a duplicate of #2328, so I'm going to close this as such.   Please feel free to reopen if that's not the case!

**Closed by kpitzen** 2023-02-27 15:31 UTC
Labels: resolution/duplicate
