### ISSUE TITLE
Update comments for resource getters, and add getters to the ref docs

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-kubernetes#1612] opened 2021-06-11 17:08 UTC
## Affected feature

Currently `get()` on k8s resources do not show up on docs e.g. https://www.pulumi.com/docs/reference/pkg/kubernetes/core/v1/service/, even though it exists in the src: https://github.com/pulumi/pulumi-kubernetes/blob/master/sdk/nodejs/core/v1/service.ts#L37-L47

It'd be great if we could:
- Show `get()` funcs in the ref docs
- Update the `id` param comment s.t. it clarifies that the ID provided should be the namespaced resource name:
   - Current: `@param id The _unique_ provider ID of the resource to lookup.`
   - Desired: `@param id The _unique_ provider ID of the resource to lookup. This is the namespaced resource name whether or not the resource is namespaced or cluster scoped`
     - e.g.
        - For a service (namespaced): `default/my-svc`
        - For a CRD (cluster/non-namespaced): `certificates.cert-manager.io`

**Comment by clstokes** [comment] 2021-06-11 17:10
Related https://github.com/pulumi/docs/issues/4991

**Comment by lukehoban** [comment] 2023-03-05 18:30
Close as dupe of https://github.com/pulumi/docs/issues/4991.

**Closed by lukehoban** 2023-03-05 18:30 UTC
Labels: kind/enhancement, resolution/duplicate
