### ISSUE TITLE
[kedacore/keda] Install fails on helm3 and Kubernetes v1.18.8

### ISSUE THREAD

**Issue by kmr0877** [pulumi/pulumi-kubernetes#1339] opened 2020-10-05 06:33 UTC
### Problem description
Trying to install kedacore/keda helm chart using python using the code below
```sh
from pulumi_kubernetes.helm.v3 import Chart, ChartOpts, FetchOpts

keda_controller = Chart(
    "keda",
    ChartOpts(
        chart='keda',
        version='2.0.0-rc',
        namespace="keda",
        fetch_opts=FetchOpts(
            repo="https://kedacore.github.io/charts",
        ),
    )
)
```
I am using [docs](https://www.pulumi.com/docs/reference/pkg/kubernetes/helm/v3/chart/#deploy-chart-into-namespace) as reference.
Not sure if i am missing something fundamentally or an issue with the API? I was able to get it working using `kubctl`  CLI from the docs shown in [keda website](https://keda.sh/docs/2.0/deploy/#helm)

### Errors & Logs
```
 error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "C:\Users\kagitam\.pulumi\bin\pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "C:\Users\kagitam\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
        return future.result()
      File "C:\Users\kagitam\.virtualenvs\poc_keda_core-oAoPWSI-\lib\site-packages\pulumi\runtime\stack.py", line 83, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "C:\Users\kagitam\.virtualenvs\poc_keda_core-oAoPWSI-\lib\site-packages\pulumi\runtime\stack.py", line 51, in run_pulumi_func
        await RPC_MANAGER.rpcs.pop()
      File "C:\Users\kagitam\.virtualenvs\poc_keda_core-oAoPWSI-\lib\site-packages\pulumi\runtime\rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File "C:\Users\kagitam\.virtualenvs\poc_keda_core-oAoPWSI-\lib\site-packages\pulumi\runtime\resource.py", line 451, in do_register_resource_outputs
        serialized_props = await rpc.serialize_properties(outputs, {})
      File "C:\Users\kagitam\.virtualenvs\poc_keda_core-oAoPWSI-\lib\site-packages\pulumi\runtime\rpc.py", line 71, in serialize_properties
        result = await serialize_property(v, deps, input_transformer)
      File "C:\Users\kagitam\.virtualenvs\poc_keda_core-oAoPWSI-\lib\site-packages\pulumi\runtime\rpc.py", line 178, in serialize_property
        value = await serialize_property(output.future(), deps, input_transformer)
      File "C:\Users\kagitam\.virtualenvs\poc_keda_core-oAoPWSI-\lib\site-packages\pulumi\runtime\rpc.py", line 164, in serialize_property
        future_return = await asyncio.ensure_future(awaitable)
      File "C:\Users\kagitam\.virtualenvs\poc_keda_core-oAoPWSI-\lib\site-packages\pulumi\output.py", line 113, in get_value  
        val = await self._future
      File "C:\Users\kagitam\.virtualenvs\poc_keda_core-oAoPWSI-\lib\site-packages\pulumi\output.py", line 185, in run
        return await transformed.future(with_unknowns=True)
      File "C:\Users\kagitam\.virtualenvs\poc_keda_core-oAoPWSI-\lib\site-packages\pulumi\output.py", line 113, in get_value  
        val = await self._future
      File "C:\Users\kagitam\.virtualenvs\poc_keda_core-oAoPWSI-\lib\site-packages\pulumi\output.py", line 185, in run        
        return await transformed.future(with_unknowns=True)
      File "C:\Users\kagitam\.virtualenvs\poc_keda_core-oAoPWSI-\lib\site-packages\pulumi\output.py", line 113, in get_value  
        val = await self._future
      File "C:\Users\kagitam\.virtualenvs\poc_keda_core-oAoPWSI-\lib\site-packages\pulumi\output.py", line 154, in run        
        value = await self._future
      File "C:\Users\kagitam\.virtualenvs\poc_keda_core-oAoPWSI-\lib\site-packages\pulumi\output.py", line 338, in gather_futures
        return await asyncio.gather(*value_futures)
      File "C:\Users\kagitam\.virtualenvs\poc_keda_core-oAoPWSI-\lib\site-packages\pulumi\output.py", line 113, in get_value  
        val = await self._future
      File "C:\Users\kagitam\.virtualenvs\poc_keda_core-oAoPWSI-\lib\site-packages\pulumi\output.py", line 154, in run        
        value = await self._future
      File "C:\Users\kagitam\.virtualenvs\poc_keda_core-oAoPWSI-\lib\site-packages\pulumi\output.py", line 175, in run        
        transformed: Input[U] = func(value)
      File "C:\Users\kagitam\.virtualenvs\poc_keda_core-oAoPWSI-\lib\site-packages\pulumi_kubernetes\yaml.py", line 519, in <lambda>
        CustomResourceDefinition(f"{x}", opts, **obj)))]
    TypeError: __init__() got an unexpected keyword argument 'status'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

### pulumi version
v2.11.2

#### kubectl version
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"windows/amd64"}        
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"
```

Local environment
#### Pip freeze
```
Arpeggio==1.9.2
astroid==2.4.2
atomicwrites==1.4.0
attrs==20.2.0
autopep8==1.5.4
certifi==2020.6.20
chardet==3.0.4
colorama==0.4.3
coverage==5.3
dill==0.3.2
grpcio==1.32.0
idna==2.10
iniconfig==1.0.1
isort==5.5.4
lazy-object-proxy==1.4.3
mccabe==0.6.1
packaging==20.4
parver==0.3.1
pipdeptree==1.0.0
pluggy==0.13.1
protobuf==3.13.0
pulumi==2.11.2
pulumi-kubernetes==2.6.1
py==1.9.0
pycodestyle==2.6.0
pylint==2.6.0
pyparsing==2.4.7
pytest==6.1.1
python-dotenv==0.14.0
PyYAML==5.3.1
requests==2.24.0
semver==2.10.2
six==1.15.0
toml==0.10.1
urllib3==1.25.10
wrapt==1.12.1
```

Highly appreciate your response. Cheers!!!

**Comment by lblackstone** [comment] 2020-10-05 19:55
This looks like a duplicate of #800 
See https://github.com/pulumi/pulumi-kubernetes/issues/800#issuecomment-697944262 for a workaround.

**Closed by lblackstone** 2020-10-05 19:55 UTC
