### ISSUE TITLE
skipAwait orchestration

### ISSUE THREAD

**Issue by roderik** [pulumi/pulumi-kubernetes#1648] opened 2021-07-09 19:11 UTC
So, I have a Deployment with a pod that uses a Service (LoadBalancer) to configure some things internally (ports). The service name needs to be passed in the variables/command. I also have a Cloudflare domain name pointing to the service.

At this point I get into a catch-22 situation

- the Deployment won't get deployed because it waits for the service
- but the Service won't be ready until the pod is running
- and setting the service to skipAwait, make the cloudflare url (which fetches the ingress ip/url from the service) to fail since it runs before the service has an ip.

I worked around it for now by hardcoding the service name.

**Comment by lukehoban** [comment] 2021-07-13 22:35
> I worked around it for now by hardcoding the service name.

This is not an entirely unreasonable solution - as you really do here want to rely on Kubernetes' own system for making sure these two mutually dependent things converge.  You don't want a Pulumi level dependency between the Deployment and the Service - you want a Kubernetes level dependency.

That said, this is awkward.  Curious if you have thoughts on how you would have wanted to express this?  I'm not sure this is really a `skipAwait` issue or a more general core Pulumi issue.  I think critical to this is that you are only depending on the name of the Service, and that actually *is* known prior to the Service being "done", and so you really want to be able to get that and pass it along without fully waiting.

**Comment by roderik** [comment] 2021-07-14 07:08
In my "mind" everything is in 2 steps. Step 1, generating whatever yaml pulumi sends to k8s (at this point everything is known apart from k8s updated values like ingress ip, and then 2, deploying and waiting for "ready"

If we could differentiate between the two types of values, the "wait" logic could resolve service.metadata.name for the deployment, and wait for the ip in the cloudflare one

**Comment by lblackstone** [comment] 2023-07-14 20:26
Closing as dupe of #1875

**Closed by lblackstone** 2023-07-14 20:26 UTC
Labels: kind/enhancement, resolution/duplicate
