### ISSUE TITLE
Node: k8s.yaml.ConfigGroupOpts should take yaml as Input<string>

### ISSUE THREAD

**Issue by mbergal** [pulumi/pulumi-kubernetes#1129] opened 2020-05-14 23:00 UTC
Sometimes yaml depends on values coming from other stacks so they are `Input<string>` and not just `string`.

**Comment by lblackstone** [comment] 2020-05-15 13:46
Thanks for the feedback. I'm going to close this as a dupe of https://github.com/pulumi/pulumi-kubernetes/issues/1107 -- I commented on that issue with a workaround.

**Closed by lblackstone** 2020-05-15 13:46 UTC
Labels: kind/enhancement
