### ISSUE TITLE
Helm chart repository unavailability create an error & an infinite loop

### ISSUE THREAD

**Issue by sylver** [pulumi/pulumi-kubernetes#1504] opened 2021-03-23 16:51 UTC
atm https://charts.jetstack.io is unavailable (`cert-manager` chart repository), returning a `503`.
Any attempt to use `pulumi up` even if we don't actually update anything related to this chart crash the program.

## Expected behavior

A `pulumi up` on resources with no relation with a chart / chart repository should not interact with it so no side effects could happen.  
It seems it tries to fetch the chart, while we didn't change anything related, if it does every time we do a `pulumi up`, that's a big waste.

## Current behavior

```
> pulumi up

[...]

    error: Error: Command failed: helm fetch cert-manager --untar --version 0.15.1 --destination /tmp/tmp-324dQzWimBZmSYf --repo https\://charts.jetstack.io
    Error: looks like "https://charts.jetstack.io" is not a valid chart repository or cannot be reached: failed to fetch https://charts.jetstack.io/index.yaml : 503 Service Unavailable
 
    Error: looks like "https://charts.jetstack.io" is not a valid chart repository or cannot be reached: failed to fetch https://charts.jetstack.io/index.yaml : 503 Service Unavailable
    Error: Error: Command failed: helm fetch cert-manager --untar --version 0.15.1 --destination /tmp/tmp-324dQzWimBZmSYf --repo https\://charts.jetstack.io
    Error: looks like "https://charts.jetstack.io" is not a valid chart repository or cannot be reached: failed to fetch https://charts.jetstack.io/index.yaml : 503 Service Unavailable
        at /pulumi/projects/node_modules/@pulumi/helm/v2/helm.ts:250:23
        at /pulumi/projects/node_modules/@pulumi/pulumi/output.js:249:35
        at Generator.next (<anonymous>)
        at /pulumi/projects/node_modules/@pulumi/pulumi/output.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/pulumi/projects/node_modules/@pulumi/pulumi/output.js:17:12)
        at applyHelperAsync (/pulumi/projects/node_modules/@pulumi/pulumi/output.js:228:12)
        at /pulumi/projects/node_modules/@pulumi/pulumi/output.js:182:65
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
    Error: Error: Command failed: helm fetch cert-manager --untar --version 0.15.1 --destination /tmp/tmp-324dQzWimBZmSYf --repo https\://charts.jetstack.io
    Error: looks like "https://charts.jetstack.io" is not a valid chart repository or cannot be reached: failed to fetch https://charts.jetstack.io/index.yaml : 503 Service Unavailable
        at /pulumi/projects/node_modules/@pulumi/helm/v2/helm.ts:250:23
        at /pulumi/projects/node_modules/@pulumi/pulumi/output.js:249:35
        at Generator.next (<anonymous>)
        at /pulumi/projects/node_modules/@pulumi/pulumi/output.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/pulumi/projects/node_modules/@pulumi/pulumi/output.js:17:12)
        at applyHelperAsync (/pulumi/projects/node_modules/@pulumi/pulumi/output.js:228:12)
        at /pulumi/projects/node_modules/@pulumi/pulumi/output.js:182:65
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
...
```

The Error + stackstrace section is being output in an infinite loop, because an `unhandled rejection` apparently, that could be related to the library we use but not sure it could be avoided anyway though : 
```
unhandled rejection: CONTEXT(6326): resource:cert-manager-issuer[kubernetes:cert-manager.io/v1alpha2:ClusterIssuer]
    STACK_TRACE:
    Error:
        at Object.debuggablePromise (/pulumi/projects/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)
        at Object.registerResource (/pulumi/projects/node_modules/@pulumi/pulumi/runtime/resource.js:219:18)
        at new Resource (/pulumi/projects/node_modules/@pulumi/pulumi/resource.js:215:24)
        at new CustomResource (/pulumi/projects/node_modules/@pulumi/pulumi/resource.js:307:9)
        at new ClusterIssuer (/pulumi/projects/node_modules/@materya/pulumi/src/vendors/cert-manager/ClusterIssuer.ts:79:5)
        at new CertManager (/pulumi/projects/node_modules/@materya/pulumi/src/components/k8s/cert-manager/CertManager.ts:82:19)
        at /pulumi/projects/projects/services/index.ts:96:5
        at /pulumi/projects/node_modules/@pulumi/pulumi/output.js:249:35
        at Generator.next (<anonymous>)
        at /pulumi/projects/node_modules/@pulumi/pulumi/output.js:21:71
```

## Steps to reproduce

1. Have a `k8s.helm.v2.Chart` component, at least, already applied ;
2. update something else without any relation to the chart ;
2. Simulate a network failure from the chart repository ;
3. do a `pulumi up`.

## Context (Environment)

Trying to do a `pulumi up` on some others components. 
That's preventing doing any update from now on, until the repository is back online.

## Affected feature

area/helm

**Comment by sylver** [comment] 2021-03-23 16:55
The chart repository is now back online, so the immediate problem is "fixed", but I think that's still a problem worth looking at, it shows there's a problem (imo) on how the charts are handled by Pulumi at each `pulumi up` run.

**Comment by viveklak** [comment] 2021-03-23 20:15
This seems to be a duplicate of #935

**Closed by viveklak** 2021-03-23 20:15 UTC
Labels: kind/bug
