### ISSUE TITLE
Helm V3 unable to use a remote chart absolute URL with dashed chart name

### ISSUE THREAD

**Issue by ctison** [pulumi/pulumi-kubernetes#1587] opened 2021-05-25 13:53 UTC
I need to deploy [fission](https://docs.fission.io/docs/installation/), which is provided as a `tgz` from Github releases.
I saw that [PR](https://github.com/pulumi/pulumi-kubernetes/pull/284) for Helm V2 but when I tried with Helm V3, the following error occurred:

```
Error: invocation of kubernetes:helm:template returned an error: failed to generate YAML for specified Helm chart: failed to load chart from temp directory: stat /var/folders/3y/2vy52_5n0zb92zyrh8p42zmr0000gn/T/helm420775922/fission: no such file or directory
```

The resource:

```ts
new k8s.helm.v3.Chart('fission', {
  chart: 'https://github.com/fission/fission/releases/download/1.12.0/fission-core-1.12.0.tgz',
  values: {
    routerServiceType: 'ClusterIP',
  },
});
```

**Comment by EronWright** [comment] 2024-04-01 20:11
The issue here is that Pulumi is checking for a folder in the unpacked tar named `fission` rather than `fission-core`.

**Comment by EronWright** [comment] 2024-05-14 00:22
I've confirmed that the issue is fixed in the upcoming Chart v4.  This works as expected:

```ts
import * as k8s from "@pulumi/kubernetes";

new k8s.helm.v4.Chart('fission', {
    chart: 'https://github.com/fission/fission/releases/download/1.12.0/fission-core-1.12.0.tgz',
    values: {
      routerServiceType: 'ClusterIP',
    },
  });
```

**Closed by EronWright** 2024-05-14 00:22 UTC
Labels: kind/bug, area/helm, resolution/fixed, mro2
