### ISSUE TITLE
Move Helm/YAML implementations into a single implementation via multi-lang components

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-kubernetes#1559] opened 2021-05-03 03:07 UTC
Today we have 8 implementations of the Helm/YAML support, hand maintained in 4 copies (for each language) and for each of these two variants (for Helm `v2` and `v3`).  We have a lot of issues with subtle bugs or inconsistencies between these implementations, and the multiplicity of implementations leads to higher cost in addressing Helm/YAML issues, and in lower  % of test coverage.

Now that we can support multi-language components within Pulumi providers, we should be able to move the implementations of these components into a single codebase, with a single schema, and code-generate the language-specific SDKs.  

The biggest challenges are likely two missing features in multi-language components today:

* transformations (the Kubernetes-specific variant that is heavily used today) - (we don't support callbacks as arguments to multi-lang components)
* getResource (we don't support methods, and the current methods at least for TypeScript are very "fancy" typewise - which we likely couldn't fully replicate in a language-agnostic model)

**Comment by lblackstone** [comment] 2023-07-14 13:57
Closing as a dupe of https://github.com/pulumi/pulumi-kubernetes/issues/1971 which has some more details

**Closed by lblackstone** 2023-07-14 13:57 UTC
Labels: kind/enhancement, resolution/duplicate, mro1
