### ISSUE TITLE
Apply on output does not work when run without dry-run for status.loadBalancer.ingress

### ISSUE THREAD

**Issue by pgcamus** [pulumi/pulumi-kubernetes#2687] opened 2023-12-04 23:20 UTC
### What happened?

After hitting #2315 (or #2577) when running on `4.3.0`, I attempted an update to `4.5.4` hoping it would fix the problem. Indeed, `preview --diff` and `up --diff` now work, but actually applying the update fails in the same way.

### Example

Relevant code:
```python
           self.service = core.Service(
                f"{self.name}-service",
                metadata=meta.ObjectMetaArgs(
                    namespace=self.namespace,
                    labels=self.labels,
                    annotations=annotations,
                ),
                spec=core.ServiceSpecArgs(
                    selector=self.labels,
                    type=service_type,
                    ports=[
                        core.ServicePortArgs(
                            port=self.service_port,
                            target_port=self.grpc_port,
                        )
                    ],
                ),
                opts=self.resource_options,
           )
           gcp.dns.RecordSet(
                f"dns-rr-{self.name}",
                name=f"{self.name}.{self.project_short_name}.private.",
                type="A",
                ttl=300,
                managed_zone="private",
                rrdatas=[
                    self.service.status.apply(
                        lambda s: s.load_balancer.ingress[0]["ip"]
                    ),
                ],
                project=self.project,
            )
```

Results of running `pulumi up` on this:
```python
    File "/home/builder/src/bando/infra/pulumi/controls/./device/proxy.py", line 110, in <lambda>
        lambda s: s.load_balancer.ingress[0]["ip"]
    TypeError: 'NoneType' object is not subscriptable
    error: update failed
```

### Output of `pulumi about`

CLI          
Version      3.82.1
Go Version   go1.21.0
Go Compiler  gc

Plugins
NAME           VERSION
docker         4.4.2
gcp            6.67.0
google-native  0.32.0
kubernetes     4.5.4
python         unknown
random         4.14.0

Host     
OS       ubuntu
Version  22.04
Arch     aarch64

This project is written in python: executable='/<long path>/bin/python3' version='3.10.9
'

Current Stack: organization/controls/guz-gopher

Found no pending operations associated with guz-gopher

Backend        
Name           95dea339f338
URL            gs://camus-infra-pulumistate/controls
User           builder
Organizations  

Dependencies:
NAME                         VERSION
absl-py                      1.4.0
dnspython                    2.3.0
gcsfs                        2023.6.0
google-cloud-asset           3.19.1
google-cloud-bigquery        3.11.4
google-cloud-bigtable        2.21.0
google-cloud-compute         1.14.1
google-cloud-pubsub          2.18.4
google-cloud-secret-manager  2.16.3
influxdb                     5.3.1
Jinja2                       3.1.2
kubernetes                   24.2.0
Pint                         0.20.1
pip                          22.3.1
prometheus-client            0.14.1
pulumi-docker                4.4.2
pulumi-gcp                   6.67.0
pulumi-google-native         0.32.0
pulumi-kubernetes            4.5.4
pulumi-policy                1.7.0
pulumi-random                4.14.0
PySocks                      1.7.1
python-json-logger           2.0.7
python-socks                 2.2.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment] 2023-12-06 13:54
Hi @pgcamus, thanks for reporting this issue. Unfortunately, I am having some trouble reproducing. 

I made a small LoadBalancer service and then extracted the ip for a dependent resource as you did. (see sample program at https://github.com/mjeffryes/python-repros/tree/add1b0d478de790f1b5ea197540d5e9a48aef1da)

I can see that the service.spec.type is coming from a variable `service_type` is it possible that `service_type` is not "LoadBalancer" so `service.load_balancer` would not be defined?

**Comment by pgcamus** [comment] 2023-12-06 14:35
Ah, apologies I missed copying over `service_type` ("`LoadBalancer"`) and `annotations` (`"networking.gke.io/load-balancer-type"` set to `"Internal"`).

But now attempting to reproduce this, now I can't either :-/ Feel free to close. I'll re-open this with more information (and a better repro!) if I hit it again. Sorry for the noise.

**Comment by rquitales** [comment] 2023-12-12 22:32
Thanks for confirming that you can no longer reproduce the issue. Given the information provided, I'll go ahead and close this ticket. It seems like the issue might have been due to a transient error on the cloud provider's side.

For more context, the code snippet `s.load_balancer.ingress[0]["ip"]` is designed to retrieve the external IP of the exposed service via the cloud provider's LoadBalancer. In scenarios where a service or ingress object is created with the service type set to `LoadBalancer`, the cloud provider's Ingress Controller (e.g., GKE Ingress controller) watches the creation of these objects and initiates the necessary provisioning for the cloud load balancer. Once the IP address is provisioned, the ingress controller updates the status fields of the service object with the address. In this specific instance, it's probable that the provisioning of the external cloud load balancer exceeded our default timeout of 10 minutes (refer to https://github.com/pulumi/pulumi-kubernetes/blob/037bde82c868711084689c0f59348bc00ce23827/provider/pkg/await/service.go#L81). Consequently, when attempting to fetch the external IP address for the DNS record set resource, an empty object will be presented since the status field would be empty.

Please feel free to re-open this issue should this reoccur.

**Closed by rquitales** 2023-12-12 22:32 UTC
Labels: kind/bug, awaiting-feedback, area/server-side-apply
