### ISSUE TITLE
Add ability to ignore KUBECONFIG

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-kubernetes#1853] opened 2022-01-03 21:07 UTC
If you're using explicit providers, and you forget to set a provider on a resource, it can be quite surprising to the user when a resource appears in a different cluster.

It would be good to have a provider option that makes it possible to completely ignore the `KUBECONFIG` environment variable

**Comment by ruckc** [comment] 2022-01-03 21:09
I second this... And also add the ability to set a default provider.

**Comment by iwahbe** [comment] 2022-02-11 13:20
We can force explicit providers with https://github.com/pulumi/pulumi/issues/3383. This won't allow you to ignore `KUBECONFIG`, but will prevent you from forgetting to set a provider on a resource.

**Comment by mnlumi** [comment] 2023-03-27 21:23
Some potential options:
1. Maintain the current behavior of allowing the environmental `KUBECONFIG` to be used by default and create an optional config variable like `pulumi:disable_default_kubeconfig`. Note: This mirrors expected behavior when using `kubectl` to interact with a cluster directly.
2. Create a breaking change that flips behavior to ignore any environmental `KUBECONFIG` by default and create an optional config variable like `pulumi:enable_default_kubeconfig`. Without using the optional variable and not specifying a `KUBECONFIG`, the program would generate an error. This would prevent accidental/unintentional cluster interaction due to using the environmental `KUBECONFIG` when no config is specified.

**Comment by lblackstone** [comment] 2023-05-10 22:02
Option 3: Keep the current behavior for default providers, but make a breaking change for explicit providers to require the `kubeconfig` parameter. Users wanting to avoid the possibility of accidentally loading the ambient `KUBECONFIG` can use the [`disable-default-providers` config option](https://www.pulumi.com/blog/disable-default-providers/#how-to-disable-default-providers)

**Comment by lblackstone** [comment] 2023-05-23 19:37
Closing this issue in favor of #2423, which includes more details about a planned resolution to this problem.

**Closed by lblackstone** 2023-05-23 19:37 UTC
Labels: customer/feedback, kind/enhancement, resolution/duplicate
