### ISSUE TITLE
How to ensure compatibility with manual helm in helm mode

### ISSUE THREAD

**Issue by novohool** [pulumi/pulumi-kubernetes#3255] opened 2024-10-10 08:45 UTC
helm code:
>file: pkg/action/validate.go
```
func mergeAnnotations(obj runtime.Object, annotations map[string]string) error {
	current, err := accessor.Annotations(obj)
	if err != nil {
		return err
	}
	return accessor.SetAnnotations(obj, mergeStrStrMaps(current, annotations))
}

		if err := mergeAnnotations(info.Object, map[string]string{
			helmReleaseNameAnnotation:      releaseName,
			helmReleaseNamespaceAnnotation: releaseNamespace,
		}); err != nil {
			return fmt.Errorf(
				"%s annotations could not be updated: %s",
				resourceString(info), err,
			)
		}
```
pulumi helm need
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: app
    meta.helm.sh/release-namespace: default

```

**Comment by novohool** [comment] 2024-10-12 02:43
> [@novohool](https://github.com/novohool) Sorry but I don't quite follow what you're attempting to achieve here. Would you be able to provide more details with what you want to do here, and what you mean by ensuring compatibility with manual helm mode? If you have a minimal Pulumi program repro of what you have, and the issues you're facing, that'd be a great start.

The annotations for applications deployed using Pulumi and those deployed using Helm are fundamentally inconsistent. If the Helm module in Pulumi is used for deployment, this inconsistency can create significant challenges during emergency situations when manual intervention using Helm is required.

**Comment by novohool** [comment] 2024-10-12 02:47
The annotations  highlight the inconsistency between Pulumi and Helm when used in conjunction. Let's break them down and explain why they might cause issues:

Helm Annotations:
```
meta.helm.sh/release-name: app
meta.helm.sh/release-namespace: default
```
meta.helm.sh/release-name: Helm uses this annotation to track the release name (app in this case). This is crucial for Helm to manage the lifecycle of the deployment (e.g., upgrades, rollbacks).
meta.helm.sh/release-namespace: Helm tracks the namespace (default in this case) where the release is deployed.
These annotations are automatically added by Helm and are used internally to manage the Helm release. Without these annotations, Helm would not be able to correctly manage the application in future updates or rollbacks.

Pulumi Annotations:
```
pulumi.com/patchForce: "true"
pulumi.com/skipAwait: "true"
```
pulumi.com/patchForce: This forces Pulumi to apply a patch to the resource, even if it results in a non-trivial update. This is useful when you need to force updates on certain resources.
pulumi.com/skipAwait: Pulumi skips waiting for the resource to become fully ready before completing the deployment. This is used to speed up deployments by bypassing the readiness checks.
These annotations are specific to Pulumi and help manage how Pulumi applies updates to Kubernetes resources. Helm doesn’t recognize or use these annotations, and they serve no purpose in a Helm-managed deployment.

The Inconsistency:
Helm expects meta.helm.sh/* annotations: These are critical for Helm to recognize and manage the release properly. If you deploy using Pulumi and Pulumi does not include these annotations, Helm will have difficulty managing that resource if you attempt to interact with it later using Helm.

Pulumi-specific annotations: These, like patchForce and skipAwait, are designed for Pulumi’s infrastructure as code (IaC) system, and Helm doesn’t know how to interpret or use them. If you perform manual updates using Helm, Pulumi might mismanage the resource in future deployments because it relies on these annotations to understand the resource’s state.

Challenges:
If you mix Helm and Pulumi for managing the same resources, you might run into scenarios where:

Helm is unaware of Pulumi’s custom patches or forced updates (pulumi.com/patchForce).
Pulumi might bypass certain readiness checks (pulumi.com/skipAwait) that Helm would enforce, causing potential issues during updates.
Helm might fail to recognize a resource if the meta.helm.sh/* annotations are missing, leading to management or rollback difficulties.
Conclusion:
This inconsistency can create serious challenges when switching between Pulumi and Helm for managing the same deployment, especially during emergency situations where manual intervention using Helm is needed. Both systems add their own specific metadata and annotations that aren't always compatible, making coordination tricky.

**Comment by rquitales** [comment] 2024-10-14 18:28
Thanks for the detailed response on this. It appears that in this case, you are referring to the `Chart` resources in Pulumi Helm. The [Helm Chart](https://www.pulumi.com/registry/packages/kubernetes/api-docs/helm/v4/chart) resource renders the templates from your chart and then manages the objects directly with the Pulumi Kubernetes provider. As such, they are managed outside of the Helm lifecycle and will not have any interoperability with using the Helm CLI. You should use Pulumi to manage the lifecycle of these resources/objects, or `kubectl`.

If you wish to have interoperability between Pulumi and the Helm CLI, then you should look into the `Resource` resource. The Pulumi Kubernetes provider uses an embedded version of the Helm SDK to natively manage [Helm Releases](https://helm.sh/docs/glossary/#release) on the target Kubernetes cluster.

Please see this summary that describes both resources and their behaviors. https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/choosing-the-right-helm-resource-for-your-use-case/

**Comment by rquitales** [comment] 2024-10-14 18:30
Closing this issue as resolved since `Chart` resources should not have interoperability with Helm CLI as designed. Please use `Release` instead for this functionality.

**Closed** 2024-10-14 18:30 UTC
Labels: kind/question, area/helm, resolution/by-design
