### ISSUE TITLE
Document dependsOn limitations for ComponentResource resources (Helm, YAML, Kustomize)

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#1773] opened 2021-10-19 14:55 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

`dependsOn` doesn't await child resource creation for several resources in the k8s provider (helm.Chart, yaml.ConfigFile, yaml.ConfigGroup, kustomize.Directory). There is ongoing work to resolve this limitation, but we should document it more clearly in the meantime.

Related to #861

Edit:

Actually, https://github.com/pulumi/pulumi/issues/5642 is done, so we could implement the `ready` attribute [workaround](https://github.com/pulumi/pulumi-kubernetes/pull/1364) in all SDKs as an alternative.

### Affected area/feature

API docs

**Comment by lblackstone** [comment] 2021-11-02 00:30
I think we should do https://github.com/pulumi/docs/issues/6740 before this so that we don't duplicate efforts across multiple repos.

**Comment by EronWright** [comment] 2024-04-17 17:27
Update: the core problem has been fixed in the "v2" implementations of `ConfigFile` and `ConfigGroup`, see https://github.com/pulumi/pulumi-kubernetes/issues/1833#issuecomment-2061802888.

We'll leave this issue open until the problem is fixed for `Chart` with this ticket:
https://github.com/pulumi/pulumi-kubernetes/issues/2847

**Comment by EronWright** [comment] 2024-06-17 18:42
Update: Chart "v4" is out and works great with `dependsOn`, likewise for Kustomize Directory "v2". The documentation on the old components hasn't been updated, that seems like the reminaing work here.

**Closed** 2024-06-17 23:09 UTC
Labels: area/docs, kind/enhancement, area/helm, area/yaml, mro1
