### ISSUE TITLE
Namespace for helm charts not set correctly

### ISSUE THREAD

**Issue by frank-bee** [pulumi/pulumi-kubernetes#701] opened 2019-08-12 06:15 UTC
When using `helm template` the parameter `--namespace` does not have the same effect as if you set the namespace during normal helm install.
(It is used here: https://github.com/pulumi/pulumi-kubernetes/blob/9375329d1ba5bb40d5034efa589378cfc94dc25f/sdk/nodejs/helm/v2/helm.ts#L172)

Instead the namespace must be used e.g. like this:
```
kubectl config set-context $(kubectl config current-context) --namespace=...
helm template....
```

**Comment by lblackstone** [comment] 2019-08-12 15:39
Closing as duplicate of https://github.com/pulumi/pulumi-kubernetes/issues/217

**Closed by lblackstone** 2019-08-12 15:39 UTC
