### ISSUE TITLE
Inconsistent default namespace selection for Helm chart

### ISSUE THREAD

**Issue by pratheekrebala** [pulumi/pulumi-kubernetes#1503] opened 2021-03-22 00:06 UTC
By default, if a helm chart is deployed without a namespace - it is deployed into the `default` namespace. This behavior is different from other resources in this provider which default to the namespace specified in the provider config (or in the kubectl context).

It would be ideal if the chart can be deployed into the namespace specified in the stack config. Alternatively, if this behavior is intentional it would be helpful if this could be documented and/or raise a warning.

Thank you!

## Expected behavior
When no namespace is provided, the Helm chart resource should use the namespace specified in the provider selection logic [specified here](https://github.com/pulumi/pulumi-kubernetes/blob/8de6b379b00e2ab95b24bc176de8b329c670d7cd/provider/pkg/gen/schema.go#L57:L60):

> A namespace can be specified in multiple places, and the precedence is as follows:
>
>   1.  .metadata.namespace set on the resource.
>   2. This namespace parameter.
>   3.  namespace set for the active context in the kubeconfig.

## Current behavior
The default namespace is hard-coded to `default`.  This behavior is [programmed here](https://github.com/pulumi/pulumi-kubernetes/blob/master/provider/pkg/provider/invoke_helm_template.go#L205:L208):

https://github.com/pulumi/pulumi-kubernetes/blob/155b56cd0718c05fe46e50d5fdbcc2f9a27d9f8f/provider/pkg/provider/invoke_helm_template.go#L205:L208

## Steps to reproduce

1. Set default namespace in provider config: `pulumi config set kubernetes:namespace not-default`
2. Create a helm chart without a namespace:
```
from pulumi_kubernetes.helm.v3 import Chart, LocalChartOpts

nginx_ingress = Chart(
    "nginx-ingress",
    LocalChartOpts(
        path="./nginx-ingress",
    ),
)
```
4. Chart is not deployed in the `not-default` namespace as defined in the provider config: `kubectl get all -n not-default`
5. Chart is deployed in the `default` namespace despite the provider config. `kubectl get all -n default`

## Context (Environment)

I am using Pulumi to orchestrate a stack that involves a helm chart along with a few different Kubernetes resources. I was expecting that the behavior for namespace selection would be the same across the entire provider.

## Affected feature

PR: https://github.com/pulumi/pulumi-kubernetes/pull/1323
Issue: https://github.com/pulumi/pulumi-kubernetes/issues/1321

**Comment by EronWright** [comment] 2024-05-14 00:27
I've confirmed that this is fixed in the upcoming Chart v4 resource.  The namespace is defaulted in this order, from lowest to highest priority:
1. The kubecontext namespace
2. The provider's `namespace`  input property
3. The Chart resource's `namespace` input property
4. The object's `.metadata.namespace` field

I would hesitate the change the behavior of Chart v2/v3 because it could be considered a breaking change. I'm closing this as fixed in v4.

**Closed by EronWright** 2024-05-14 00:27 UTC
Labels: kind/bug, area/helm, resolution/fixed, mro2
