### ISSUE TITLE
Create a KubernetesX package

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-kubernetes#589] opened 2019-06-09 22:03 UTC

**Comment by metral** [comment] 2019-06-10 18:41
This a dupe of https://github.com/pulumi/kx/issues/4.

As an aside, is the intent for kx to live in its own repo (`pulumi/kx`) or be a sub-package of `pulumi/kubernetes`? I can see a case for either or, where the former is probably better for `kx` lifecycle management akin to `pulumi/awsx` vs. `pulumi/aws`

**Comment by lblackstone** [comment] 2019-11-06 17:52
We decided to go with a separate package at https://github.com/pulumi/pulumi-kubernetesx

**Closed by lblackstone** 2019-11-06 17:52 UTC
