### ISSUE TITLE
API docs missing .get methods

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#1461] opened 2021-02-03 16:47 UTC
### Problem description

- I saw an issue in the following documentation: https://www.pulumi.com/docs/reference/pkg/kubernetes/core/v1/service/ for example

All of the k8s resources include `.get` methods, but they are missing from the API reference docs. They likely need to be added to the schema as part of codegen.

**Comment by clstokes** [comment] 2021-02-05 16:30
Related https://github.com/pulumi/docs/issues/4991

**Comment by lukehoban** [comment] 2023-03-05 18:30
Close as dupe of https://github.com/pulumi/docs/issues/4991.

**Closed by lukehoban** 2023-03-05 18:30 UTC
Labels: kind/bug, resolution/duplicate
