### ISSUE TITLE
Pulumi destroy stack if wanting to write to yaml

### ISSUE THREAD

**Issue by magnusboman** [pulumi/pulumi-kubernetes#1693] opened 2021-09-02 01:10 UTC
I have created a k8s resource using pulumi. I also want to create the YAML file for the resource so I set the option to do so and then run pulumi up. However, when doing so, it will want to replace the resource. ie, remove it from the k8s cluster and add it as a yaml file.
It would probably be more reasonable if it didn't touch k8s and pulumi state and just wrote the yaml files.

## Steps to reproduce
See attached files (__main__.py and output.txt).

First, run it with `yaml=False` to create the kubernetes resource. Then change to yaml=True and run it again. 
[output.txt](https://github.com/pulumi/pulumi-kubernetes/files/7095325/output.txt)
[pulumi.zip](https://github.com/pulumi/pulumi-kubernetes/files/7095328/pulumi.zip)

**Comment by leezen** [comment] 2021-09-02 23:06
I think the behavior is 'by design' looking at the code you've provided. Because the provider changes from one run to the next, the underlying resources will want to be replaced because of the provider change (after all, they could be completely different k8s clusters).

Does https://github.com/pulumi/pulumi-kubernetes/issues/1327 capture what you're interested in doing?

**Comment by magnusboman** [comment] 2021-09-02 23:23
Yes, this is a dupe of #1327

**Comment by leezen** [comment] 2021-09-03 00:37
Thanks for confirming. I'll close this issue out in favor of that one.

**Closed by leezen** 2021-09-03 00:37 UTC
Labels: kind/bug, resolution/duplicate
