### ISSUE TITLE
Intellisense suggestions for possible values

### ISSUE THREAD

**Issue by philipp-schaerer-lambdait** [pulumi/pulumi-kubernetes#1624] opened 2021-06-18 15:16 UTC
Many of the possible values of some properties often are predefined and could be suggested as an union type. For example at: https://github.com/pulumi/pulumi-kubernetes/blob/e0b0bb820e47d983cd754a055002c121a1056ad4/sdk/nodejs/types/input.ts#L2053-L2056

could be defined as:
```ts
{ type?: pulumi.Input<'Recreate' | 'RollingUpdate'>; }
```

Or was this not done because the types are automatically generated? Or will this already be updated with Issue #1616?

## Affected feature

This affects the types found in the `nodejs` (typescript) SDK.

**Comment by mikhailshilkov** [comment] 2021-06-18 19:56
Thank you for the question @philipp-schaerer-lambdait 

Yes, I believe #1616 tracks exactly this.

**Comment by lblackstone** [comment] 2023-07-14 20:21
Closing as dupe of #1616

**Closed by lblackstone** 2023-07-14 20:21 UTC
Labels: kind/enhancement, resolution/duplicate
