### ISSUE TITLE
Prevent Kubernetes provider from recreation when the cluster gets updated

### ISSUE THREAD

**Issue by muellermatthias** [pulumi/pulumi-kubernetes#1148] opened 2020-05-27 16:26 UTC
### Problem description

I'm currently using the Kubernetes provider together with AKS.
Similar to this code snippet:
```typescript
let aks = new azure.containerservice.KubernetesCluster(name, {
  resourceGroupName: "rg",
  kubernetesVersion: "1.16.9",

  defaultNodePool: {
...
});


new k8s.Provider(name, {
  kubeconfig: aks.kubeAdminConfigRaw,
});
```
Every change in the cluster, even when the change doesn't trigger a recreation, will result in a replacement of the Kubernetes provider and all deployed K8s resources.
I know this setup is not recommended, but I wonder if it's not possibley to either check if the kubeconfig differs or to check if the cluster resource is only updated.

A similar issue would be certificate rotations. You can either manually trigger that for an AKS cluster or they will expire after two years. The provider doesn't recognize any changes to that, when I tested it.

**Comment by leezen** [comment] 2020-05-27 18:38
Re: replacements -- Pulumi is fairly conservative with updates -- anytime an output _might_ change, it will show a diff. I don't think the provider should actually be replaced. For example, I just tried this myself by adding tags to the cluster resource (which is an update). The preview shows a replace for the provider, but doesn't actually do so.

As a way to ensure you don't accidentally end up with a cascading set of replacements, you could attempt a targeted update, e.g. `pulumi up --target <urn>` where `<urn>` is the urn for the cluster. At that point, the various outputs are now 'known' and a subsequent `pulumi up` shouldn't attempt to make any replacements.

This is more or less a dupe of https://github.com/pulumi/pulumi/issues/4326 so I'm going to close this issue and track improving the experience there.

**Closed by leezen** 2020-05-27 18:38 UTC
