### ISSUE TITLE
Sometimes pulumi tries to create helm chart before EKS cluster finish installing API server

### ISSUE THREAD

**Issue by Dysproz** [pulumi/pulumi-kubernetes#2059] opened 2022-07-07 14:29 UTC
### What happened?

Sometimes when running deployment with EKS cluster and helm charts both created with pulumi, helm charts fail with such errors as:
```
error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ConfigMap" in version "v1"
error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
```

Seems as EKS cluster didn't finish installing API server which contains all the basic kinds (as ConfigMap or CRD) while pulumi has already started trying to install helm charts.

Usually running deployment again fix the problem.

### Steps to reproduce

Create EKS cluster with pulumi and pass created EKS cluster as provider for helm charts.

### Expected Behavior

Helm charts are installed without problems

### Actual Behavior

Helm charts fail with errors such as:
```
error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ConfigMap" in version "v1"
error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
```

### Versions used

```
Backend
Name           pulumi.com
URL            https://app.pulumi.com/Szymon
User           Szymon
Organizations  Szymon, starburstdata

Dependencies:
NAME                                  VERSION
@pulumi/command                       0.1.0
@pulumi/eks                           0.37.1
@pulumi/kubernetes                    3.19.0
typescript                            4.5.5
@pulumi/aws                           5.4.0
prettier                              2.5.1
@types/node                           17.0.18
@pulumi/tls                           4.4.0
jest                                  28.1.0
@aws-sdk/client-sts                   3.118.1
@types/jest                           27.5.1
@types/yargs                          17.0.10
ts-jest                               28.0.3
yargs                                 17.4.1
@pulumi/pulumi                        3.35.3

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by ringods** [comment] 2022-07-07 14:42
Duplicate of https://github.com/pulumi/pulumi-eks/issues/720

**Closed as completed by ringods** 2022-07-07 14:42 UTC
Labels: kind/bug, resolution/duplicate, needs-triage
