### ISSUE TITLE
Add equivalent of `kubectl annotate`

### ISSUE THREAD

**Issue by steve-marmalade** [pulumi/pulumi-kubernetes#1615] opened 2021-06-15 01:01 UTC
## Affected feature

This feature would be useful when we need to modify an existing resource. 

A concrete example is that when setting up Workload Identity on Google Kubernetes Engine, we need to add an annotation to a Kubernetes service account (see step 6 in [the instructions](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#authenticating_to)). In my case, I am creating a new namespace in the kubernetes cluster, and so would like to annotate the `default` service account rather than create a new one. I don't see any existing way to patch or annotate an existing kubernetes resource.

Thanks for considering this!

**Comment by leezen** [comment] 2021-06-15 22:07
Marking as a duplicate of #264 

Also please note the workaround using `import` described in https://github.com/pulumi/pulumi-kubernetes/issues/264#issuecomment-560933184

**Closed by leezen** 2021-06-15 22:07 UTC
Labels: kind/enhancement, resolution/duplicate
