### ISSUE TITLE
Helm chart not installing when using digitalocean k8s provider

### ISSUE THREAD

**Issue by polymeris** [pulumi/pulumi-kubernetes#947] opened 2020-01-13 21:06 UTC
### Problem description
I have not found a way to install a helm chart on a digitalocean k8s cluster.

Sample program, which displays the chart as created, but *does not* actually create any resources:

```
"use strict";
const pulumi = require("@pulumi/pulumi");
const digitalocean = require("@pulumi/digitalocean");
const kubernetes = require("@pulumi/kubernetes");

const region = "sfo2";

const nodeSize = "s-1vcpu-2gb";
const nodeCount = 1;

const cluster = new digitalocean.KubernetesCluster(
    "kubernetes-cluster",
    {
        region: region,
        version: "latest",
        nodePool: {name: "default", size: nodeSize, nodeCount: nodeCount}
    }
);

const kubeconfig = cluster.kubeConfigs[0].rawConfig;

const provider = new kubernetes.Provider("kubernetes-provider", {kubeconfig});

const wordpress = new kubernetes.helm.v2.Chart("wpdev", {
        repo: "stable",
        version: "2.1.3",
        chart: "wordpress",
    },
    {providers: {kubernetes: provider}});

module.exports = {kubeconfig};
```

package.json:

```
{
    "name": "digitalocean-javascript",
    "main": "index.js",
    "dependencies": {
        "@pulumi/pulumi": "^1.8.1",
        "@pulumi/kubernetes": "^1.4.3",
        "@pulumi/digitalocean": "^1.4.0"
    }
}

```

### Errors & Logs
```
Previewing update (do-k8s):

     Type                                     Name                 Plan       
 +   pulumi:pulumi:Stack                      test-do-k8s-do-k8s   create     
 +   ├─ kubernetes:helm.sh:Chart              wpdev                create     
 +   ├─ digitalocean:index:KubernetesCluster  kubernetes-cluster   create     
 +   └─ pulumi:providers:kubernetes           kubernetes-provider  create     
 
Resources:
    + 4 to create

Do you want to perform this update? yes
Updating (do-k8s):

     Type                                     Name                 Status      
 +   pulumi:pulumi:Stack                      test-do-k8s-do-k8s   created     
 +   ├─ kubernetes:helm.sh:Chart              wpdev                created     
 +   ├─ digitalocean:index:KubernetesCluster  kubernetes-cluster   created     
 +   └─ pulumi:providers:kubernetes           kubernetes-provider  created     
 
```

### Affected product version(s)

```
$ pulumi version
v1.8.1
$ helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

**Comment by lblackstone** [comment] 2020-01-17 17:36
I wasn't able to reproduce locally. I did have to update the chart version since the one in your example is using an old apiVersion for the StatefulSet, but it worked after that:

```js
"use strict";
const k8s = require("@pulumi/kubernetes");
const digitalocean = require("@pulumi/digitalocean");

const region = "sfo2";

const nodeSize = "s-1vcpu-2gb";
const nodeCount = 1;

const cluster = new digitalocean.KubernetesCluster(
    "kubernetes-cluster",
    {
        region: region,
        version: "latest",
        nodePool: {name: "default", size: nodeSize, nodeCount: nodeCount}
    }
);

const kubeconfig = cluster.kubeConfigs[0].rawConfig;

const provider = new k8s.Provider("kubernetes-provider", {kubeconfig});

const wordpress = new k8s.helm.v2.Chart("wpdev", {
        repo: "stable",
        version: "8.1.1",
        chart: "wordpress",
    },
    {providers: {kubernetes: provider}});
```
<img width="626" alt="Screen Shot 2020-01-17 at 10 33 39 AM" src="https://user-images.githubusercontent.com/9253463/72633144-10f7e780-3915-11ea-9855-c83d0f19064e.png">

Closing this out for now, but feel free to reopen with additional info if it's still not working for you.

**Closed by lblackstone** 2020-01-17 17:36 UTC

**Comment by polymeris** [comment] 2020-01-24 19:26
It seems to have been a helm version issue. Using `2.16` everything works as expected.
