### ISSUE TITLE
Readiness check on Service.get()

### ISSUE THREAD

**Issue by Sodki** [pulumi/pulumi-kubernetes#1238] opened 2020-08-10 18:28 UTC
### Problem description

I'm trying to get information on a (pre-installed) Kubernetes service, but Pulumi complains if there are any problems with the pods. In this particular case I'm expecting those pods to be down, but I need to get information from the service so I can perform a deployment and fix them. I'm using Python:
```
kubernetes.core.v1.Service.get("service",
    "kube-system/kube-dns",
    opts=pulumi.ResourceOptions(provider=kubernetes_provider))
```
At this point Pulumi gives the following error:

```
  kubernetes:core:Service (service):
    error: Preview failed: 2 errors occurred:
        * Resource 'kube-dns' was created but failed to initialize
        * Service does not target any Pods. Selected Pods may not be ready, or field '.spec.selector' may not match labels on any Pods
```

### Affected product version(s)

Pulumi v2.8.2
Pulumi-kubernetes v2.4.2

### Suggestions for a fix

When I got support in Slack I was asked to submit a bug report, since a `.get()` was not expected to run a readiness check.

**Comment by lblackstone** [comment] 2023-07-13 21:35
Closing as a duplicate of #1656

**Closed by lblackstone** 2023-07-13 21:35 UTC
Labels: kind/enhancement, resolution/duplicate
