### ISSUE TITLE
Creating a namespace that already exists returns an `InitError`

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi-kubernetes#164] opened 2018-08-27 15:56 UTC
Instead of an `InitError`, this should probably be a proper error. This is especially bad because the engine will delete the preexisting namespace if the "failed" resource is deleted (e.g. during a destroy).

**Comment by hausdorff** [comment] 2018-08-29 21:49
This is a duplicate of #136.

**Closed by hausdorff** 2018-08-29 21:49 UTC
