### ISSUE TITLE
k8s.helm.v3.Release unable to install images from AWS ECR helm chart

### ISSUE THREAD

**Issue by gencube** [pulumi/pulumi-kubernetes#2364] opened 2023-04-18 03:09 UTC
### What happened?

![image](https://user-images.githubusercontent.com/663792/232656866-54fc9195-4a8a-4408-9e34-bfd696d0fe40.png)
![image](https://user-images.githubusercontent.com/663792/232659782-409320cc-2bba-4e8a-9f96-79c3a3be3ebc.png)
![image](https://user-images.githubusercontent.com/663792/232660638-bf544ae1-acb0-4aa2-8061-0db67692670d.png)

- AWS login authentication is successful.
- helm chart exist in AWS ECR
- it was successfully pushed into the private ECR using the same authentication account.
- k8s.helm.v3.Release not able to load from authenticated ECR and gave 401 error.

## I was following instruction here:
- https://docs.aws.amazon.com/AmazonECR/latest/userguide/ECR_on_EKS.html

### Expected Behavior

Able to pull and install from AWS ECR private repository helm chart.

### Steps to reproduce
![image](https://user-images.githubusercontent.com/663792/232664032-be901c4e-8e0f-4bcc-9cb8-19f05fdfb90b.png)

- aws ecr create-repository --region xxx-2  --repository-name redis
- helm pull redis --repo https://charts.bitnami.com/bitnami --version 16.13.2
- helm push redis-16.13.2.tgz oci://6...9.dkr.ecr.xxx-2.amazonaws.com
- pulumi up 

### Output of `pulumi about`

![image](https://user-images.githubusercontent.com/663792/232661071-9cc0b394-b3b9-4f3e-9ead-842129bdc295.png)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lblackstone** [comment] 2023-04-18 12:40
Hi @gencube, I think that you're running into https://github.com/pulumi/pulumi-kubernetes/issues/1914. That issue suggests that you can get creds with `helm registry login`, but it looks like you already tried that. I'd suggest asking on that issue thread to see if anyone has found a workaround.

**Comment by mikhailshilkov** [comment] 2023-04-24 10:02
@gencube Do you think we should close this issue as a duplicate of #1914?

**Comment by mikhailshilkov** [comment] 2023-04-25 12:57
@gencube I'm not saying it is resolved. #1914 is still open.

Closing an issue as a duplicate of another open issue means that they track the same issue, it directs all users to the same place and avoids scattered discussions.

**Comment by lblackstone** [comment] 2023-07-14 22:38
Closing as duplicate of #1914 since it's the same underlying issue

**Closed by lblackstone** 2023-07-14 22:38 UTC
Labels: kind/bug, resolution/duplicate, area/helm
