### ISSUE TITLE
Add additional matrix for CI to test across multiple supported k8s versions

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi-kubernetes#1862] opened 2022-01-07 17:23 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Our CI tests currently run against a static 1.19 version. There are tangible differences between behavior across minor versions which we should validate explicitly by running our integration tests across a matrix of supported k8s versions instead. This doesn't have to be exhaustive but will improve the fidelity of our tests. It is not sufficient for us to simply test with the latest minor version either. For instance 1.19 adds self links to metadata while newer cluster versions don't - see https://github.com/pulumi/pulumi-kubernetes/pull/1846/commits/bfd116e645916fbc781d441e2617a4812f437f12 for something that wasted a bunch of time as a result. Since our customers use a wide array of k8s versions, our tests should be somewhat representative of the same diversity.

### Affected area/feature
* Testing

**Comment by lblackstone** [comment] 2023-07-14 21:13
Dupe of #913

**Closed by lblackstone** 2023-07-14 21:13 UTC
Labels: kind/enhancement, kind/engineering, resolution/duplicate
