### ISSUE TITLE
Support for AWS Native clusters as providers

### ISSUE THREAD

**Issue by SpecLad** [pulumi/pulumi-kubernetes#2435] opened 2023-06-01 14:42 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
From the documentation it looks like you can easily use clusters created by the Pulumi EKS library as providers. I'd like to see something like that for the Pulumi AWS Native library. I was able to integrate AWS Native with this library manually, by generating a kubeconfig from cluster attributes and creating a `pulumi_kubernetes.Provider` object with that kubeconfig, but it would be nice to have a built-in solution.

**Comment by rquitales** [comment] 2023-06-02 19:13
Thank you for submitting this new feature request. We appreciate your input, and we will definitely add it to our backlog for further consideration and prioritization.

It's important to note that AWS Native is currently in Public Preview and has not yet been marked as Generally Available (GA). This means that our focus may primarily be on addressing critical issues and stabilizing the existing functionality during this phase. While we acknowledge the value of the feature you suggested, we want to maintain transparency and inform you that unless there is significant user demand for it, it may not be prioritized for immediate implementation. We will carefully evaluate the demand and prioritize features accordingly to ensure the best possible experience for our users.

Thank you once again for your input, and we will keep you updated on any developments related to this feature request. If you have any additional ideas or suggestions, please don't hesitate to reach out. We appreciate your support.

**Comment by lblackstone** [comment] 2023-07-14 22:58
Closing as a duplicate of #2127

**Closed by lblackstone** 2023-07-14 22:58 UTC
Labels: area/providers, kind/enhancement, resolution/duplicate
