### ISSUE TITLE
Helm not correctly installing prometheus-operator chart

### ISSUE THREAD

**Issue by carterwilliamson** [pulumi/pulumi-kubernetes#223] opened 2018-09-25 23:26 UTC
Installing `prometheus-operator:0.0.29` then `kube-prometheus:0.0.105` results in
```
error: Plan apply failed: unable to fetch resource description for monitoring.coreos.com/v1alpha1: the server could not find the requested resource
```
This error happens when `prometheus-operator` doesn't successfully install.
Using helm to install these charts works as expected.

The `prometheus-operator` chart installs via Pulumi by itself, but when trying to add the `kube-prometheus` chart the error above is thrown.

Confirmed this bug with @hausdorff

**Comment by hausdorff** [comment] 2018-09-25 23:48
Can reproduce, will fix ASAP.

**Comment by hausdorff** [comment] 2018-09-26 00:07
I think this is actually a problem with the Helm Chart itself:

* The Chart looks like it's using `.Capabilities` to automatically fill in the `apiVersion` of the `ServiceMonitor`.
* Since we're not using Tiller, we can't introspect on the API server's capabilities, and thus falling back to `monitoring.coreos.com/v1alpha1` as the `GroupVersion`.
* But, the version of the Prometheus operator we're installing with that Chart actually installs `monitoring.coreos.com/v1`; in particular, it does _not_ install the `v1alpha` variants.
* Thus, when we try to submit the `ServiceMonitor`, we fail, because the `v1alpha1` version of that group was not installed on the API server.

The fix is pretty simple. Borrowing the code from #215, the following ought to do the trick:

```typescript
function useMonitoringV1(o: any) {
    if (o && o.apiVersion == "monitoring.coreos.com/v1alpha1" && o.kind == "ServiceMonitor") {
        o.apiVersion = "monitoring.coreos.com/v1";
    }
}

let kubePrometheus = new helm.v2.Chart("kube-prometheus", {
  repo: "coreos",
  chart: "kube-prometheus",
  version: config.kube.version,
  transformations: [useMonitoringV1]
}, { providers: { kubernetes: provider }, dependsOn: operator });
```

**Comment by hausdorff** [comment] 2018-09-26 00:10
Ok, using @carterwilliamson's exact code I am able to say this fully works on my machine. We could close this issue, but I'm curious to hear opinions on how we might make these sorts of things clear to the user? There is a high likelihood errors like this will cause the user to think this is a Pulumi problem, when really it's a Pulumi _and_ `helm template` problem. :) @lukehoban @joeduffy thoughts?

**Comment by lukehoban** [comment] 2018-09-26 02:03
> this works on my machine

You mean that after applying the transforms this works, but the chart itself does not deploy correctly without this?

Is the same thing true if you just `helm install` outside Pulumi?  If so, worth reporting the bug on the chart. Also, what error does Helm/kubectl report for this?  Seems we should be reporting something morally similar. I wouldn’t be too surprised if it’s similar to what we already do report here.

**Comment by hausdorff** [comment] 2018-09-26 05:29
No, it works with `helm install`, because `helm install` goes through Tiller, which has access to the API server's `.Capabilities`. If you were using `helm template` and `kubectl apply` you'd see the same error text as us, because we both use client-go.

**Comment by hausdorff** [comment] 2018-10-10 19:57
Per extensive discussion in #224, we've upstreamed the fix to the Helm Chart (coreos/prometheus-operator#1990). I don't think there's anything else for us to do to solve the acute pain of this issue, so I'm closing it for now. We have other issues to track more general aspects of this problem, like #196.

**Closed by hausdorff** 2018-10-10 19:57 UTC
Labels: kind/bug
