### ISSUE TITLE
[improvement] - Support Input<string> for YAML path

### ISSUE THREAD

**Issue by danfhernandez** [pulumi/pulumi-kubernetes#1107] opened 2020-05-07 14:49 UTC
### Problem description

Output as an input for the `file` parameter on the `yaml.ConfigFile` resource isn't supported.  This would be useful to have in certain scenarios when you want to construct the source of the file from another resource. 

### Errors & Logs

```
Type 'Output<string>' is not assignable to type 'string | undefined'.
  Type 'Output<string>' is not assignable to type 'string'
```
### Reproducing the issue

``` 
import * as pulumi from "@pulumi/pulumi"
import * as k8s from "@pulumi/kubernetes";

const provider = new k8s.Provider("render-yaml", {
    renderYamlToDirectory: "rendered",
});

const appLabels = { app: "nginx" };
const deployment = new k8s.apps.v1.Deployment("nginx", {
    spec: {
        selector: { matchLabels: appLabels },
        replicas: 1,
        template: {
            metadata: { labels: appLabels },
            spec: { containers: [{ name: "nginx", image: "nginx" }] }
        }
    }
}, { provider });

const filePath = pulumi.interpolate `./rendered/${deployment.id}.yaml`

const yaml = new k8s.yaml.ConfigFile("nginx-deploy", {
    file: filePath
}, { provider })

export const name = deployment.metadata.name;

```

**Comment by lblackstone** [comment] 2020-05-15 13:45
As a workaround for this issue, you can call the `ConfigFile` or `ConfigGroup` constructor within an `apply`, which will unwrap the `Input<string>` for you. Note that this will reduce the accuracy of previews since the input may not be known.

**Comment by lblackstone** [comment] 2021-10-29 21:40
@osela In general, it's not possible to preview resources created inside an apply if the input is unknown. (apply is a callback that only runs once the input resolves, so it doesn't run when previewing an unknown input).

You would have more flexibility and better previews with native SDK resources, but it's unfortunately not always possible with YAML.

**Comment by antifuchs** [comment] 2021-11-24 10:00
So I'm running into this (via #1129) as well, but for me, the issue seems even weirder: actually applying the `apply`ed `ConfigGroup` with yaml from an input causes `pulumi up` to error out with "error: Duplicate resource URN 'urn:pulumi:asf::mzcloud::kubernetes:yaml:ConfigGroup::instances-eu-west-1-link-to-backend'; try giving it a unique name" (but that URN is the only one in the entire stack - in fact, the only resource that exists has that error on it in the resource viewer).

Does that mean that the `ConfigGroup` is re-created if the input yaml changes, but it collides with itself? I'm not sure, but it seems like a really weird one.

**Comment by lblackstone** [comment] 2021-12-01 17:54
> Does that mean that the `ConfigGroup` is re-created if the input yaml changes, but it collides with itself? I'm not sure, but it seems like a really weird one.

@antifuchs That shouldn't be the case, so I'd guess it's related to something about the apply command you're using. Can you open a new issue with repro code if you're still having this issue?

**Comment by almson** [comment] 2024-01-08 11:35
Please just fix it. What is the problem?

**Comment by renannprado** [comment] 2024-03-08 00:28
> As a workaround for this issue, you can call the `ConfigFile` or `ConfigGroup` constructor within an `apply`, which will unwrap the `Input<string>` for you. Note that this will reduce the accuracy of previews since the input may not be known.

Thanks for the workaround. It's easy to forget such tricks when you try to stick to good practices.

I've just crossed this issue because I can't use crossplane resources with Pulumi due to https://github.com/pulumi/crd2pulumi/issues/126, therefore I need to use yaml files, but in my situation I need to interpolate things in the yaml file I'm applying.

**Comment by EronWright** [comment] 2024-03-29 21:24
Closing as a duplicate of https://github.com/pulumi/pulumi-kubernetes/issues/2203

**Closed by EronWright** 2024-03-29 21:24 UTC
Labels: kind/enhancement, resolution/duplicate, mro1
