### ISSUE TITLE
yaml.ConfigGroup should error if file does not exist

### ISSUE THREAD

**Issue by brandonkal** [pulumi/pulumi-kubernetes#938] opened 2020-01-05 08:58 UTC
### Problem description

I noticed while refactoring that if I moved a yaml file so that the files array pointed to a no-longer-existing file, pulumi planned to delete the resources. Pulumi should instead report that it was unable to read the file.

### Affected product version(s)

1.4.1

### Suggestions for a fix
If any files cannot be read, pulumi should return an error.

**Comment by pyoio** [comment] 2021-12-22 16:22
Just bumped into this on TypeScript. If you specify a `ConfigFile` with a `file: ` that doesn't exist, it throws an `ENOENT` because it uses `fs.readFileSync`.

However, when using a `ConfigGroup`, if you provide a list of `files: [ ... ]` that don't exist (file names, no patterns), the paths get passed to `glob.sync(...)` which returns an empty array (as no files match the paths provided). We had an issue where a ConfigGroup was creating 0 ConfigFiles under the hood which feels like maybe it could at least be a warning.

In the interest of breaking changes, perhaps a config flag such as `<warn|error>OnNoMatches` (except with a better name) could be used to indicate if a warning/error should be raised if all (or any?) pattern(s) yield no results? Happy to raise a PR but would rather ask about the best way to go about it

**Comment by lblackstone** [comment] 2022-01-10 16:23
Rather than adding a config flag, I think it would be better to always return an error if the ConfigGroup doesn't match any files. I can't think of a reason why deploying an empty ConfigGroup would be intended behavior, and if it was, the ConfigGroup could be enabled conditionally instead.

**Comment by pyoio** [comment] 2022-01-11 18:25
> Rather than adding a config flag, I think it would be better to always return an error if the ConfigGroup doesn't match any files. I can't think of a reason why deploying an empty ConfigGroup would be intended behavior, and if it was, the ConfigGroup could be enabled conditionally instead.

Good point! Was overly wary of changing existing semantics 😁

**Comment by EronWright** [comment] 2024-04-02 01:29
Good news, this is fixed in the new `v2.ConfigGroup` resource, it produces an error when a given file is missing, if the value is not a pattern.

**Closed by EronWright** 2024-04-02 01:29 UTC
Labels: kind/bug
