### ISSUE TITLE
Helm Chart Values with Periods in the name aren't getting applied

### ISSUE THREAD

**Issue by NArnott** [pulumi/pulumi-kubernetes#1380] opened 2020-11-13 20:37 UTC
### Problem description

Helm Values that have a period in the name don't appear to work.

I'm trying to install RabbitMQ to K8s using C# Pulumi using the following:

    //Helm Chart: https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq
    new Chart("rmq-helm-chart", new ChartArgs()
    {
        Namespace = ns.Metadata.Apply(x => x.Name),

        Chart = "bitnami/rabbitmq",
        Version = "8.0.2",

        Values =
        {
            { "replicaCount", replicas },
            { "auth.password", "abc" },
        }
    }, new ComponentResourceOptions() { Parent = this });

This should be the same as calling the CLI:
`helm install rmq --set replicaCount=2 --set auth.password="abc" -n rabbitmq bitnami/rabbitmq`

When running with Pulumi, the `replicaCount` values works just fine, but it doesn't pick up `auth.password`, or any other value with a period in it. The equivalent helm CLI works just fine, so I don't see it as a problem with the chart itself.

Am I doing something wrong, or is this a bug?

### Affected product version(s)

Pulumi 2.13.2

**Comment by mikhailshilkov** [comment] 2020-11-23 17:09
Hi @NArnott 

Which Helm version were you using. I tried with V3 (so, `using Pulumi.Kubernetes.Helm.V3;`) and ran debug logs with `pulumi pre -v=9 --logtostderr &> log.txt`, where I see `"values":{"auth.password":"abc","replicaCount":2}` which LGTM. Could you try that as well?

**Comment by chris-sanders** [comment] 2021-04-25 15:03
I ran across this having what I suspect is the same issue. For anyone else in the future that makes this mistake, Helm accepts dotted values on the command line which is expanded into nested configurations. The values on the chart object isn't setting command line values as I initially assumed. It's setting the values file. Ref: https://www.pulumi.com/docs/reference/pkg/kubernetes/helm/v3/chart/#set-chart-values

Dotted values are passed through but don't map to what what you intend. Pass a mapping of mappings into the value field like you would the values.yaml file and you'll get your expected results. I suspect you can close this as not a bug.

**Closed** 2023-07-14 13:53 UTC
Labels: kind/bug, resolution/by-design, mro2
