### ISSUE TITLE
Can't install Prometheus Operator via Helm3: Duplicate resource URN

### ISSUE THREAD

**Issue by Aaronontheweb** [pulumi/pulumi-kubernetes#1225] opened 2020-07-29 21:30 UTC
### Problem description
Using Pulumi 2.7.1, I've been trying to install the [prometheus-operator Helm chart from the stable repo](https://github.com/helm/charts/tree/master/stable/prometheus-operator), version 9.2.2.

I'm using the following Pulumi definition to do it:

```csharp
public static void DeployPrometheus(CustomResourceOptions k8sCustomResourceOptions)
{
    var appName = "prometheus";
    var appLabels = new InputMap<string>
    {
        {"app", appName}
    };

    /**
     * Enable Prometheus data storage on a persistent volume claim
     */
    // See https://docs.microsoft.com/en-us/azure/aks/azure-disks-dynamic-pv for more details on provisioning
    var prometheusVolumeClaim = new Pulumi.Kubernetes.Core.V1.PersistentVolumeClaim("promtheus-volume-claim", new PersistentVolumeClaimArgs()
    {
        Metadata = new ObjectMetaArgs
        {
            Name = $"prometheus",
        },
        ApiVersion = "v1",
        Spec = new PersistentVolumeClaimSpecArgs
        {
            AccessModes = "ReadWriteOnce", // can only be mounted and written to by a single 
            StorageClassName = "default", // standard disk,
            Resources = new ResourceRequirementsArgs
            {
                Requests =
                {
                    // TODO: make storage amounts configurable
                    { "storage", "15Gi"} // 15Gb of storage
                }
            }
        }
    }, k8sCustomResourceOptions);

    // need to work around CRD bug here https://github.com/pulumi/pulumi-kubernetes/issues/1023
    //var configGroup = new ConfigGroup("prometheus-crds", new ConfigGroupArgs
    //{
    //    Files = new[]{ "https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.38/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml",
    //    "https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.38/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml",
    //    "https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.38/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml",
    //    "https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.38/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml",
    //    "https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.38/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml",
    //    "https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.38/example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml"},
    //}, new ComponentResourceOptions()
    //{
    //    Provider = k8sCustomResourceOptions.Provider
    //});

    var prometheusChartValues = prometheusVolumeClaim.Metadata.Apply(f => new Dictionary<string, object>()
    {
        /* define Kubelet metrics scraping */
        ["kubelet"] = new Dictionary<string, object>
        {
            ["enabled"] = true,
            ["serviceMonitor"] = new Dictionary<string, object>
            {
                ["https"] = false
            },
        },
        ["kubeControllerManager"] = new Dictionary<string, object>
        {
            ["enabled"] = false
        },
        ["kubeScheduler"] = new Dictionary<string, object>
        {
            ["enabled"] = false
        },
        ["kubeEtcd"] = new Dictionary<string, object>
        {
            ["enabled"] = false
        },
        ["kubeProxy"] = new Dictionary<string, object>
        {
            ["enabled"] = false
        },
        ["prometheusOperator"] = new 
        {
            createCustomResource = false
        },
        ["prometheus"] = new Dictionary<string, object>
        {
            ["prometheusSpec"] = new Dictionary<string, object>
            {
                ["volumes"] = new[]
                {
                    new Dictionary<string, object>
                    {
                        ["name"] = "prometheus-storage",
                        ["persistentVolumeClaim"] = new Dictionary<string, object>{
                            ["claimName"] = f.Name
                        },
                    }
                },
                ["volumeMounts"] = new[] {
                    new Dictionary<string, object>
                    {
                        ["name"] = "prometheus-storage",
                        ["mountPath"] = "/prometheus/"
                    }
                }
            }
        },
    });

    var objectNames = new ConcurrentBag<string>();

    ImmutableDictionary<string, object> OmitCustomResource(ImmutableDictionary<string, object> obj, CustomResourceOptions opts)
    {
        var metadata = (ImmutableDictionary<string, object>)obj["metadata"];
        var resourceName = $"{obj["kind"]}.{metadata["name"]}";

        if (objectNames.Contains(resourceName))
        {
            Console.WriteLine($"Deduplicated [{resourceName}]");
            return new Dictionary<string, object>
            {
                ["apiVersion"] = "v1",
                ["kind"] = "List",
                ["items"] = new Dictionary<string, object>(),
            }.ToImmutableDictionary();
        }
        objectNames.Add(resourceName);
        Console.WriteLine(resourceName);
        return obj;
    }

    var prometheusOperatorChart = new Chart("pm", new Pulumi.Kubernetes.Helm.ChartArgs
    {
        Repo = "stable",
        Chart = "prometheus-operator",
        Version = "9.2.2",
        Namespace = "monitoring",
        Values = prometheusChartValues,
        Transformations = { OmitCustomResource }
    }, new ComponentResourceOptions()
    {
        Provider = k8sCustomResourceOptions.Provider,
        //DependsOn = configGroup
    });
}
```

I'm using the transformation mechanism for the Helm chart to attempt to resolve the error

### Errors & Logs
I get a similar error to this one each time I attempt to run this chart installation:

```
 error: Duplicate resource URN 'urn:pulumi:dev::sdkbin-resources::kubernetes:helm.sh/v2:Chart$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::monitoring/pm-prometheus-operator-alertmanager'; try giving it a unique name
```

It's always one of the custom resource definitions - it's not always the same one that throws the error though. This time it was the `alertmanager` CRD that caused the error - other times it's been the `prometheus` CRD or the `node-exporter`.

I attempted to fix this issue by adding the `OmitCustomResource` filtering code to my application to omit any duplicates - I also added some logging to see what those filtered / unfiltered outputs were:

1. CustomResourceDefinition.alertmanagers.monitoring.coreos.com
2. CustomResourceDefinition.podmonitors.monitoring.coreos.com
3. CustomResourceDefinition.prometheuses.monitoring.coreos.com
4. CustomResourceDefinition.prometheusrules.monitoring.coreos.com
5. CustomResourceDefinition.servicemonitors.monitoring.coreos.com
6. CustomResourceDefinition.thanosrulers.monitoring.coreos.com
7. PodSecurityPolicy.pm-grafana
8. PodSecurityPolicy.pm-grafana-test
9. PodSecurityPolicy.pm-kube-state-metrics
10. PodSecurityPolicy.pm-prometheus-node-exporter
11. PodSecurityPolicy.pm-prometheus-operator-alertmanager
12. PodSecurityPolicy.pm-prometheus-operator-operator
13. PodSecurityPolicy.pm-prometheus-operator-prometheus
14. ServiceAccount.pm-grafana
15. ServiceAccount.pm-grafana-test
16. ServiceAccount.pm-kube-state-metrics
17. ServiceAccount.pm-prometheus-node-exporter
18. ServiceAccount.pm-prometheus-operator-alertmanager
19. ServiceAccount.pm-prometheus-operator-operator
20. ServiceAccount.pm-prometheus-operator-prometheus
21. Secret.pm-grafana
22. Secret.alertmanager-pm-prometheus-operator-alertmanager
23. ConfigMap.pm-grafana-config-dashboards
24. ConfigMap.pm-grafana
25. ConfigMap.pm-grafana-test
26. ConfigMap.pm-prometheus-operator-grafana-datasource
27. ConfigMap.pm-prometheus-operator-apiserver
28. ConfigMap.pm-prometheus-operator-cluster-total
29. ConfigMap.pm-prometheus-operator-k8s-coredns
30. ConfigMap.pm-prometheus-operator-k8s-resources-cluster
31. ConfigMap.pm-prometheus-operator-k8s-resources-namespace
32. ConfigMap.pm-prometheus-operator-k8s-resources-node
33. ConfigMap.pm-prometheus-operator-k8s-resources-pod
34. ConfigMap.pm-prometheus-operator-k8s-resources-workload
35. ConfigMap.pm-prometheus-operator-k8s-resources-workloads-namespace
36. ConfigMap.pm-prometheus-operator-kubelet
37. ConfigMap.pm-prometheus-operator-namespace-by-pod
38. ConfigMap.pm-prometheus-operator-namespace-by-workload
39. ConfigMap.pm-prometheus-operator-node-cluster-rsrc-use
40. ConfigMap.pm-prometheus-operator-node-rsrc-use
41. ConfigMap.pm-prometheus-operator-nodes
42. ConfigMap.pm-prometheus-operator-persistentvolumesusage
43. ConfigMap.pm-prometheus-operator-pod-total
44. ConfigMap.pm-prometheus-operator-prometheus
45. ConfigMap.pm-prometheus-operator-statefulset
46. ConfigMap.pm-prometheus-operator-workload-total
47. ClusterRole.pm-grafana-clusterrole
48. ClusterRole.pm-kube-state-metrics
49. ClusterRole.psp-pm-kube-state-metrics
50. ClusterRole.psp-pm-prometheus-node-exporter
51. ClusterRole.pm-prometheus-operator-operator
52. ClusterRole.pm-prometheus-operator-operator-psp
53. ClusterRole.pm-prometheus-operator-prometheus
54. ClusterRole.pm-prometheus-operator-prometheus-psp
55. ClusterRoleBinding.pm-grafana-clusterrolebinding
56. ClusterRoleBinding.pm-kube-state-metrics
57. ClusterRoleBinding.psp-pm-kube-state-metrics
58. ClusterRoleBinding.psp-pm-prometheus-node-exporter
59. ClusterRoleBinding.pm-prometheus-operator-operator
60. ClusterRoleBinding.pm-prometheus-operator-operator-psp
61. ClusterRoleBinding.pm-prometheus-operator-prometheus
62. ClusterRoleBinding.pm-prometheus-operator-prometheus-psp
63. Role.pm-grafana
64. Role.pm-grafana-test
65. Role.pm-prometheus-operator-alertmanager
66. RoleBinding.pm-grafana
67. RoleBinding.pm-grafana-test
68. RoleBinding.pm-prometheus-operator-alertmanager
69. Service.pm-grafana
70. Service.pm-kube-state-metrics
71. Service.pm-prometheus-node-exporter
72. Service.pm-prometheus-operator-alertmanager
73. Service.pm-prometheus-operator-coredns
74. Service.pm-prometheus-operator-operator
75. Service.pm-prometheus-operator-prometheus
76. DaemonSet.pm-prometheus-node-exporter
77. Deployment.pm-grafana
78. Deployment.pm-kube-state-metrics
79. Deployment.pm-prometheus-operator-operator
80. Alertmanager.pm-prometheus-operator-alertmanager
81. MutatingWebhookConfiguration.pm-prometheus-operator-admission
82. Prometheus.pm-prometheus-operator-prometheus
83. PrometheusRule.pm-prometheus-operator-alertmanager.rules
84. PrometheusRule.pm-prometheus-operator-general.rules
85. PrometheusRule.pm-prometheus-operator-k8s.rules
86. PrometheusRule.pm-prometheus-operator-kube-apiserver-availability.rules
87. PrometheusRule.pm-prometheus-operator-kube-apiserver-slos
88. PrometheusRule.pm-prometheus-operator-kube-apiserver.rules
89. PrometheusRule.pm-prometheus-operator-kube-prometheus-general.rules
90. PrometheusRule.pm-prometheus-operator-kube-prometheus-node-recording.rules
91. PrometheusRule.pm-prometheus-operator-kube-state-metrics
92. PrometheusRule.pm-prometheus-operator-kubelet.rules
93. PrometheusRule.pm-prometheus-operator-kubernetes-apps
94. PrometheusRule.pm-prometheus-operator-kubernetes-resources
95. PrometheusRule.pm-prometheus-operator-kubernetes-storage
96. PrometheusRule.pm-prometheus-operator-kubernetes-system-apiserver
97. PrometheusRule.pm-prometheus-operator-kubernetes-system-kubelet
98. PrometheusRule.pm-prometheus-operator-kubernetes-system
99. PrometheusRule.pm-prometheus-operator-node-exporter.rules
100. PrometheusRule.pm-prometheus-operator-node-exporter
101. PrometheusRule.pm-prometheus-operator-node-network
102. PrometheusRule.pm-prometheus-operator-node.rules
103. PrometheusRule.pm-prometheus-operator-prometheus-operator
104. PrometheusRule.pm-prometheus-operator-prometheus
105. ServiceMonitor.pm-prometheus-operator-alertmanager
106. ServiceMonitor.pm-prometheus-operator-coredns
107. ServiceMonitor.pm-prometheus-operator-apiserver
108. ServiceMonitor.pm-prometheus-operator-kube-state-metrics
109. ServiceMonitor.pm-prometheus-operator-kubelet
110. ServiceMonitor.pm-prometheus-operator-node-exporter
111. ServiceMonitor.pm-prometheus-operator-grafana
112. ServiceMonitor.pm-prometheus-operator-operator
113. ServiceMonitor.pm-prometheus-operator-prometheus
114. ValidatingWebhookConfiguration.pm-prometheus-operator-admission
115. PodSecurityPolicy.pm-prometheus-operator-admission
116. ServiceAccount.pm-prometheus-operator-admission
117. ClusterRole.pm-prometheus-operator-admission
118. ClusterRoleBinding.pm-prometheus-operator-admission
119. Role.pm-prometheus-operator-admission
120. RoleBinding.pm-prometheus-operator-admission
121. Pod.pm-grafana-test
122. Job.pm-prometheus-operator-admission-create
123. Job.pm-prometheus-operator-admission-patch

As you can see, there were no duplicates included in this list - nor did my logging code for finding duplicates catch any.

### Affected product version(s)

2.7.1

### Reproducing the issue
The code I included above will reproduce it. 

### Suggestions for a fix
I've tried looking at other similar issues in this repo, such as https://github.com/pulumi/pulumi-kubernetes/issues/1023 - it's not clear to me what the issue is here but I suspect it has something to do with the `prometheus-operator` chart pulling in other charts that all create the same custom resources under the covers. If my transform could also apply to those [dependent charts](https://github.com/helm/charts/blob/master/stable/prometheus-operator/requirements.yaml) that would be wonderful.

Or is my issue something else?

**Comment by hausdorff** [comment] 2020-07-29 21:47
This error usually means you have two resources with the same type, namespace and name. Almost always this is a bug in the Helm chart. In particular, it looks like you're creating the monitoring/pm-prometheus-operator-alertmanager CRD twice.

Alex

Theory is the first term in the Taylor series of practice. -- Thomas M Cover (1992)

**Comment by Aaronontheweb** [comment] 2020-07-29 22:25
@hausdorff I figured it was an issue with the chart - specifically, an issue with the chart and one or more of its dependencies both attempting to create the same dependent resource type. Is there a way I can improve my code to work around this problem?

**Comment by hausdorff** [comment] 2020-07-30 00:02
As a hack you could use the transforms API in the `ChartOpts` to find one of those CRD definitions and replace it with an empty `v1.List`. Or `undefined` may work—I forget.

There's probably a flag somewhere that's causing it to get double-generated though.

Alex

Theory is the first term in the Taylor series of practice. -- Thomas M Cover (1992)

**Comment by kmr0877** [comment] 2020-07-30 00:28
I have come across similar issue when trying to install KNative serving from [KNative docs](https://knative.dev/docs/install/any-kubernetes-cluster/) specifically when installing CRD definitions and core components

**Comment by hausdorff** [comment] 2020-07-30 01:50
Yes. This is extremely common. Most Charts have lots of bugs exactly like this.

Alex

Theory is the first term in the Taylor series of practice. -- Thomas M Cover (1992)

**Comment by Aaronontheweb** [comment] 2020-07-31 15:31
> Yes. This is extremely common. Most Charts have lots of bugs exactly like this.

If that's the case then it severely limits Pulumi's usefulness if we can't install most Helm charts.

**Comment by lukehoban** [comment] 2020-07-31 17:53
> > Yes. This is extremely common. Most Charts have lots of bugs exactly like this.

> If that's the case then it severely limits Pulumi's usefulness if we can't install most Helm charts.

FWIW - I do not consider this "a bug in the charts" exactly.  Since the charts do work correctly via the Helm CLI, it is a bug in Pulumi's support for deploying Helm charts that we do not handle this smoothly as well - even if it is "poor design on behalf of the chart author".

We should definitely look into what we can do to fix/improve Pulumi's support for charts like these (especially as the majority of the most used charts have this sort of "issue").

**Comment by jaxxstorm** [comment] 2020-07-31 17:58
@lblackstone and I are having a discussion on how best to support this. It seems this was introduced by #1102 and we do need to figure out a way to either 
A) let the user opt-out of installing the CRDs, because they might be installed out of band by another process
B) detect if the crd is in the api and omit them if automatically.

The workaround at the moment is to use a transformation to drop the resource, something a bit like this:

```
transformations: [
          (obj: any, opts: pulumi.CustomResourceOptions) => {
            if (obj.kind === "CustomResourceDefinition" && (obj.metadata.name === "postgresqls.acid.zalan.do" || obj.metadata.name === "operatorconfigurations.acid.zalan.do")) {
              obj.apiVersion = "v1"
                obj.kind = "List"
            }
          },
        ],
```

**Comment by lblackstone** [comment] 2020-07-31 18:01
> The workaround at the moment is to use a transformation to drop the resource

This is documented for each SDK here:

https://www.pulumi.com/docs/reference/pkg/kubernetes/helm/v3/chart/#chart-with-transformations

**Comment by Aaronontheweb** [comment] 2020-08-11 16:27
So adding this transformation to my Helm chart did not work around the problem:

```csharp
static ImmutableDictionary<string, object> OmitCustomResource(ImmutableDictionary<string, object> obj, CustomResourceOptions opts)
            {
                var metadata = (ImmutableDictionary<string, object>)obj["metadata"];
                var resourceName = $"{obj["kind"]}.{metadata["name"]}";

                if (string.Equals(obj["kind"], "CustomResourceDefinition"))
                {
                    return new Dictionary<string, object>
                    {
                        ["apiVersion"] = "v1",
                        ["kind"] = "List",
                        ["items"] = new Dictionary<string, object>(),
                    }.ToImmutableDictionary();
                }
                return obj;
            }
```

Any other ideas for how I can work around this?

**Comment by ekeij** [comment] 2020-08-12 13:35
It looks like line 132-135 of ChartBase.cs is forcing the inclusion of crds with the `--include-crds` flag. https://github.com/pulumi/pulumi-kubernetes/blob/9069b3a1c780df9e6ac0d7ef6b6fe46a23acef72/sdk/dotnet/Helm/ChartBase.cs#L134

Shouldn't this become an option so the user can decide to either use the `--include-crds` or `--skip-crds` flag?

**Comment by lukehoban** [comment] 2020-08-12 14:03
> Shouldn't this become an option so the user can decide to either use the --include-crds or --skip-crds flag?

Yes - I believe @jaxxstorm is working on a plan for how best to expose this option.

**Comment by jaxxstorm** [comment] 2020-08-12 17:50
The short term fix is to provide the option in the helm options to not install CRDs, similar to the helm flag. It was my mistake to assume this would always be needed.

In the long term, I think @lblackstone is considering some ideas to make this more seamless to users. Considering this is becoming a pressing issue, I'm going to author the short term fix for this and get this out ASAP

**Comment by Freakazoid182** [comment] 2020-08-13 12:45
The problem here isn't with the Kubernetes `CustomResourceDefinition`, but with the URN generation of Pulumi.

Specifically in @Aaronontheweb case, there is an `AlertManager` generated by the helm chart called `monitoring/pm-prometheus-operator-alertmanager`. But there's also a `ServiceMonitor` called `monitoring/pm-prometheus-operator-alertmanager`. 

Because these are not standard Kubernetes resource kinds, Pulumi generates a URN for a `CustomResourceDefinition` type (is this the fallback type for unknown resource kinds?).  The result is 2 resources with URN
```
urn:pulumi:dev::sdkbin-resources::kubernetes:helm.sh/v2:Chart$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::monitoring/pm-prometheus-operator-alertmanager'
```

Kubernetes has no issue with resources named the same, as long as they are not of the same `Kind`. From the helm chart perspective there is no issue. I would consider it a bug/missing feature in Pulumi. It would be nice if Pulumi just takes the Kubernetes resource Kind in the URN, also for unknown kinds.

I worked around it by applying this transform

```csharp

Transformations = {
    (obj, opt) =>
    {
         // Transform the name with suffix to prevent URN collisions
         obj = AddNameSuffixForKind(
         kind: "ServiceMonitor",
         suffix: "service-monitor",
         obj,
         opt);

         // Transform the name with suffix to prevent URN collisions
         obj = AddNameSuffixForKind(
         kind: "AlertManager",
         suffix: "alert-manager",
         obj,
         opt);
    }
...
static ImmutableDictionary<string, object> AddNameSuffixForKind(
            string kind,
            string suffix,
            ImmutableDictionary<string, object> obj,
            CustomResourceOptions opts)
        {
            if ((string)obj["kind"] == kind)
            {
                var metaData = (ImmutableDictionary<string, object>)obj["metadata"];
                var name = metaData["name"];
                metaData = metaData.SetItem("name", $"{name}-{suffix}");
                obj = obj.SetItem("metadata", metaData);

                return obj;
            }

            return obj;
        }
```

**Comment by Place1** [comment] 2020-09-01 04:53
I've got this problem with cert-manager's CRDs. I'm deploying multiple clusters in my pulumi stack and cert-manager to each cluster.

Pulumi throws a duplicate URN error because the helm chart uses a hardcoded name for it's CRD "certificaterequests.cert-manager.io".

Unfortunately I can't work around this issue by using "resourcePrefix" because then my resource names start to exceed 53 characters (also it makes the naming very silly with a double {name}-{name} prefix).

I also can't work around this problem by using a resource transformation to rename the CRD because the CRD name `must be spec.names.plural+"."+spec.group` as enforced by the k8s api.

I think pulumi needs to do something to better handle URN generation for helm charts.

Perhaps an `urnPrefix` would work?

**Comment by lblackstone** [comment] 2020-09-02 14:28
I'm currently working on https://github.com/pulumi/pulumi-kubernetes/issues/920, and then I'll see if I can rework the URNs to fix this problem (with aliases so that they remain compatible).

**Comment by vyrwu** [comment] 2020-12-14 14:21
> @lblackstone and I are having a discussion on how best to support this. It seems this was introduced by #1102 and we do need to figure out a way to either
> A) let the user opt-out of installing the CRDs, because they might be installed out of band by another process
> B) detect if the crd is in the api and omit them if automatically.
> 
> The workaround at the moment is to use a transformation to drop the resource, something a bit like this:
> 
> ```
> transformations: [
>           (obj: any, opts: pulumi.CustomResourceOptions) => {
>             if (obj.kind === "CustomResourceDefinition" && (obj.metadata.name === "postgresqls.acid.zalan.do" || obj.metadata.name === "operatorconfigurations.acid.zalan.do")) {
>               obj.apiVersion = "v1"
>                 obj.kind = "List"
>             }
>           },
>         ],
> ```

Would be nice to at least have the flag `--skip-crds` exposed on the _v3.Chart_ object, for now this workaround works for us. 👍

**Comment by lukehoban** [comment] 2021-05-02 06:43
If I understand correctly - there are at least two issues being tracked here:
1. URNs for customer resources can frequently conflict as noted in https://github.com/pulumi/pulumi-kubernetes/issues/1225#issuecomment-684237439 and https://github.com/pulumi/pulumi-kubernetes/issues/1225#issuecomment-673455979.  
2. Issues around whether CRDs are skipped or not in Helm charts - and specifically the desire to offer users control over it - which is tracked in https://github.com/pulumi/pulumi-kubernetes/issues/1195.

I'll assume this issue is tracking (1) - improving URNs and/or offering more configurability for URNs via `urnPrefix` or similar.  This has some relationship to https://github.com/pulumi/pulumi-kubernetes/issues/1472 which also proposes changes to URNs - though is a separate issue.

**Comment by lblackstone** [comment] 2021-05-03 16:06
@lukehoban Correct

**Comment by almson** [comment] 2021-05-26 10:23
Has this been fixed? I see the correct resource type in URNs, even if the resource is custom. In any case, I have no problem installing prometheus from https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack

**Comment by lblackstone** [comment] 2021-05-26 16:12
#1195 is done, so it's possible to skip the CRD creation now. The other URN issue (#1225) is still open.

**Comment by almson** [comment] 2021-05-26 18:28
@lblackstone The above-referenced comment says 

> Because these are not standard Kubernetes resource kinds, Pulumi generates a URN for a CustomResourceDefinition type (is this the fallback type for unknown resource kinds?). The result is 2 resources with URN
> `pulumi:dev::sdkbin-resources::kubernetes:helm.sh/v2:Chart$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::monitoring/pm-prometheus-operator-alertmanager`

I see that this is not necessarily true. The Helm chart [that I use](https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack) creates resources with urns

    urn:pulumi:dev::swkube::sw:KubernetesMonitoring$kubernetes:core/v1:Namespace$kubernetes:helm.sh/v2:Chart$kubernetes:monitoring.coreos.com/v1:ServiceMonitor::monitoring/prometheus-operator-kube-state-metrics
    urn:pulumi:dev::swkube::sw:KubernetesMonitoring$kubernetes:core/v1:Namespace$kubernetes:helm.sh/v3:Chart$kubernetes:monitoring.coreos.com/v1:PrometheusRule::monitoring/prometheus-operator-kube-state-metrics

As you can see, the URNs use the correct custom resource types (they don't have `CustomResourceDefinition` in their URNs) and don't conflict. So, the problem seems more nuanced than just "urns don't include custom resources."

**Comment by almson** [comment] 2021-05-26 18:30
@Place1 You can prefix the URN by declaring `CustomResource` classes of different types. See https://github.com/pulumi/pulumi-kubernetes/issues/1472#issuecomment-849017562 This should fix your issue of declaring multiple clusters.

**Comment by gitfool** [comment] 2021-07-02 18:28
@lblackstone I'm also trying to install [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) and seem to hitting this issue, so I'm confused that @almson says it works for him. Using Pulumi 3.6.0 and Pulumi.Kubernetes 3.5.0. Note that I'm installing the crds separately and skipping crds when installing the helm chart. Currently working through using transformations using the following dotnet/c#:
```c#
// kube prometheus stack; https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
Logger.LogDebug("Installing kube prometheus stack");
var kubePrometheusStackCrds = new ConfigGroup("kube-prometheus-stack-crds",
    new ConfigGroupArgs { Yaml = ReadResource("KubePrometheusStackCrds.yaml") },
    new ComponentResourceOptions { /*Protect = true,*/ Provider = k8sProvider });

var monitoringNs = new Namespace("monitoring",
    new NamespaceArgs { Metadata = new ObjectMetaArgs { Name = "monitoring" } },
    new CustomResourceOptions { Provider = k8sProvider });

var kubePrometheusStackValues =
    new Dictionary<string, object>
    {
        ["alertmanager"] = new
        {
            alertmanagerSpec = new
            {
                nodeSelector = new { role = "monitoring" },
                tolerations = new[] { new { key = "role", @operator = "Exists" } }
            },
            ingress = new { enabled = false }
        },
        ["grafana"] = new
        {
            ingress = new { enabled = false },
            nodeSelector = new { role = "monitoring" },
            tolerations = new[] { new { key = "role", @operator = "Exists" } }
        },
        ["kubeControllerManager"] = new { enabled = false },
        ["kubeEtcd"] = new { enabled = false },
        ["kubeScheduler"] = new { enabled = false },
        ["kube-state-metrics"] = new
        {
            nodeSelector = new { role = "monitoring" },
            tolerations = new[] { new { key = "role", @operator = "Exists" } }
        },
        ["prometheus"] = new
        {
            ingress = new { enabled = false },
            prometheusSpec = new
            {
                podMonitorSelectorNilUsesHelmValues = false,
                serviceMonitorSelectorNilUsesHelmValues = false,
                nodeSelector = new { role = "monitoring" },
                tolerations = new[] { new { key = "role", @operator = "Exists" } }
            }
        },
        ["prometheus-node-exporter"] = new { tolerations = new[] { new { key = "role", @operator = "Exists" } } },
        ["prometheusOperator"] = new
        {
            admissionWebhooks = new
            {
                certManager = new { enabled = true },
                patch = new
                {
                    nodeSelector = new { role = "monitoring" },
                    tolerations = new[] { new { key = "role", @operator = "Exists" } }
                }
            },
            nodeSelector = new { role = "monitoring" },
            tolerations = new[] { new { key = "role", @operator = "Exists" } }
        }
    };

new Chart("kube-prometheus-stack",
    new ChartArgs
    {
        Namespace = monitoringNs.Metadata.Apply(metadata => metadata.Name),
        FetchOptions = new ChartFetchArgs { Repo = "https://prometheus-community.github.io/helm-charts" },
        Chart = "kube-prometheus-stack",
        Version = K8sConfig.KubePrometheusStackChartVersion,
        Values = kubePrometheusStackValues,
        SkipCRDRendering = true,
        Transformations =
        {
            (obj, _) => obj.DefaultNamespace("monitoring"),
            (obj, _) => obj.ExcludeName("kube-prometheus-stack-grafana-test")
        }
    },
    new ComponentResourceOptions { DependsOn = { kubePrometheusStackCrds, certManagerCrds }, Provider = k8sProvider });
```
Results in errors like the following (only one of them depending on the race of which resource is created first):
```
Diagnostics:
  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition (monitoring/kube-prometheus-stack-alertmanager):
    error: Duplicate resource URN 'urn:pulumi:alpha::k8s::kubernetes:helm.sh/v3:Chart$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::monitoring/kube-prometheus-stack-alertmanager'; try giving it a unique name

  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition (monitoring/kube-prometheus-stack-prometheus):
    error: Duplicate resource URN 'urn:pulumi:alpha::k8s::kubernetes:helm.sh/v3:Chart$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::monitoring/kube-prometheus-stack-prometheus'; try giving it a unique name
```

**Comment by almson** [comment] 2021-07-02 20:39
@lblackstone
Well, what happens when you install the CRDs together?

**Comment by gitfool** [comment] 2021-07-02 20:54
@almson No difference (same errors), which makes sense as it's not installing the crds but using the crds that causes the issue.

**Comment by almson** [comment] 2021-07-03 07:18
Well, I stand by my observation that it works under some combination of circumstances. The usual way I go about solving problems like this in general is to just run under a debugger and step into the library code. However the Pulumi architects, in their infinite wisdom, decided that that's not a target usecase.

**Comment by gitfool** [comment] 2021-07-06 02:32
I finally got the helm chart to install using the following:
```c#
// kube prometheus stack; https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
Logger.LogDebug("Installing kube prometheus stack");
var kubePrometheusStackCrds = new ConfigGroup("kube-prometheus-stack-crds",
    new ConfigGroupArgs { Yaml = ReadResource("KubePrometheusStackCrds.yaml") },
    new ComponentResourceOptions { /*Protect = true,*/ Provider = k8sProvider });

var monitoringNs = new Namespace("monitoring",
    new NamespaceArgs { Metadata = new ObjectMetaArgs { Name = "monitoring" } },
    new CustomResourceOptions { Provider = k8sProvider });

var kubePrometheusStackValues =
    new Dictionary<string, object>
    {
        ["nameOverride"] = "kps",
        ["fullnameOverride"] = "kps",
        ["alertmanager"] = new
        {
            alertmanagerSpec = new
            {
                nodeSelector = new { role = "monitoring" },
                tolerations = new[] { new { key = "role", @operator = "Exists" } }
            },
            ingress = new { enabled = false }
        },
        ["grafana"] = new
        {
            nameOverride = "kps-grafana",
            fullnameOverride = "kps-grafana",
            ingress = new { enabled = false },
            nodeSelector = new { role = "monitoring" },
            tolerations = new[] { new { key = "role", @operator = "Exists" } }
        },
        ["kubeControllerManager"] = new { enabled = false },
        ["kubeEtcd"] = new { enabled = false },
        ["kubeScheduler"] = new { enabled = false },
        ["kube-state-metrics"] = new
        {
            nameOverride = "kps-kube-state-metrics",
            fullnameOverride = "kps-kube-state-metrics",
            nodeSelector = new { role = "monitoring" },
            tolerations = new[] { new { key = "role", @operator = "Exists" } }
        },
        ["prometheus"] = new
        {
            ingress = new { enabled = false },
            prometheusSpec = new
            {
                podMonitorSelectorNilUsesHelmValues = false,
                serviceMonitorSelectorNilUsesHelmValues = false,
                nodeSelector = new { role = "monitoring" },
                tolerations = new[] { new { key = "role", @operator = "Exists" } }
            }
        },
        ["prometheus-node-exporter"] = new
        {
            nameOverride = "kps-prometheus-node-exporter",
            fullnameOverride = "kps-prometheus-node-exporter",
            tolerations = new[] { new { key = "role", @operator = "Exists" } }
        },
        ["prometheusOperator"] = new
        {
            admissionWebhooks = new
            {
                certManager = new { enabled = true },
                patch = new
                {
                    nodeSelector = new { role = "monitoring" },
                    tolerations = new[] { new { key = "role", @operator = "Exists" } }
                }
            },
            nodeSelector = new { role = "monitoring" },
            tolerations = new[] { new { key = "role", @operator = "Exists" } }
        }
    };

new Chart("kube-prometheus-stack",
    new ChartArgs
    {
        Namespace = monitoringNs.Metadata.Apply(metadata => metadata.Name),
        FetchOptions = new ChartFetchArgs { Repo = "https://prometheus-community.github.io/helm-charts" },
        Chart = "kube-prometheus-stack",
        Version = K8sConfig.KubePrometheusStackChartVersion,
        Values = kubePrometheusStackValues,
        SkipCRDRendering = true,
        Transformations =
        {
            (obj, _) => obj.MutateWhenKind("PodSecurityPolicy", mutable => mutable.OmitNamespace()),
            (obj, _) => obj.MutateWhenKind("AlertManager", mutable => mutable.SetName(name => $"{name}-am")),
            (obj, _) => obj.MutateWhenKind("PrometheusRule", mutable => mutable.SetName(name => $"{name}-pr")),
            (obj, _) => obj.MutateWhenKind("ServiceMonitor", mutable => mutable.SetName(name => $"{name}-sm")),
            (obj, _) => obj.MutateWhenName("kps-grafana-test", mutable => mutable.Exclude())
        }
    },
    new ComponentResourceOptions { DependsOn = { kubePrometheusStackCrds, certManagerCrds }, Provider = k8sProvider });
```
I needed to transform the various crd names to force pulumi to use a unique urn. You have to be careful to not transform the `Prometheus` crd name, otherwise the resulting service will not have the correct labels and so not match its pods.

@lblackstone please fix this so that the urn uses the actual crd name.

**Comment by viveklak** [comment] 2021-09-14 23:28
An option is to consider the new Helm Release resource here. See https://www.pulumi.com/blog/full-access-to-helm-features-through-new-helm-release-resource-for-kubernetes/ for details. You should be able to create multiple releases without an issue.

**Comment by gitfool** [comment] 2021-10-07 04:23
I can confirm that release [v3.8.0](https://github.com/pulumi/pulumi-kubernetes/releases/tag/v3.8.0) with #1741 fixes this issue for me.

Specifically, I can remove the crd name transformation hacks I mention above and it works as expected! 🎉

**Closed** 2023-07-14 18:04 UTC
Labels: kind/enhancement, area/helm, resolution/fixed
