### ISSUE TITLE
When creating k8s resources with a custom provider, one must supply the provider for every new object

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-kubernetes#439] opened 2019-02-20 06:34 UTC
A user has to repeatedly declare the k8s cluster provider when creating many k8s resources. See for [more info](https://github.com/pulumi/pulumi-kubernetes/blob/master/tests/integration/istio/step1/istio.ts#L9-L29): the line `{ provider: k8sProvider }` is set twice by the user in the `namespace`, and `adminBinding` objects.

It'd be great if there was a method of setting the k8s cluster provider once for use with *many* objects, in some bounded context, to avoid having to set this every time we declare a new k8s resource instance.

**Comment by 4c74356b41** [comment] 2019-03-14 08:55
extremely annoying

**Comment by lukehoban** [comment] 2019-03-14 14:00
I believe this is a dupe of https://github.com/pulumi/pulumi/issues/2059.

**Comment by 4c74356b41** [comment] 2019-03-14 14:03
yep, looks similar

**Comment by hausdorff** [comment] 2019-03-14 18:26
Let's close as a dupe.

**Closed by hausdorff** 2019-03-14 18:26 UTC
Labels: resolution/duplicate
