### ISSUE TITLE
Outputs not working

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi-kubernetes#137] opened 2018-08-15 01:39 UTC
Output properties on k8s resources are not being populated. This is because the values of these properties do not live at the root level in the resource's state object; instead, they are nested under "live".

A simple fix here is to move the live state that contains the values of the output properties to the root level of the resource's state object (i.e. instead of storing `{ inputs: {}, live: {} }` in the checkpoint file, store `{ ...live, "__inputs": {} }`).

**Comment by pgavlin** [comment] 2018-08-15 01:48
Another candidate fix is to update the `pulumi.CustomResource` type to accept a function in its constructor that is called by the runtime to find the resource's output properties in its state. This has the advantage of making outputs work with existing state files. The approach proposed above would only fix outputs for resources created or updated after the fix.

Another approach that would light up outputs for existing state files is to change the engine and provider interface s.t. each provider has a chance to migrate the state of its existing resources to a new format even if the resource has not changed.

**Comment by pgavlin** [comment] 2018-08-15 01:49
A simple implementation of the originally-proposed fix is here: https://github.com/pulumi/pulumi-kubernetes/compare/pgavlin/fixOutputs

**Comment by pgavlin** [comment] 2018-08-15 01:49
cc @hausdorff @lukehoban @swgillespie

**Comment by joeduffy** [comment] 2018-08-15 02:35
@pgavlin I noticed this doesn't have a milestone, and isn't assigned to anyone. Did you mean to put it in M17? It would seem this is a serious issue we want to fix for 15.1.

If that was your intent, can you tag the work item accordingly? (Good habit to get into for all new work items.)

**Comment by hausdorff** [comment] 2018-08-15 03:04
This is actually a duplicate of #134, but since discussion has moved here let's close that ticket and re-tag this one accordingly.

**Comment by hausdorff** [comment] 2018-08-15 03:17
This is critical to fix for v0.15.1. The big question for me is whether the "right way" to fix this is too expensive or risky to fit into v0.15.1.

I think Pat and I agree that "correct" solution is to change the protocol so that functions consuming the state object get a copy of the old inputs. The "packed" state struct with `live` and `inputs` was always a hack to accommodate Kubernetes' need for the strategic merge, and it would be nice to just get rid of the hack altogether.

Changing the protocol is a less invasive change than it might seem, because the information is purely advisory and the only provider it affects is the Kubernetes provider. And between Pat and I, I think it should not take too much time.

But, if it's not realistic to change the protocol for v0.15.1, then the least invasive and most expedient thing to do is to apply the `{ ...live, "__inputs": {} }` semantics. It requires only changes to the Kubernetes provider and leaves the door open for the protocol fix later.

I personally do not see the utility of `Migrate` outside of this very specific scenario, and I'm reticent to add this to the protocol for this one use case, especially if we're planning on fixing this "for real" in M17.

**Closed** 2018-08-15 21:55 UTC
Labels: kubernetes/inner-dev-loop
