### ISSUE TITLE
Support build/push of docker builds from local folders

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-kubernetes#95] opened 2018-07-18 14:14 UTC
In the `cloud.Service` package, we have the ability to specify `build:` instead of `image:`, resulting in a `docker build` and `docker push` to a private registry that is used for the service.

We should support the same for Kubernetes.  

A key question is what registry to push to - and this likely needs to be pluggable. (local for local minikube/docker-for-desktop, cloud-hosted for GKE/AKS/EKS, potentially a self-hosted registry in the kube cluster, etc.)

It may be possible to support this with just a standalone API like `imageFromLocalPath("./app", { parent: this} )` which internally allocates the registry and manages the build/push lifecycle, but returns just the image name to embed in existing `image:` blocks.

**Comment by hausdorff** [comment] 2018-09-04 19:07
Closing as duplicate of https://github.com/pulumi/pulumi-docker/issues/2

**Closed by hausdorff** 2018-09-04 19:07 UTC
Labels: resolution/duplicate
