### ISSUE TITLE
Allow helm charts to disable autonaming

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-kubernetes#1644] opened 2021-07-01 10:18 UTC
Many Pulumi users do not want to use autonaming on their resources for a variety of good reasons. Our current helm implementation only allows this if the chart has a `fullNameOverride` value.

We don't expose a `name` property like we do with many other resources, which makes this exceptionally difficult. You can sort of work around it with transformations, but it's not very user friendly.

We should implement a `name` property for all resources in the Component to allow users to have flexibility over their naming

**Comment by headconnect** [comment] 2021-07-01 13:20
The current behavior is that helm charts take their name from the pulumi name - which is usually more verbose than the desired result.  This can lead to more complex deployments over time - for instance where helm charts are deployed to multiple clusters (requiring unique pulumi names so as to avoid URN conflicts) - and ingresses are deployed separately (which would require special logic to ensure the selectors go to the specific instance).  Essentially, instead of having two clusters with "prometheus", you get two clusters with "cluster1-prometheus" and "cluster2-prometheus" even though it's fairly apparent which cluster is which. 

Decoupling the chart name from the pulumi name would be highly beneficial (though please ensure the pulumi name is what's reflected in the stack URNs once the chart is expanded)

**Comment by pierlucg-xs** [comment] 2021-07-28 13:44
> You can sort of work around it with transformations, but it's not very user friendly.

Any chance you can give an example of this? I'd be happy if my nginx ingress controller was not named `nginx-ingress-ingress-nginx-controller` (which is made worse by the fact that my applications need to refer to it as http://nginx-ingress-ingress-nginx-controller.nginx since it is in the nginx namespace)

**Comment by lustefaniak** [comment] 2022-01-11 00:13
I'm not sure if my problem is related to this one, but it is very similar and might be caused by an invalid `name` passed to Helm. I'm trying to install `bitnami/kafka` using code like this:

```go
		_, err = helmv2.NewChart(ctx, "bitnami/kafka", helmv2.ChartArgs{
			Chart:     pulumi.String("kafka"),
			Namespace: pulumi.String(kafkaNamespace),
			FetchArgs: helmv2.FetchArgs{
				Repo: pulumi.String("https://charts.bitnami.com/bitnami/"),
			},
			Values: pulumi.Map{
				"nameOverride":     pulumi.String("kafka"), // doesn't help
				"fullnameOverride": pulumi.String("kafka"), // doesn't help
				"replicaCount":     pulumi.Int(kafkaReplicas),
				"externalAccess":   externalAccessValues,
			},
		})
```

What I see is that Pulumi tries to create
```
     └─ kubernetes:helm.sh/v2:Chart           bitnami/kafka                                      
 +      ├─ kubernetes:core/v1:ServiceAccount  kafka/kafka                             create     
 +      ├─ kubernetes:core/v1:Service         kafka/kafka                             create     
 +      ├─ kubernetes:core/v1:Service         kafka/kafka-0-external                  create     
 +      ├─ kubernetes:core/v1:ConfigMap       kafka/kafka-scripts                     create     
 +      ├─ kubernetes:core/v1:Service         kafka/bitnami/kafka-zookeeper           create     
 +      ├─ kubernetes:core/v1:Service         kafka/kafka-headless                    create     
 +      ├─ kubernetes:core/v1:Service         kafka/bitnami/kafka-zookeeper-headless  create     
 +      ├─ kubernetes:apps/v1:StatefulSet     kafka/bitnami/kafka-zookeeper           create     
 +      └─ kubernetes:apps/v1:StatefulSet     kafka/kafka                             create 
```

Which later fails creation due to `/` being used in `name` attributes:

```
error: resource kafka/bitnami/kafka-zookeeper-headless was not successfully created by the Kubernetes API server : Service "bitnami/kafka-zookeeper-headless" is invalid: [metadata.name: Invalid value: "bitnami/kafka-zookeeper-headless": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?'), metadata.labels: Invalid value: "bitnami/kafka": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'), spec.selector: Invalid value: "bitnami/kafka": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]
```

What also surprises me is somehow inconsistent naming; sometimes `/bitnami/` is present and sometimes not. That inconsistency indicates there might be an actual problem with the Chart itself not taking into account `nameOverride` or `fullnameOverride` always as it should.

Are there any workarounds to make it work? I see there are `ChartArgs.Transformations` available, but that looks like an overkill 🤔

**Comment by lustefaniak** [comment] 2022-01-11 00:17
Ok, those that still have `kafka/bitnami/kafka-zookeeper` are from the dependent Chart. Probably I could work around this by excluding such dependency and installing the Zookeper chart separately. On the other hand, is it correct that such a name `kafka/bitnami` is passed to Helm?

**Comment by EronWright** [comment] 2024-04-01 17:56
I believe the ask here is to support `--release-name` parameter on `helm template`, which defaults to the `Chart` component name.

**Comment by EronWright** [comment] 2024-04-19 23:50
Note this limitation on values for `--release-name`:
> “invalid release name, must match regex ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ and the length must not be longer than 53”

**Comment by EronWright** [comment] 2024-05-14 00:19
This is fixed in Chart v4 since it provides a `name` input to set the release name.  I would still recommend that people set the `fullNameOverride` in preference to this.

**Closed by EronWright** 2024-05-14 00:19 UTC
Labels: kind/enhancement, area/helm, resolution/fixed, mro2
