### ISSUE TITLE
Refresh not working as expected on some resources

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-kubernetes#1525] opened 2021-04-13 17:34 UTC
If you create a namespace (as an example) and then manually modify the namespace, you'd expect a refresh to reflect the changes. Currently it does not.

To repo, create a namespace:

```
let name = "foo"

let appLabels = {
  "app.kubernetes.io/instance": name,
  "app.kubernetes.io/application": "productionapp"
}

this.namespace = new k8s.core.v1.Namespace(name, {
  metadata: {
    name: name,
     labels: appLabels
   }
 })
```

Modify that namespace and add a new label, then run `pulumi up --refresh`

## Expected behavior
We'd expect Pulumi to reflect the difference and tell the user it was going to remove the added label

## Current behavior
Currently, Pulumi reports the diff in the detailed diff, but not in the default view

**Comment by lblackstone** [comment] 2021-04-30 21:07
After digging through the diff code, this appears to be expected behavior for the current client-side diff implementation. The refresh part of the operation does modify the state, but the update portion does not make additional changes, as reflected in the default view.

The difference in behavior between the default and detailed diff is because of this Diff result: https://github.com/pulumi/pulumi-kubernetes/blob/6731fdd6e15e282f406c394a9ccba5568cff4dfe/provider/pkg/provider/provider.go#L1386

Since the input values from the Pulumi program haven't changed (no diff), this value is set to `DIFF_NONE`: https://github.com/pulumi/pulumi-kubernetes/blob/6731fdd6e15e282f406c394a9ccba5568cff4dfe/provider/pkg/provider/provider.go#L1340

---

> We'd expect Pulumi to reflect the difference and tell the user it was going to remove the added label

In my testing, Pulumi doesn't modify data changed out of band (e.g., by kubectl). If you add a label with `kubectl edit`, Pulumi will update the state on refresh, but not remove that label because it's not part of the resource under management by Pulumi.

More concretely, here's what the resource state looks like after these steps:

1. Create Namespace with Pulumi
2. Add a new label with `kubectl edit`
3. `pulumi up --refresh`

```diff
~ pulumi:pulumi:Stack: (refresh)
    [urn=urn:pulumi:dev::pulumi-k8s-test::pulumi:pulumi:Stack::pulumi-k8s-test-dev]
    ~ pulumi:providers:kubernetes: (refresh)
        [id=24c4fb96-6edc-4e56-9427-d753e6cf27de]
        [urn=urn:pulumi:dev::pulumi-k8s-test::pulumi:providers:kubernetes::k8s]
    ~ kubernetes:core/v1:Namespace: (refresh)
        [id=foo]
        [urn=urn:pulumi:dev::pulumi-k8s-test::kubernetes:core/v1:Namespace::foo]
        [provider=urn:pulumi:dev::pulumi-k8s-test::pulumi:providers:kubernetes::k8s::24c4fb96-6edc-4e56-9427-d753e6cf27de]
        --outputs:--
      ~ metadata  : {
          ~ annotations      : {
              + bar                                             : "bar"
                foo                                             : "bar"
                kubectl.kubernetes.io/last-applied-configuration: "{\"apiVersion\":\"v1\",\"kind\":\"Namespace\",\"metadata\":{\"annotations\":{\"foo\":\"bar\"},\"labels\":{\"app.kubernetes.io/managed-by\":\"pulumi\"},\"name\":\"foo\"}}\n"
            }
            creationTimestamp: "2021-04-30T21:03:48Z"
            labels           : {
                app.kubernetes.io/managed-by: "pulumi"
            }
          ~ managedFields    : [
                [0]: {
                        apiVersion: "v1"
                        fieldsType: "FieldsV1"
                        fieldsV1  : {
                            f:metadata: {
                                f:annotations: {
                                }
                                f:labels     : {
                                }
                            }
                            f:status  : {
                            }
                        }
                        manager   : "pulumi-resource-kubernetes"
                        operation : "Update"
                        time      : "2021-04-30T21:03:48Z"
                    }
              + [1]: {
                      + apiVersion: "v1"
                      + fieldsType: "FieldsV1"
                      + fieldsV1  : {
                          + f:metadata: {
                              + f:annotations: {
                                }
                            }
                        }
                      + manager   : "kubectl-edit"
                      + operation : "Update"
                      + time      : "2021-04-30T21:03:56Z"
                    }
            ]
            name             : "foo"
          ~ resourceVersion  : "154897" => "154915"
            selfLink         : "/api/v1/namespaces/foo"
            uid              : "8fabf424-0638-460d-b71e-a803768d0de3"
        }
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::pulumi-k8s-test::pulumi:pulumi:Stack::pulumi-k8s-test-dev]
```
```yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    bar: bar
    foo: bar
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{"foo":"bar"},"labels":{"app.kubernetes.io/managed-by":"pulumi"},"name":"foo"}}
  creationTimestamp: "2021-04-30T21:03:48Z"
  labels:
    app.kubernetes.io/managed-by: pulumi
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:foo: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/managed-by: {}
      f:status:
        f:phase: {}
    manager: pulumi-resource-kubernetes
    operation: Update
    time: "2021-04-30T21:03:48Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:bar: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-04-30T21:03:56Z"
  name: foo
  resourceVersion: "154915"
  selfLink: /api/v1/namespaces/foo
  uid: 8fabf424-0638-460d-b71e-a803768d0de3
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```

**Comment by lblackstone** [comment] 2021-04-30 21:11
I believe that this is working as intended, so closing this out.

**Closed by lblackstone** 2021-04-30 21:11 UTC
Labels: kind/bug, resolution/invalid
