### ISSUE TITLE
Updates to kubernetes hang for up to 15 minutes

### ISSUE THREAD

**Issue by aeb-sia** [pulumi/pulumi-kubernetes#640] opened 2019-07-15 08:17 UTC
Using a minimal kubernetes deployment:
```
import * as k8s from "@pulumi/kubernetes";

const appLabels = { app: "nginx" };
const deployment = new k8s.apps.v1.Deployment("nginx", {
    metadata: {
        annotations: {
            myVeryOwnAnnotation: 'foo'
        }
    },
    spec: {
        selector: { matchLabels: appLabels },
        replicas: 1,
        template: {
            metadata: { labels: appLabels },
            spec: { containers: [{ name: "nginx", image: "nginx" }] }
        }
    }
});
export const name = deployment.metadata.apply(m => m.name);
```

the deploy is fast. If I update the annotation:
```
import * as k8s from "@pulumi/kubernetes";

const appLabels = { app: "nginx" };
const deployment = new k8s.apps.v1.Deployment("nginx", {
    metadata: {
        annotations: {
            myVeryOwnAnnotation: 'bar'
        }
    },
    spec: {
        selector: { matchLabels: appLabels },
        replicas: 1,
        template: {
            metadata: { labels: appLabels },
            spec: { containers: [{ name: "nginx", image: "nginx" }] }
        }
    }
});
export const name = deployment.metadata.apply(m => m.name);
```
the update hangs for up to 15 minutes. If I update the kubernetes cluster using another way (dashboard for instance) pulumi is notified of the change and "finishes".

I assume this is caused by the watch query being run after issuing the update command. If the update is done very fast, the watch query gets the updated state and does not receive further updates, waiting forever (I consitently get 15 minute timeouts, so there has to be one defined somewhere)

I could not replicate this using minikube, but I get it in our production cluster. Running the latest pulumi version. Tried it out on ubuntu and windows 10

**Comment by pgavlin** [comment] 2019-07-15 21:13
May be related to #611

**Comment by lblackstone** [comment] 2019-07-23 22:36
I wasn't able to reproduce with the provided example. The readiness check isn't dependent on the speed of the update operation, but the behavior you saw could perhaps be caused by a state mismatch for your stack.

Can you try running a `pulumi refresh` on the stack and see if that fixes it? If that doesn't work, a fix to #611 will be pushed out soon, and we can try again after that in case it was related.

**Comment by aeb-sia** [comment] 2019-07-24 06:30
I'm running it in a fresh namespace without any other person/machine interfering.
I can't run pulumi refresh, since the operation itself is still running, I get this (which is probably expected):
```
error: the current deployment has 1 resource(s) with pending operations:
  * urn:pulumi:siatest::simon-pulumi-test::kubernetes:apps/v1:Deployment::nginx, interrupted while updating

These resources are in an unknown state because the Pulumi CLI was interrupted while
waiting for changes to these resources to complete. You should confirm whether or not the
operations listed completed successfully by checking the state of the appropriate provider.
For example, if you are using AWS, you can confirm using the AWS Console.

Once you have confirmed the status of the interrupted operations, you can repair your stack
using 'pulumi stack export' to export your stack to a file. For each operation that succeeded,
remove that operation from the "pending_operations" section of the file. Once this is complete,
use 'pulumi stack import' to import the repaired stack.

refusing to proceed
```

The only way to repair it, is to export/import the stack, run refresh and proceed...

**Comment by lblackstone** [comment] 2019-07-24 14:51
Yeah, that's expected if the CLI is stopped prior to an operation completing, and not necessarily related to the problem you're seeing. If you repair the stack, are you still seeing the update operation hang for 15 mins after that?

**Comment by aeb-sia** [comment] 2019-07-24 14:56
subsequent updates to the annotations always hang.

**Comment by hausdorff** [comment] 2019-07-25 20:39
@aeb-sia are you still seeing this problem? I'm having trouble reproducing it as well.

**Comment by aeb-sia** [comment] 2019-07-26 05:48
Yes. Here is the verbose debug output if that helps:
```
sia@pc-xdlinux0014 ~/dev/kube/pulumi
 % pulumi up --non-interactive -v 10 -d -y
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE to remember): 
Previewing update (siatest):

    pulumi:pulumi:Stack simon-pulumi-test-siatest  debug: Registering resource: t=pulumi:pulumi:Stack, name=simon-pulumi-test-siatest, custom=false
    pulumi:pulumi:Stack simon-pulumi-test-siatest  debug: RegisterResource RPC prepared: t=pulumi:pulumi:Stack, name=simon-pulumi-test-siatest
    pulumi:pulumi:Stack simon-pulumi-test-siatest running debug: RegisterResource RPC prepared: t=pulumi:pulumi:Stack, name=simon-pulumi-test-siatest
    pulumi:pulumi:Stack simon-pulumi-test-siatest running debug: RegisterResource RPC finished: resource:simon-pulumi-test-siatest[pulumi:pulumi:Stack]; err: null, resp: urn:pulumi:siatest::simon-pulumi-test::pulumi:pulumi:Stack::simon-pulumi-test-siatest,,,true,
    pulumi:pulumi:Stack simon-pulumi-test-siatest running debug: Running program '/home/sia/dev/kube/pulumi' in pwd '/home/sia/dev/kube/pulumi' w/ args: 
    pulumi:pulumi:Stack simon-pulumi-test-siatest running debug: Registering resource: t=kubernetes:apps/v1:Deployment, name=nginx, custom=true
    pulumi:pulumi:Stack simon-pulumi-test-siatest running debug: Registering resource: t=kubernetes:core/v1:Service, name=nginx, custom=true
    pulumi:pulumi:Stack simon-pulumi-test-siatest running debug: RegisterResourceOutputs RPC prepared: urn=urn:pulumi:siatest::simon-pulumi-test::pulumi:pulumi:Stack::simon-pulumi-test-siatest
    pulumi:pulumi:Stack simon-pulumi-test-siatest running debug: RegisterResourceOutputs RPC finished: urn=urn:pulumi:siatest::simon-pulumi-test::pulumi:pulumi:Stack::simon-pulumi-test-siatest; err: null, resp: 
    pulumi:pulumi:Stack simon-pulumi-test-siatest running debug: RegisterResource RPC prepared: t=kubernetes:core/v1:Service, name=nginx
    pulumi:pulumi:Stack simon-pulumi-test-siatest running debug: RegisterResource RPC prepared: t=kubernetes:apps/v1:Deployment, name=nginx
    kubernetes:core:Service nginx  
    pulumi:pulumi:Stack simon-pulumi-test-siatest running debug: RegisterResource RPC finished: resource:nginx[kubernetes:core/v1:Service]; err: null, resp: urn:pulumi:siatest::simon-pulumi-test::kubernetes:core/v1:Service::nginx,sia-ns/nginx-service,__inputs,,,,,apiVersion,,,v1,kind,,,Service,metadata,,,,,labels,,,,,app.kubernetes.io/managed-by,,,pulumi,name,,,nginx-service,namespace,,,sia-ns,spec,,,,,ports,,,,,,,,,,name,,,http,port,,80,protocol,,,TCP,targetPort,,8080,selector,,,,,App,,,nginx,type,,,ClusterIP,apiVersion,,,v1,kind,,,Service,metadata,,,,,annotations,,,,,kubectl.kubernetes.io/last-applied-configuration,,,{"apiVersion":"v1","kind":"Service","metadata":{"labels":{"app.kubernetes.io/managed-by":"pulumi"},"name":"nginx-service","namespace":"sia-ns"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":8080}],"selector":{"App":"nginx"},"type":"ClusterIP"}}
 ~  kubernetes:apps:Deployment nginx update [diff: ~metadata]
    pulumi:pulumi:Stack simon-pulumi-test-siatest running debug: RegisterResource RPC finished: resource:nginx[kubernetes:apps/v1:Deployment]; err: null, resp: urn:pulumi:siatest::simon-pulumi-test::kubernetes:apps/v1:Deployment::nginx,sia-ns/nginx-6xdb52z9,,,
    pulumi:pulumi:Stack simon-pulumi-test-siatest  12 debugs
 
Diagnostics:
  pulumi:pulumi:Stack (simon-pulumi-test-siatest):
    debug: Registering resource: t=pulumi:pulumi:Stack, name=simon-pulumi-test-siatest, custom=false
    debug: RegisterResource RPC prepared: t=pulumi:pulumi:Stack, name=simon-pulumi-test-siatest
    debug: RegisterResource RPC finished: resource:simon-pulumi-test-siatest[pulumi:pulumi:Stack]; err: null, resp: urn:pulumi:siatest::simon-pulumi-test::pulumi:pulumi:Stack::simon-pulumi-test-siatest,,,true,
    debug: Running program '/home/sia/dev/kube/pulumi' in pwd '/home/sia/dev/kube/pulumi' w/ args: 
    debug: Registering resource: t=kubernetes:apps/v1:Deployment, name=nginx, custom=true
    debug: Registering resource: t=kubernetes:core/v1:Service, name=nginx, custom=true
    debug: RegisterResourceOutputs RPC prepared: urn=urn:pulumi:siatest::simon-pulumi-test::pulumi:pulumi:Stack::simon-pulumi-test-siatest
    debug: RegisterResourceOutputs RPC finished: urn=urn:pulumi:siatest::simon-pulumi-test::pulumi:pulumi:Stack::simon-pulumi-test-siatest; err: null, resp: 
    debug: RegisterResource RPC prepared: t=kubernetes:core/v1:Service, name=nginx
    debug: RegisterResource RPC prepared: t=kubernetes:apps/v1:Deployment, name=nginx
    debug: RegisterResource RPC finished: resource:nginx[kubernetes:core/v1:Service]; err: null, resp: urn:pulumi:siatest::simon-pulumi-test::kubernetes:core/v1:Service::nginx,sia-ns/nginx-service,__inputs,,,,,apiVersion,,,v1,kind,,,Service,metadata,,,,,labels,,,,,app.kubernetes.io/managed-by,,,pulumi,name,,,nginx-service,namespace,,,sia-ns,spec,,,,,ports,,,,,,,,,,name,,,http,port,,80,protocol,,,TCP,targetPort,,8080,selector,,,,,App,,,nginx,type,,,ClusterIP,apiVersion,,,v1,kind,,,Service,metadata,,,,,annotations,,,,,kubectl.kubernetes.io/last-applied-configuration,,,{"apiVersion":"v1","kind":"Service","metadata":{"labels":{"app.kubernetes.io/managed-by":"pulumi"},"name":"nginx-service","namespace":"sia-ns"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":8080}],"selector":{"App":"nginx"},"type":"ClusterIP"}}
    ,creationTimestamp,,,2019-07-26T05:17:57Z,labels,,,,,app.kubernetes.io/managed-by,,,pulumi,name,,,nginx-service,namespace,,,sia-ns,resourceVersion,,,4590324,selfLink,,,/api/v1/namespaces/sia-ns/services/nginx-service,uid,,,ba7bd3b7-af64-11e9-862e-005056a3fa65,spec,,,,,clusterIP,,,100.75.23.134,ports,,,,,,,,,,name,,,http,port,,80,protocol,,,TCP,targetPort,,8080,selector,,,,,App,,,nginx,sessionAffinity,,,None,type,,,ClusterIP,status,,,,,loadBalancer,,,,,,true,
    debug: RegisterResource RPC finished: resource:nginx[kubernetes:apps/v1:Deployment]; err: null, resp: urn:pulumi:siatest::simon-pulumi-test::kubernetes:apps/v1:Deployment::nginx,sia-ns/nginx-6xdb52z9,,,
 
Resources:
    ~ 1 to update
    2 unchanged

Updating (siatest):

    pulumi:pulumi:Stack simon-pulumi-test-siatest  debug: Registering resource: t=pulumi:pulumi:Stack, name=simon-pulumi-test-siatest, custom=false
    pulumi:pulumi:Stack simon-pulumi-test-siatest  debug: RegisterResource RPC prepared: t=pulumi:pulumi:Stack, name=simon-pulumi-test-siatest
    pulumi:pulumi:Stack simon-pulumi-test-siatest running debug: RegisterResource RPC prepared: t=pulumi:pulumi:Stack, name=simon-pulumi-test-siatest
    pulumi:pulumi:Stack simon-pulumi-test-siatest running debug: RegisterResource RPC finished: resource:simon-pulumi-test-siatest[pulumi:pulumi:Stack]; err: null, resp: urn:pulumi:siatest::simon-pulumi-test::pulumi:pulumi:Stack::simon-pulumi-test-siatest,,,true,
    pulumi:pulumi:Stack simon-pulumi-test-siatest running debug: Running program '/home/sia/dev/kube/pulumi' in pwd '/home/sia/dev/kube/pulumi' w/ args: 
    pulumi:pulumi:Stack simon-pulumi-test-siatest running debug: Registering resource: t=kubernetes:apps/v1:Deployment, name=nginx, custom=true
    pulumi:pulumi:Stack simon-pulumi-test-siatest running debug: Registering resource: t=kubernetes:core/v1:Service, name=nginx, custom=true
    pulumi:pulumi:Stack simon-pulumi-test-siatest running debug: RegisterResourceOutputs RPC prepared: urn=urn:pulumi:siatest::simon-pulumi-test::pulumi:pulumi:Stack::simon-pulumi-test-siatest
    pulumi:pulumi:Stack simon-pulumi-test-siatest running debug: RegisterResource RPC prepared: t=kubernetes:core/v1:Service, name=nginx
    pulumi:pulumi:Stack simon-pulumi-test-siatest running debug: RegisterResource RPC prepared: t=kubernetes:apps/v1:Deployment, name=nginx
    pulumi:pulumi:Stack simon-pulumi-test-siatest running debug: RegisterResourceOutputs RPC finished: urn=urn:pulumi:siatest::simon-pulumi-test::pulumi:pulumi:Stack::simon-pulumi-test-siatest; err: null, resp: 
    kubernetes:core:Service nginx  
    pulumi:pulumi:Stack simon-pulumi-test-siatest running debug: RegisterResource RPC finished: resource:nginx[kubernetes:core/v1:Service]; err: null, resp: urn:pulumi:siatest::simon-pulumi-test::kubernetes:core/v1:Service::nginx,sia-ns/nginx-service,__inputs,,,,,apiVersion,,,v1,kind,,,Service,metadata,,,,,labels,,,,,app.kubernetes.io/managed-by,,,pulumi,name,,,nginx-service,namespace,,,sia-ns,spec,,,,,ports,,,,,,,,,,name,,,http,port,,80,protocol,,,TCP,targetPort,,8080,selector,,,,,App,,,nginx,type,,,ClusterIP,apiVersion,,,v1,kind,,,Service,metadata,,,,,annotations,,,,,kubectl.kubernetes.io/last-applied-configuration,,,{"apiVersion":"v1","kind":"Service","metadata":{"labels":{"app.kubernetes.io/managed-by":"pulumi"},"name":"nginx-service","namespace":"sia-ns"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":8080}],"selector":{"App":"nginx"},"type":"ClusterIP"}}
 ~  kubernetes:apps:Deployment nginx updating [diff: ~metadata]
 ~  kubernetes:apps:Deployment nginx updating [diff: ~metadata]; [1/2] Waiting for app ReplicaSet be marked available
 ~  kubernetes:apps:Deployment nginx updating [diff: ~metadata]; ✅ Deployment initialization complete
 ~  kubernetes:apps:Deployment nginx updated [diff: ~metadata]; ✅ Deployment initialization complete
    pulumi:pulumi:Stack simon-pulumi-test-siatest running debug: RegisterResource RPC finished: resource:nginx[kubernetes:apps/v1:Deployment]; err: null, resp: urn:pulumi:siatest::simon-pulumi-test::kubernetes:apps/v1:Deployment::nginx,sia-ns/nginx-6xdb52z9,__inputs,,,,,apiVersion,,,apps/v1,kind,,,Deployment,metadata,,,,,annotations,,,,,foo,,,bar,pulumi.com/autonamed,,,true,labels,,,,,app.kubernetes.io/managed-by,,,pulumi,name,,,nginx-6xdb52z9,namespace,,,sia-ns,spec,,,,,replicas,,1,selector,,,,,matchLabels,,,,,App,,,nginx,template,,,,,metadata,,,,,labels,,,,,App,,,nginx,spec,,,,,containers,,,,,,,,,,image,,,nginx:1.17,name,,,nginx,apiVersion,,,apps/v1,kind,,,Deployment,metadata,,,,,annotations,,,,,deployment.kubernetes.io/revision,,,1,foo,,,bar,kubectl.kubernetes.io/last-applied-configuration,,,{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"foo":"bar","pulumi.com/autonamed":"true"},"labels":{"app.kubernetes.io/managed-by":"pulumi"},"name":"nginx-6xdb52z9","namespace":"sia-ns"},"spec":{"replicas":1,"selector":{"matchLabels":{"App":"nginx"}},"template":{"metadata":{"labels":{"App":"nginx"}},"spec":{"containers":[{"image":"nginx:1.17","name":"nginx"}]}}}}
    pulumi:pulumi:Stack simon-pulumi-test-siatest  12 debugs
 
Diagnostics:
  pulumi:pulumi:Stack (simon-pulumi-test-siatest):
    debug: Registering resource: t=pulumi:pulumi:Stack, name=simon-pulumi-test-siatest, custom=false
    debug: RegisterResource RPC prepared: t=pulumi:pulumi:Stack, name=simon-pulumi-test-siatest
    debug: RegisterResource RPC finished: resource:simon-pulumi-test-siatest[pulumi:pulumi:Stack]; err: null, resp: urn:pulumi:siatest::simon-pulumi-test::pulumi:pulumi:Stack::simon-pulumi-test-siatest,,,true,
    debug: Running program '/home/sia/dev/kube/pulumi' in pwd '/home/sia/dev/kube/pulumi' w/ args: 
    debug: Registering resource: t=kubernetes:apps/v1:Deployment, name=nginx, custom=true
    debug: Registering resource: t=kubernetes:core/v1:Service, name=nginx, custom=true
    debug: RegisterResourceOutputs RPC prepared: urn=urn:pulumi:siatest::simon-pulumi-test::pulumi:pulumi:Stack::simon-pulumi-test-siatest
    debug: RegisterResource RPC prepared: t=kubernetes:core/v1:Service, name=nginx
    debug: RegisterResource RPC prepared: t=kubernetes:apps/v1:Deployment, name=nginx
    debug: RegisterResourceOutputs RPC finished: urn=urn:pulumi:siatest::simon-pulumi-test::pulumi:pulumi:Stack::simon-pulumi-test-siatest; err: null, resp: 
    debug: RegisterResource RPC finished: resource:nginx[kubernetes:core/v1:Service]; err: null, resp: urn:pulumi:siatest::simon-pulumi-test::kubernetes:core/v1:Service::nginx,sia-ns/nginx-service,__inputs,,,,,apiVersion,,,v1,kind,,,Service,metadata,,,,,labels,,,,,app.kubernetes.io/managed-by,,,pulumi,name,,,nginx-service,namespace,,,sia-ns,spec,,,,,ports,,,,,,,,,,name,,,http,port,,80,protocol,,,TCP,targetPort,,8080,selector,,,,,App,,,nginx,type,,,ClusterIP,apiVersion,,,v1,kind,,,Service,metadata,,,,,annotations,,,,,kubectl.kubernetes.io/last-applied-configuration,,,{"apiVersion":"v1","kind":"Service","metadata":{"labels":{"app.kubernetes.io/managed-by":"pulumi"},"name":"nginx-service","namespace":"sia-ns"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":8080}],"selector":{"App":"nginx"},"type":"ClusterIP"}}
    ,creationTimestamp,,,2019-07-26T05:17:57Z,labels,,,,,app.kubernetes.io/managed-by,,,pulumi,name,,,nginx-service,namespace,,,sia-ns,resourceVersion,,,4590324,selfLink,,,/api/v1/namespaces/sia-ns/services/nginx-service,uid,,,ba7bd3b7-af64-11e9-862e-005056a3fa65,spec,,,,,clusterIP,,,100.75.23.134,ports,,,,,,,,,,name,,,http,port,,80,protocol,,,TCP,targetPort,,8080,selector,,,,,App,,,nginx,sessionAffinity,,,None,type,,,ClusterIP,status,,,,,loadBalancer,,,,,,true,
    debug: RegisterResource RPC finished: resource:nginx[kubernetes:apps/v1:Deployment]; err: null, resp: urn:pulumi:siatest::simon-pulumi-test::kubernetes:apps/v1:Deployment::nginx,sia-ns/nginx-6xdb52z9,__inputs,,,,,apiVersion,,,apps/v1,kind,,,Deployment,metadata,,,,,annotations,,,,,foo,,,bar,pulumi.com/autonamed,,,true,labels,,,,,app.kubernetes.io/managed-by,,,pulumi,name,,,nginx-6xdb52z9,namespace,,,sia-ns,spec,,,,,replicas,,1,selector,,,,,matchLabels,,,,,App,,,nginx,template,,,,,metadata,,,,,labels,,,,,App,,,nginx,spec,,,,,containers,,,,,,,,,,image,,,nginx:1.17,name,,,nginx,apiVersion,,,apps/v1,kind,,,Deployment,metadata,,,,,annotations,,,,,deployment.kubernetes.io/revision,,,1,foo,,,bar,kubectl.kubernetes.io/last-applied-configuration,,,{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"foo":"bar","pulumi.com/autonamed":"true"},"labels":{"app.kubernetes.io/managed-by":"pulumi"},"name":"nginx-6xdb52z9","namespace":"sia-ns"},"spec":{"replicas":1,"selector":{"matchLabels":{"App":"nginx"}},"template":{"metadata":{"labels":{"App":"nginx"}},"spec":{"containers":[{"image":"nginx:1.17","name":"nginx"}]}}}}
    ,pulumi.com/autonamed,,,true,creationTimestamp,,,2019-07-26T05:17:57Z,generation,,3,labels,,,,,app.kubernetes.io/managed-by,,,pulumi,name,,,nginx-6xdb52z9,namespace,,,sia-ns,resourceVersion,,,4591405,selfLink,,,/apis/apps/v1/namespaces/sia-ns/deployments/nginx-6xdb52z9,uid,,,ba778941-af64-11e9-862e-005056a3fa65,spec,,,,,progressDeadlineSeconds,,600,replicas,,1,revisionHistoryLimit,,10,selector,,,,,matchLabels,,,,,App,,,nginx,strategy,,,,,rollingUpdate,,,,,maxSurge,,,25%,maxUnavailable,,,25%,type,,,RollingUpdate,template,,,,,metadata,,,,,labels,,,,,App,,,nginx,spec,,,,,containers,,,,,,,,,,image,,,nginx:1.17,imagePullPolicy,,,IfNotPresent,name,,,nginx,resources,,,,,,terminationMessagePath,,,/dev/termination-log,terminationMessagePolicy,,,File,dnsPolicy,,,ClusterFirst,restartPolicy,,,Always,schedulerName,,,default-scheduler,securityContext,,,,,,terminationGracePeriodSeconds,,30,status,,,,,availableReplicas,,1,conditions,,,,,,,,,,lastTransitionTime,,,2019-07-26T05:17:59Z,lastUpdateTime,,,2019-07-26T05:17:59Z,message,,,Deployment has minimum availability.,reason,,,MinimumReplicasAvailable,status,,,True,type,,,Available,,,,,lastTransitionTime,,,2019-07-26T05:17:57Z,lastUpdateTime,,,2019-07-26T05:17:59Z,message,,,ReplicaSet "nginx-6xdb52z9-68fd8fc875" has successfully progressed.,reason,,,NewReplicaSetAvailable,status,,,True,type,,,Progressing,observedGeneration,,3,readyReplicas,,1,replicas,,1,updatedReplicas,,1,,
 
Resources:
    ~ 1 updated
    2 unchanged

Duration: 15m3s

Permalink: file:///home/sia/.pulumi/stacks/siatest.json
```

**Comment by aeb-sia** [comment] 2019-07-26 05:49
And I'm currently running:
```
 % pulumi version
v0.17.25
```

**Comment by hausdorff** [comment] 2019-07-26 19:40
@aeb-sia can you ping me on our community slack so I can help debug? https://slack.pulumi.io I'm @hausdorff over there.

**Comment by lukehoban** [comment] 2019-08-02 19:40
We haven’t been able to repro this - do pending new data we’ll close this out. @aeb-sia if there are any more details you can share to help reproduce - please do share.

**Closed by lukehoban** 2019-08-02 19:40 UTC
Labels: feature/q3, priority/P1
