### ISSUE TITLE
Helm OCI chart deployment fails in Windows

### ISSUE THREAD

**Issue by dirien** [pulumi/pulumi-kubernetes#2644] opened 2023-10-29 08:36 UTC
### What happened?

The deployment of a OCI Helm chart fails under Windows (tested with Windows 11) starting with version `3.29.0` of the Kubernetes provider with following message: `The filename, directory name, or volume label syntax is incorrect.`

![image](https://github.com/pulumi/pulumi-kubernetes/assets/38325136/b1b085c4-c36d-4c7b-88c7-7eedfa9c34cf)

I tested the code in Go and Typescript and both of the time I get the same error. Here the go version during `pulumi up`

![image](https://github.com/pulumi/pulumi-kubernetes/assets/38325136/f600cd14-d6bf-4337-9396-99ce2e2fd04b)

With `3.28.1` it works fine:

![image](https://github.com/pulumi/pulumi-kubernetes/assets/38325136/616fe888-ed59-4829-8bbc-0a18062e831e)

OCI support was introduced with #1892 since version `3.16.0` of the provider-``

### Non-Working example 

```json
{
    "name": "pulumi-stacks",
    "main": "index.ts",
    "devDependencies": {
        "@types/node": "^16"
    },
    "dependencies": {
        "@pulumi/pulumi": "^3.0.0",
        "@pulumi/kubernetes": "3.29.0"
    }
}
```

And snippet of code:

```typescript
//...

const ingressController = new kubernetes.helm.v3.Release("kubecost", {
    chart: "oci://public.ecr.aws/kubecost/cost-analyzer",
    namespace: "kubecost",
    createNamespace: true,
    version: "1.106.3",
});
```

Output:

```shell
 pulumi up -y -f
Updating (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/dirien/pulumi-stacks/dev/updates/13

     Type                              Name               Status                  Info
     pulumi:pulumi:Stack               pulumi-stacks-dev  **failed**              1 error
 +   └─ kubernetes:helm.sh/v3:Release  kubecost           **creating failed**     1 error
Diagnostics:
  pulumi:pulumi:Stack (pulumi-stacks-dev):
    error: update failed

  kubernetes:helm.sh/v3:Release (kubecost):
    error: CreateFile oci://public.ecr.aws/kubecost/cost-analyzer: The filename, directory name, or volume label syntax is incorrect.

Outputs:
    clusterName: "myFirstCivoCluster"
  + kubeconfig : [secret]

Resources:
    4 unchanged

Duration: 23s
```

### Output of `pulumi about`

```shell
PS C:\Users\dirien\pulumi-stacks> pulumi about 
CLI
Version      3.91.1
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME        VERSION
civo        2.3.11
kubernetes  3.29.0
nodejs      unknown

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22621 Build 22621
Arch     x86_64
```

### Additional context

There was a similar error reported back in 2018 with #143, maybe it is a regression?

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by EronWright** [comment] 2023-10-30 22:13
We recently added a new test for OCI support, [here](https://github.com/pulumi/pulumi-kubernetes/pull/2611/files#diff-0843835cc6b8540cb71c157e3e2be2ff69fee669b899f33cdac1eb144b31316dR460-R471).

I tried the example that was provided, and it works for me on macos with pulumi-kubernetes v4.5.2. Of course, it is possible that the problem is specific to Windows.

**Comment by mmisztal1980** [comment] 2023-10-31 10:59
@EronWright I've very recently attempted to provision an OCI helm chart using C#:

```csharp
var provider = new Pulumi.Kubernetes.Provider("k8s", new Pulumi.Kubernetes.ProviderArgs()
    {
      KubeConfig = "~/.kube/config",
      Context = "docker-desktop"
    });

    var ns = new Namespace("ingress", new Pulumi.Kubernetes.Types.Inputs.Core.V1.NamespaceArgs()
    {
      Metadata = new ObjectMetaArgs()
      {
        Name = "ingress"
      }
    }, new CustomResourceOptions()
    {
      Provider = provider
    });

    var nginx = new Chart("nginx-ingress", new ChartArgs
    {
      Chart = "nginx-ingress",
      Version = "1.0.1",
      Namespace = ns.Metadata.Apply(metadata => metadata.Name),
      Repo = "oci://ghcr.io/nginxinc/charts/nginx-ingress",
      FetchOptions = new ChartFetchArgs
      {
        Repo = "oci://ghcr.io/nginxinc/charts"
      },
    });
```

Here's what I got:

```
Previewing update (dev):
     Type                             Name               Plan       Info
 +   pulumi:pulumi:Stack              Ops.Local.K8S-dev  create     1 error
 +   ├─ kubernetes:helm.sh/v3:Chart   nginx-ingress      create     
 +   ├─ pulumi:providers:kubernetes   k8s                create     
 +   └─ kubernetes:core/v1:Namespace  ingress            create     


Diagnostics:
  pulumi:pulumi:Stack (Ops.Local.K8S-dev):
    error: Running program '/Users/mmisztal/Checkout/@cloud-tek/ops-local-infrastructure/Ops.Local.K8S/bin/Debug/net7.0/Ops.Local.K8S.dll' failed with an unhandled exception:
    Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="invocation of kubernetes:helm:template returned an error: failed to generate YAML for specified Helm chart: failed to pull chart: looks like "oci://ghcr.io/nginxinc/charts" is not a valid chart repository or cannot be reached: object required")
       at async Task<InvokeResponse> Pulumi.GrpcMonitor.InvokeAsync(ResourceInvokeRequest request)
       at async Task<SerializationResult> Pulumi.Deployment.InvokeRawAsync(string token, SerializationResult argsSerializationResult, InvokeOptions options) x 2
       at async Task<T> Pulumi.Deployment.InvokeAsync<T>(string token, InvokeArgs args, InvokeOptions options, bool convertResult)
       at async Task<OutputData<T>> Pulumi.Output<T>+<>c__DisplayClass12_0.<Create>g__GetData|0(?)+GetData(?)
       at async Task<OutputData<U>> Pulumi.Output<T>.ApplyHelperAsync<U>(Task<OutputData<T>> dataTask, Func<T, Output<U>> func) x 3
       at async Task<OutputData<object>> Pulumi.Output<T>.Pulumi.IOutput.GetDataAsync()
       at async Task<object> Pulumi.Serialization.Serializer.SerializeAsync(string ctx, object prop, bool keepResources, bool keepOutputValues)
       at async Task<RawSerializationResult> Pulumi.Deployment.SerializeFilteredPropertiesRawAsync(string label, IDictionary<string, object> args, Predicate<string> acceptKey, bool keepResources, bool keepOutputValues)
       at async Task<SerializationResult> Pulumi.Deployment.SerializeFilteredPropertiesAsync(string label, IDictionary<string, object> args, Predicate<string> acceptKey, bool keepResources, bool keepOutputValues)
       at async Task<Struct> Pulumi.Deployment.SerializeAllPropertiesAsync(string label, IDictionary<string, object> args, bool keepResources, bool keepOutputValues)
       at async Task Pulumi.Deployment.RegisterResourceOutputsAsync(Resource resource, Output<IDictionary<string, object>> outputs)
```

Can you clarify whether or not OCI support is working? or doing something incorrectly?

**Comment by EronWright** [comment] 2023-10-31 17:51
@mmisztal1980 I think the `repo` property is for using Helm repositories, not OCI repositories. Please specify the fully OCI URL in the `chart` property, e.g. `oci://ghcr.io/nginxinc/charts/nginx-ingress`.

**Comment by mmisztal1980** [comment] 2023-10-31 17:52
let me try that

**Comment by mmisztal1980** [comment] 2023-10-31 18:05
@EronWright progress! however an even more interesting error has appeared:

```csharp
    var nginx = new Chart("nginx", new ChartArgs
    {
      Chart = "oci://ghcr.io/nginxinc/charts/nginx-ingress",
      Version = "1.0.1",
      Namespace = ns.Metadata.Apply(metadata => metadata.Name),
      // FetchOptions = new ChartFetchArgs
      // {
      //   Repo = "oci://ghcr.io/nginxinc/charts/nginx-ingress"
      // },
    });

```

Error:

```
rror: Running program '/Users/mmisztal/Checkout/@cloud-tek/ops-local-infrastructure/Ops.Local.K8S/bin/Debug/net7.0/Ops.Local.K8S.dll' failed with an unhandled exception:
    Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="invocation of kubernetes:helm:template returned an error: failed to generate YAML for specified Helm chart: failed to create chart from template: chart requires kubeVersion: >= 1.22.0-0 which is incompatible with Kubernetes v1.0.1")
```

I've changed the version and it also got changed in the "kubernetes vX" version.  Is this something Pulumi is propagating?

**Comment by mmisztal1980** [comment] 2023-10-31 21:08
I've updated my previous post to make it a bit more clear

**Comment by alecor191** [comment] 2023-11-03 12:51
I'm getting the same error (on Win 11) as @dirien using `@pulumi/kubernetes: 4.5.3` package:

```typescript
export const deployActionsRunnerController = (namespace: Input<string>) =>
  new Release(chartName, {
    chart: 'oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller',
    name: chartName,
    namespace,
    dependencyUpdate: true,
    timeout: 300,
  });
```

Error:

```bash
error: CreateFile oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller: The filename, directory name, or volume label syntax is incorrect.
```

Works with `3.28.1`.

**Comment by mmisztal1980** [comment] 2023-11-03 14:36
oh hi @alecor191 ! :)

**Comment by EronWright** [comment] 2023-11-13 21:32
@alecor191 the issue that you are seeing is fixed by https://github.com/pulumi/pulumi-kubernetes/pull/2648 and will land soon.

@mmisztal1980 the issue that you are seeing is fixed in v4.5.4 (https://github.com/pulumi/pulumi-kubernetes/issues/2631).

**Comment by mmisztal1980** [comment] 2023-11-13 21:56
good to hear, btw is there any guidance on working with private OCI registries with Pulumi?

**Comment by EronWright** [comment] 2023-11-14 01:25
@mmisztal1980 see https://github.com/pulumi/pulumi-kubernetes/issues/1914 for private OCI registry support.

**Comment by mmisztal1980** [comment] 2023-11-14 07:10
Thank you!

**Closed** 2023-11-15 17:53 UTC
Labels: kind/bug, area/helm, os/windows
