### ISSUE TITLE
Install `kube-prometheus-stack` via helm

### ISSUE THREAD

**Issue by yellowhat** [pulumi/pulumi-kubernetes#1898] opened 2022-02-04 12:46 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Hi,
I would to install the `kube-prometheus-stack` chart:

```python
monitoring = kubernetes.helm.v3.Chart(
    "monitoring",                                                                                                                                                  
    kubernetes.helm.v3.ChartOpts(                                                                                                                                  
        chart="kube-prometheus-stack",                                                                                                                              
        namespace=monitoring_ns.metadata.name,                                                                                                                     
        fetch_opts=kubernetes.helm.v3.FetchOpts(
            repo="https://prometheus-community.github.io/helm-charts",                                                                                             
        ),
    ),                                          
    opts=ResourceOptions(provider=k8s_provider),
)
```
I get:

```console
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 107, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
        return future.result()
      File "/usr/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 110, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/usr/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 45, in run_pulumi_func
        await wait_for_rpcs()
      File "/usr/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 94, in wait_for_rpcs
        raise exception
      File "/usr/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 594, in do_register_resource_outputs
        serialized_props = await rpc.serialize_properties(outputs, {})
      File "/usr/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 150, in serialize_properties
        result = await serialize_property(v, deps, input_transformer, get_type(k), keep_output_values)
      File "/usr/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 292, in serialize_property
        value = await serialize_property(output.future(), promise_deps, input_transformer, typ, keep_output_values=False)
      File "/usr/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 277, in serialize_property
        future_return = await asyncio.ensure_future(awaitable)
      File "/usr/lib/python3.10/site-packages/pulumi/output.py", line 161, in run
        value = await self._future
      File "/usr/lib/python3.10/site-packages/pulumi/output.py", line 119, in get_value
        val = await self._future
      File "/usr/lib/python3.10/site-packages/pulumi/output.py", line 192, in run
        return await transformed.future(with_unknowns=True)
      File "/usr/lib/python3.10/site-packages/pulumi/output.py", line 119, in get_value
        val = await self._future
      File "/usr/lib/python3.10/site-packages/pulumi/output.py", line 192, in run
        return await transformed.future(with_unknowns=True)
      File "/usr/lib/python3.10/site-packages/pulumi/output.py", line 119, in get_value
        val = await self._future
      File "/usr/lib/python3.10/site-packages/pulumi/output.py", line 161, in run
        value = await self._future
      File "/usr/lib/python3.10/site-packages/pulumi/output.py", line 419, in gather_futures
        return await asyncio.gather(*value_futures_list)
      File "/usr/lib/python3.10/site-packages/pulumi/output.py", line 119, in get_value
        val = await self._future
      File "/usr/lib/python3.10/site-packages/pulumi/output.py", line 161, in run
        value = await self._future
      File "/usr/lib/python3.10/site-packages/pulumi/output.py", line 182, in run
        transformed: Input[U] = func(value)
      File "/usr/lib/python3.10/site-packages/pulumi_kubernetes/yaml/yaml.py", line 543, in <lambda>
        CustomResourceDefinition(f"{x}", opts, **obj)))]
      File "/usr/lib/python3.10/site-packages/pulumi_kubernetes/apiextensions/v1/CustomResourceDefinition.py", line 126, in __init__
        __self__._internal_init(resource_name, *args, **kwargs)
    TypeError: CustomResourceDefinition._internal_init() got an unexpected keyword argument 'status'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

Any ideas?

Thanks

**Comment by guineveresaenger** [comment] 2022-02-08 18:20
Duplicate of #1481

This is a known issue - we would recommend installing this with the new [Helm Release resource](https://www.pulumi.com/registry/packages/kubernetes/api-docs/helm/v3/release/), published with the latest version of this provider.

**Closed by guineveresaenger** 2022-02-08 18:20 UTC
Labels: kind/bug
