### ISSUE TITLE
Unable to create Provider with correct Kubeconfig

### ISSUE THREAD

**Issue by blaargh** [pulumi/pulumi-kubernetes#2712] opened 2023-12-13 10:54 UTC
### What happened?

When trying to use NewProvider with a kubeconfig from file, it is unable to parse the yaml:

> failed to parse kubeconfig: yaml: line 4: found character that cannot start any token

The Yaml file is valid and kubectl from the console can be executed without issues using this kubeconfig

### Example

```
// load kubeconfig from file
content, err := os.ReadFile("/path/to/kubeconfig.yaml")
if err != nil {
    log.Panic(err)
}
kubeconfig := string(content)
// Create new provider from config
k8sProvider, err := kubernetes.NewProvider(ctx, "k8sprovider", &kubernetes.ProviderArgs{
		Kubeconfig: pulumi.String(kubeconfig),
	})
```

Kubeconfig looks like this (sensitive information redacted):

```
apiVersion: v1
clusters:
- cluster:
    server: <redacted>
    certificate-authority-data: <redacted>
  name: <redacted>
contexts:
- context:
    cluster: <redacted>
    user: <redacted>
  name: internal
current-context: internal
kind: Config
preferences: {}
users:
- name: <redacted>
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws
      args:
      - --region
      - <redacted>
      - eks
      - get-token
      - --cluster-name
      - "internal"
      env:
      - name: AWS_PROFILE
        value: internal
```

### Output of `pulumi about`

CLI          
Version      3.96.2
Go Version   go1.21.5
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.0.2
go          unknown
kubernetes  4.5.5
kubernetes  3.30.2
kubernetes  1.6.0

Host     
OS       darwin
Version  14.2
Arch     arm64

This project is written in go: executable='/usr/local/go/bin/go' version='go version go1.21.5 darwin/arm64'

Dependencies:
NAME                                        VERSION
github.com/pulumi/pulumi-aws/sdk/v6         6.0.2
github.com/pulumi/pulumi/sdk/v3             3.92.0
gopkg.in/yaml.v2                            2.4.0
github.com/pulumi/pulumi-kubernetes         1.6.0
github.com/pulumi/pulumi-kubernetes/sdk/v3  3.30.2
github.com/pulumi/pulumi-kubernetes/sdk/v4  4.5.5

### Additional context

Reverting back to pulumi version 3.91.1 fixes this issue.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment] 2023-12-14 17:33
Hello @blaargh,

I apologize for any inconvenience this issue has caused. It seems that the problem might not be directly related to the issues you've referenced. While it's curious that it works with `kubectl` but not with our Kubernetes provider, my suspicion is that the discrepancy may be attributed to formatting errors in the kubeconfig file.

Specifically, the error message "`yaml: line 4: found character that cannot start any token`" suggests that there might be tabs on line 4 of your kubeconfig file. Please be aware that the YAML specification does not permit the use of tabs for indentation.

I've observed in your example that you are programmatically opening the file and converting it to a string for the provider. Could you check if providing the path to the kubeconfig directly also helps? For instance:

```go
kubeconfigPath := "/path/to/kubeconfig.yaml"
// Create a new provider from the config
k8sProvider, err := kubernetes.NewProvider(ctx, "k8sprovider", &kubernetes.ProviderArgs{
    Kubeconfig: pulumi.String(kubeconfigPath),
})
```

This adjustment might address the issue you're facing. Thank you for your patience, and please let me know if this resolves the issue or if further assistance is needed.

**Comment by blaargh** [comment] 2023-12-14 19:27
Hi @rquitales,

Indeed, it works when providing the path. However, I scanned the generated kubeconfig yaml like so:

`grep $'\t' kubeconfig-internal.yaml`

As well as with yq. Neither reports invalid yaml in line 4 or any tabs. So I am still certain this is a provider issue.

**Comment by rquitales** [comment] 2023-12-14 20:10
I'm unable to reproduce this issue on my end. I've copied the method you've used to specify the kubeconfig contents as a string and do not face any issues. I've also copied and pasted the kubeconfig template you provided verbatim, and added my own config to the redacted fields.

```go
package main

import (
        "os"

	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes"
	appsv1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/apps/v1"
	corev1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/core/v1"
	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	p "github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	p.Run(func(ctx *p.Context) error {
		content, err := os.ReadFile("<redacted_file_path>")
		if err != nil {
			log.Panic(err)
		}
		kubeconfig := string(content)

		provider, err := kubernetes.NewProvider(ctx, "k8s", &kubernetes.ProviderArgs{
			Kubeconfig:            p.String(kubeconfig),
		})
		if err != nil {
			return err
		}
...
```

I am using v4.6.0 of the Kubernetes provider, Go 1.21.5 and Pulumi CLI v3.96.2.

Could you try printing the contents of the read `kubeconfig` string variable to stdout to see if there are any discrepancies? Something like `fmt.Println(strconv.Quote(kubeconfig))`.

**Comment by blaargh** [comment] 2023-12-15 09:41
Printing the read config like in your example gives me this string:

`"apiVersion: v1\nclusters:\n- cluster:\n    server:<redacted>\n    certificate-authority-data:<redacted>\n  name: arn:aws:eks:eu-central-1:260213969297:cluster/internal\ncontexts:\n- context:\n    cluster: <redacted>\n    user: <redacted>\n  name: internal\ncurrent-context: internal\nkind: Config\npreferences: {}\nusers:\n- name: <redacted>\n  user:\n    exec:\n      apiVersion: client.authentication.k8s.io/v1beta1\n      command: aws\n      args:\n      - --region\n      - eu-central-1\n      - eks\n      - get-token\n      - --cluster-name\n      - \"internal\"\n      env:\n      - name: AWS_PROFILE\n        value: internal\n"`

I suppose the escape character COULD be an issue, but since you weren't able to reproduce it, and the kubeconfig itself is usable with kubectl, I don't see how...

**Comment by EronWright** [comment] 2024-01-25 19:32
@blaargh I'm going to close this issue as "no repro" but please open another issue if the problem recurs.

**Closed by EronWright** 2024-01-25 19:32 UTC
Labels: kind/bug, awaiting-feedback
