### ISSUE TITLE
Deployment diff causing replace instead of update

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi-kubernetes#1140] opened 2020-05-20 02:26 UTC
A deployment was changed with an environment variable inserted into the list, changing the order of env vars like so:

```
# many lines removed
~ spec      : {
    ~ template: {
        ~ spec    : {
            ~ containers                   : [
                ~ [0]: {
                        ~ env            : [
                        # many lines removed
                        ~ [14]: {
                                ~ name     : "ENV_VAR_A" => "SOME_NEW_ENV_VAR"
                                - value    : "env-var-a-value"
                                + valueFrom: {
                                    + secretKeyRef: {
                                        + key : "a-key"
                                        + name: "on-a-secret-resource"
                                    }
                                }
                            }
                        + [15]: {
                                + name : "ENV_VAR_A"
                                + value: "env-var-a-value"
                            }
```

This appeared to result in a replace instead of an update operation, as other Deployments in the same project were updated, but their `containers[].env` spec was not changed.

### Errors & Logs

This resulted in spurious creation failures which had to be resolved by reverting the change and then re-running the deployment job several times:

```
  ++ kubernetes:apps:Deployment client-default-backend creating replacement [diff: ~spec]; error: resource vendor-sync/client-default-backend was not successfully created by the Kubernetes API server : deployments.apps "client-default-backend" already exists
```

The default create-and-delete policy for k8s resources has a race condition.

### Affected product version(s)

Pulumi 1.14.1
Kubernetes provider 1.6.0

### Suggestions for a fix

I wasn't able to discern why a change to the env would key would result in a replace operation. Is it because of the `valueFrom: { secretKeyRef: ... }`? If so, that shouldn't be cause for a replace, as the Deployment will take care of creating a new replicaset with the new env spec.

The only distinction between Deployments which were "updated" and "replaced" was that the latter had changes to their `containers[].env`, so I assume something there is causing a "replace".

**Comment by leezen** [comment] 2020-05-20 17:19
This looks like a duplicate of https://github.com/pulumi/pulumi-kubernetes/issues/1140 or am I missing something?

**Comment by lblackstone** [comment] 2020-05-20 19:59
> This looks like a duplicate of #1140 or am I missing something?

You linked back to this same issue. Was there another one you had in mind?

**Comment by leezen** [comment] 2020-05-20 21:07
Gah, bad copy and paste. I meant to link https://github.com/pulumi/pulumi-kubernetes/issues/1133

**Comment by Dominik-K** [comment] 2020-05-22 15:06
@leezen #1133 is about `Service.spec.type`, here about `Deployment...containers[0].env[]`. So only similar as `pulumi-kubernetes` also did a replace instead update there, too.

@AaronFriel What were the changes in the other `Deployment`s which trigger only a "replace"?

**Comment by AaronFriel** [comment] 2020-05-24 04:01
@Dominik-K the changes in the deployments fell into two categories:

1. Updating `containers[].env[]` and `containers[].image`
2. Updating `containers[].image` only

The latter were updates vs replaces.

**Comment by protometa** [comment] 2020-06-02 07:29
I'm also getting deployment replacements when I change a secret used by a deployment. I thought that sort of thing used to just trigger an update.

The replace itself is happening with a change to the name of the autonamed deployment e.g. `metadata.name : "my-app-7vijq5ed" => "my-app-hm623g3v"` in diff.

**Comment by Aaronontheweb** [comment] 2020-07-27 22:04
I'm running into this as well when just changing `containers[].image`

**Comment by lblackstone** [comment] 2020-07-27 22:41
I tried changing those fields locally on a Deployment, and wasn't able to reproduce the replacement behavior. Can anyone provide a repro case?

**Comment by ninja-** [comment] 2020-07-31 10:51
I can repro this when changing envs on container...

**Comment by ninja-** [comment] 2020-07-31 19:20
I was using env["version"] = something_dynamic to force kubernetes to restart pods on deployment change.
That was triggering this bug which made pulumi "replace" deployment instead of update, and broke rolling restarts.
I switched to using dynamic `container.image` and that resulted in pulumi doing proper replace...

**Comment by ninja-** [comment] 2020-07-31 19:24
That's weird considering "env" is not on the hardcoded list here... https://github.com/pulumi/pulumi-kubernetes/blob/c644505339561a32efaaef54c73cc833b1706605/provider/pkg/provider/diff.go#L169

**Comment by lblackstone** [comment] 2020-08-03 15:09
I still haven't been able to reproduce this behavior (using v2.4.1).

I tried with the following program:
```ts
import * as k8s from "@pulumi/kubernetes";
import * as random from "@pulumi/random";

const foo = new random.RandomString("foo", {
    length: 8,
}).result;

const appLabels = {app: "nginx"};
new k8s.apps.v1.Deployment("foo", {
    metadata: {
        name: "scale-test",
    },
    spec: {
        selector: {matchLabels: appLabels},
        replicas: 1,
        template: {
            metadata: {labels: appLabels},
            spec: {
                containers: [
                    {name: "nginx", image: "nginx:1.13", ports: [{containerPort: 80}], env: [{name: "FOO", value: foo}]}
                ],
            },
        },
    },
})
```

Neither adding additional env vars nor changing the value of the computed random string caused a replace in my testing.

**Comment by AaronFriel** [comment] 2021-11-08 19:25
Hey @lblackstone I think I determined the cause, as I just found another case of this.

It looks like the issue is that we had a `Deployment.spec.template.metadata.annotations[]` entry like so:

```ts
            annotations: {
              'checksum/config': configMapHash,
            },
```

Where the annotation was derived from the hash of `ConfigMap`'s `spec.data`:

```ts
  const configMapHash = configMap.data.apply((data) => sha256(JSON.stringify(data)));
```

And the **ConfigMap** had a `replace` performed, which transitively caused `configMapHash` to carry with it the need to perform a replacement.

**Comment by lblackstone** [comment] 2021-11-15 23:43
Thanks for the update @AaronFriel. It sounds like this is working as intended then, but the docs were confusing about the expected behavior. Does that sounds right?

If so, let's close this issue out and track the docs update in https://github.com/pulumi/pulumi-kubernetes/issues/1568

**Comment by AaronFriel** [comment] 2021-11-17 16:40
Of course, I think that's right. We did have some issues moving to the "happy path" where we had some resources using fixed resource names, and I think documentation and/or offering a choice of behavior seems reasonable.

I believe Kubernetes now has an `immutable` property on these resources to act as a hint.

**Closed** 2021-12-01 23:21 UTC
Labels: resolution/by-design
