### ISSUE TITLE
[Helm/Release] absent keyring value keeps updating

### ISSUE THREAD

**Issue by ruckc** [pulumi/pulumi-kubernetes#1724] opened 2021-09-18 13:25 UTC
With the new `helm.v3.Release` when I do a preview, it always shows `Plan: update`, and `Info: [diff ~keyring]`.  keyring is unset, but keeps changing?

## Steps to reproduce
```ts
        const namespace = new k8s.core.v1.Namespace("prometheus", {
            metadata: {
                name: "prometheus",
            },
        });
        const release = new k8s.helm.v3.Release("prometheus", {
            name: "kube-prometheus-stack",
            chart: "kube-prometheus-stack",
            repositoryOpts: {
                repo: "https://prometheus-community.github.io/helm-charts",
            },
            version: this.version,
            namespace: namespace.metadata.name,
        });
```

Expected: If nothing changes, the resource shouldn't show changed.
Actual: 
```
     Type                              Name                                  Plan       Info
     pulumi:pulumi:Stack               project-dev                                      
 ~   ├─ kubernetes:helm.sh/v3:Release  prometheus                            update     [diff: ~keyring]
```

**Comment by viveklak** [comment] 2021-09-18 16:26
Thanks for the report. Investigating this.

**Comment by ruckc** [comment] 2021-09-18 22:09
Looks like its automatically pulling in whatever `~/.gpg/pubring.gpg` which causes preview to churn since i'm using github actions.

**Comment by viveklak** [comment] 2021-09-20 16:46
> Looks like its automatically pulling in whatever `~/.gpg/pubring.gpg` which causes preview to churn since i'm using github actions.

Indeed. IIRC this is what Helm CLI does as well but I will confirm here. Could you consider setting it to a constant value?

**Comment by lblackstone** [comment] 2023-07-14 20:36
It looks like this matches Helm's behavior, so closing as "by design"

**Closed by lblackstone** 2023-07-14 20:36 UTC
Labels: kind/bug, area/helm, resolution/by-design
