### ISSUE TITLE
Error templating helm chart with python SDL

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-kubernetes#1400] opened 2020-12-09 04:03 UTC
### Problem description

Trying to install the aws load balancer controller helm chart with the Python SDK and the template never renders

### Errors & Logs

```
  pulumi:pulumi:Stack (aws-lb-controller-dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/Users/lbriggs/src/go/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
        return future.result()
      File "/Users/lbriggs/src/git/jaxxstorm/eks-workshop/aws-lb-controller/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 83, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/lbriggs/src/git/jaxxstorm/eks-workshop/aws-lb-controller/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await RPC_MANAGER.rpcs.pop()
      File "/Users/lbriggs/src/git/jaxxstorm/eks-workshop/aws-lb-controller/venv/lib/python3.9/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File "/Users/lbriggs/src/git/jaxxstorm/eks-workshop/aws-lb-controller/venv/lib/python3.9/site-packages/pulumi/runtime/resource.py", line 499, in do_register_resource_outputs
        serialized_props = await rpc.serialize_properties(outputs, {})
      File "/Users/lbriggs/src/git/jaxxstorm/eks-workshop/aws-lb-controller/venv/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 79, in serialize_properties
        result = await serialize_property(v, deps, input_transformer)
      File "/Users/lbriggs/src/git/jaxxstorm/eks-workshop/aws-lb-controller/venv/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 201, in serialize_property
        value = await serialize_property(output.future(), deps, input_transformer)
      File "/Users/lbriggs/src/git/jaxxstorm/eks-workshop/aws-lb-controller/venv/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 187, in serialize_property
        future_return = await asyncio.ensure_future(awaitable)
      File "/Users/lbriggs/src/git/jaxxstorm/eks-workshop/aws-lb-controller/venv/lib/python3.9/site-packages/pulumi/output.py", line 113, in get_value
        val = await self._future
      File "/Users/lbriggs/src/git/jaxxstorm/eks-workshop/aws-lb-controller/venv/lib/python3.9/site-packages/pulumi/output.py", line 185, in run
        return await transformed.future(with_unknowns=True)
      File "/Users/lbriggs/src/git/jaxxstorm/eks-workshop/aws-lb-controller/venv/lib/python3.9/site-packages/pulumi/output.py", line 113, in get_value
        val = await self._future
      File "/Users/lbriggs/src/git/jaxxstorm/eks-workshop/aws-lb-controller/venv/lib/python3.9/site-packages/pulumi/output.py", line 185, in run
        return await transformed.future(with_unknowns=True)
      File "/Users/lbriggs/src/git/jaxxstorm/eks-workshop/aws-lb-controller/venv/lib/python3.9/site-packages/pulumi/output.py", line 113, in get_value
        val = await self._future
      File "/Users/lbriggs/src/git/jaxxstorm/eks-workshop/aws-lb-controller/venv/lib/python3.9/site-packages/pulumi/output.py", line 154, in run
        value = await self._future
      File "/Users/lbriggs/src/git/jaxxstorm/eks-workshop/aws-lb-controller/venv/lib/python3.9/site-packages/pulumi/output.py", line 338, in gather_futures
        return await asyncio.gather(*value_futures)
      File "/Users/lbriggs/src/git/jaxxstorm/eks-workshop/aws-lb-controller/venv/lib/python3.9/site-packages/pulumi/output.py", line 113, in get_value
        val = await self._future
      File "/Users/lbriggs/src/git/jaxxstorm/eks-workshop/aws-lb-controller/venv/lib/python3.9/site-packages/pulumi/output.py", line 154, in run
        value = await self._future
      File "/Users/lbriggs/src/git/jaxxstorm/eks-workshop/aws-lb-controller/venv/lib/python3.9/site-packages/pulumi/output.py", line 175, in run
        transformed: Input[U] = func(value)
      File "/Users/lbriggs/src/git/jaxxstorm/eks-workshop/aws-lb-controller/venv/lib/python3.9/site-packages/pulumi_kubernetes/yaml.py", line 531, in <lambda>
        CustomResourceDefinition(f"{x}", opts, **obj)))]
    TypeError: __init__() got an unexpected keyword argument 'status'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

### Affected product version(s)

pulumi v2.15.1
pulumi_kubernetes v2.7.3

### Reproducing the issue

```python

kubeconfig = cluster.get_output("kubeconfig")
cluster_name = cluster.get_output("clusterName")
vpc_id = cluster.get_output("vpcId")

k8s.helm.v3.Chart(
    "lb", k8s.helm.v3.ChartOpts(
        chart="aws-load-balancer-controller",
        fetch_opts=k8s.helm.v3.FetchOpts(
            repo="https://aws.github.io/eks-charts"
        ),
        namespace=namespace.metadata["name"],
        values={
            "clusterName": "foo",
            "region": "us-west-1",
            "serviceAccount": {
                "name": "aws-lb-controller-serviceaccount"
            },
            "vpcId": vpc_id,
            "podLabels": {
                "stack": stack,
                "app": "aws-lb-controller"
            }
        }
    ), pulumi.ResourceOptions(
        provider=provider
    )
)
```

**Comment by lblackstone** [comment] 2020-12-09 16:46
Closing as a dupe of https://github.com/pulumi/pulumi-kubernetes/issues/800

See https://github.com/pulumi/pulumi-kubernetes/issues/800#issuecomment-697944262 for a workaround

**Closed by lblackstone** 2020-12-09 16:46 UTC
Labels: area/helm
