### ISSUE TITLE
Output to YAML AND deploy using same Pulumi code

### ISSUE THREAD

**Issue by garethr** [pulumi/pulumi-kubernetes#1327] opened 2020-09-20 06:47 UTC
### Problem description

Following https://github.com/pulumi/pulumi-kubernetes/issues/1025 I was able to get render_yaml_to_directory to output YAML files from my Python code. However, I noticed (as documented) that this means I can’t then deploy those resources to the cluster with Pulumi as well. I'm looking though to do both:

1. run pulumi up
2. deploy to cluster
3. generate YAML

I tried:

* Passing providers and a list of providers, but that didn’t seemed to revert to defaults :x:
* Using a config as a toggle between two providers, but this led to state problems :x:
* Abstracting the resources, and then applying twice in the same script, but Pulumi complains about them having the same name :x:

Appreciate this has a nice BETA FEATURE warning. I’d be interested if anyone has a pattern for doing the above, or if this might be supported in thee future.

> :param pulumi.Input[str] render_yaml_to_directory: BETA FEATURE - If present, render resource manifests to this directory. In this mode, resources will not
>                be created on a Kubernetes cluster, but the rendered manifests will be kept in sync with changes
>                to the Pulumi program. This feature is in developer preview, and is disabled by default.
>                Note that some computed Outputs such as status fields will not be populated
>                since the resources are not created on a Kubernetes cluster. These Output values will remain undefined,
>                and may result in an error if they are referenced by other resources. Also note that any secret values
>                used in these resources will be rendered in plaintext to the resulting YAML.

Conversation in https://pulumi-community.slack.com/archives/CRFURDVQB/p1600518879011300

### Affected product version(s)

* Pulumi `v2.10.1`
* macOS `10.15.6`
* Python `3.8.3`

**Comment by sanmai-NL** [comment] 2022-10-14 12:07
Rendering doesn't work at all for me under Python. I read #1025. How do you do it?

**Comment by lblackstone** [comment] 2022-10-17 19:27
@sanmai-NL I just checked with the following program, and it seems to be working as expected. If you're still having problems, please open a new issue.

```py3
import pulumi_kubernetes as k8s
import pulumi

prov = k8s.Provider("k8s", k8s.ProviderArgs(
    render_yaml_to_directory="rendered"
))

k8s.core.v1.Namespace(
    "test",
    opts=pulumi.ResourceOptions(
        provider=prov,
    ))
```
```
cat rendered/1-manifest/v1-namespace-default-test-64773ace.yaml
───────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: rendered/1-manifest/v1-namespace-default-test-64773ace.yaml
───────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ apiVersion: v1
   2   │ kind: Namespace
   3   │ metadata:
   4   │   annotations:
   5   │     kubectl.kubernetes.io/last-applied-configuration: |
   6   │       {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{"pulumi.com/autonamed":"true"},"labels":{"app.kubernetes.io/managed-by":"pulumi"},"name":"test-64773ace"}}
   7   │     pulumi.com/autonamed: "true"
   8   │   labels:
   9   │     app.kubernetes.io/managed-by: pulumi
  10   │   name: test-64773ace
───────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by lblackstone** [comment] 2023-07-14 20:19
Closing as a dupe of #1620, which includes a workaround in this comment: https://github.com/pulumi/pulumi-kubernetes/issues/1620#issuecomment-1373188238

**Closed by lblackstone** 2023-07-14 20:19 UTC
Labels: kind/enhancement, resolution/duplicate
