### ISSUE TITLE
helm.Chart/yaml transformations for nodejs should respect return values, not only support mutating input

### ISSUE THREAD

**Issue by gobengo** [pulumi/pulumi-kubernetes#556] opened 2019-05-04 17:19 UTC
As part of #555, I was making a transformation to pass to `helm.Chart` that would remove any helm hooks.

As there are kind of limited docs for what sort of functions are supported, and the type is pretty broad, at first I tried:

```
function removePodsWithHooksTransformation() {
	return (o: any) => {
		if ( ! o) return
		if (o.metadata && o.metadata.annotations && o.metadata.annotations['helm.sh/hook']) {
			console.log('skipping helm hook', o.metadata)
			return 
		}
		return o
	}
}
```

(assuming maybe returning falsy would 'transform' the input into 'nothing').
I ran `pulumi up` and it didn't have the effect I wanted.

Then I searched the code on here and first found the python yaml parser and noticed that it was going to [require a return value of an object](https://github.com/pulumi/pulumi-kubernetes/blob/29d2b48affdd07ca314970e2c6370e7f90f17c5d/sdk/python/pulumi_kubernetes/yaml.py#L150) with at least `kind` property. So I rewrote to:

```
function removePodsWithHooksTransformation() {
	return (o: any) => {
		if ( ! o) return
		if (o.metadata && o.metadata.annotations && o.metadata.annotations['helm.sh/hook']) {
			console.log('skipping helm hook', o.metadata)
			return {
				kind: "List",
				apiVersion: "v1",
				metadata: {},
				items: [],
			}
		}
		return o
	}
}
```

Then I deployed again, still didn't work. I read more code and learned that the same logic for python (that uses a return value) exists in the nodejs sdk. But in the nodejs sdk, [the return value is thrown away and the transformation expects you to mutate the object input](https://github.com/pulumi/pulumi-kubernetes/blob/4b01b5114df3045cecefd2ff3e2f2ed64430e3dd/sdk/nodejs/yaml/yaml.ts#L2214).

Finally what works is:
```
function removePodsWithHooksTransformation() {
	return (o: any) => {
		if ( ! o) return
		if (o.metadata && o.metadata.annotations && o.metadata.annotations['helm.sh/hook']) {
			console.log('skipping helm hook', o.metadata)
			// transforms in nodejs expects you to mutate input object, not return a new one :/
			// https://github.com/pulumi/pulumi-kubernetes/blob/4b01b5114df3045cecefd2ff3e2f2ed64430e3dd/sdk/nodejs/yaml/yaml.ts#L2214
			for (const key in o) {
				delete o[key]
			}
			Object.assign(o, {
				kind: "List",
				apiVersion: "v1",
				metadata: {},
				items: [],
			})
			return
		}
		return o
	}
}
```

As you can see above, this is kind of awkward when you really want to transform the input object to something completely different like an empty List, as you have to go through and delete all the existing keys. In my experience, it is quite uncommon to have a JavaScript API where you are encouraged to mutate the object passed to you. Instead usually you return a value based on the input.

The exact API design is subjective. But I do think it's worth noting that the python sdk transformation logic uses the return value (and doesnt necessarily respect your mutations to the input object), but the nodejs one is the opposite, and it would be nice if at least they were the same.

Thoughts?

**Comment by gobengo** [comment] 2019-05-30 00:05
Recently discovered https://github.com/pulumi/pulumi-kubernetes/issues/161 and it's basically the same, i.e. this is a use-case and workaround for that.

**Comment by lukehoban** [comment] 2019-05-30 00:30
Yes - this is exactly what #161 was tracking - and it remains important.  I'll close this out as a duplicate of that - but I've added a note to #161 calling out this specific example so we consider it as part of the design of an improve `transforms` function.

**Closed by lukehoban** 2019-05-30 00:30 UTC
