### ISSUE TITLE
Snapshot integrity failure when kubernetes provider changes

### ISSUE THREAD

**Issue by jsravn** [pulumi/pulumi-kubernetes#1730] opened 2021-09-22 14:41 UTC
The original issue is at https://github.com/pulumi/pulumi/issues/4996.

Example error:
```
error: .pulumi/stacks/sandbox.json: snapshot integrity failure; refusing to use it: resource urn:pulumi:sandbox::cloud-infra-pulumi::kubernetes:yaml:ConfigGroup$kubernetes:rbac.authorization.k8s.io/v1:Role::kube-public/anonymous-kube-root-ca refers to unknown provider urn:pulumi:sandbox::cloud-infra-pulumi::pulumi:providers:kubernetes::gke-cluster::f352a78a-34a1-450e-afdb-44b926694153
```

## Steps to reproduce

1. Recreate a cluster (EKS, GKE, whatever) that the kubernetes provider depends on for its configuration, e.g. by changing its name or other parameters.
2. Eventually pulumi will fail with "Snapshot integrity failure" as described in the linked issue

The statefile has all of the old resources in the deleted cluster, referring to the old provider. For some reason these are not being removed, but the provider gets removed from the state file (replaced w/ the new one).

I have tried adding explicit dependencies from the provider to the cluster resource and nodepool resource but it makes no difference. This always seems to happen when recreating a cluster.

The workaround is manually remove the old k8s resources from the state.

Expected: 
Actual:

**Comment by DavidHe1127** [comment] 2022-05-04 01:20
Is there any updates? In my case, I was trying to change from using `kubeconfig` to `context` (kubeconfig is pre-loaded in the build agents). Looking into state file, it shows `main-new` provider was created and has itself aliased to old `main` which still exists in the file. Moreover, the dependent resources are pointing to the new provider. Everything looks good to me, however I still have the same issue.

```js
export const eksProvider = new kubernetes.Provider('main-new', {
  namespace: kubernetesNamespace,
  // kubeconfig: kubeconfig.apply(JSON.stringify),
  context: `arn:aws:eks:${awsRegion}:${accountId}:cluster/${eksClusterName}`,
}, {
  aliases: [{
    name: 'main'
  }]
});
```

**Comment by lblackstone** [comment] 2023-07-14 21:05
Closing as a duplicate of https://github.com/pulumi/pulumi/issues/4996

**Closed by lblackstone** 2023-07-14 21:05 UTC
Labels: area/providers, impact/usability, kind/bug, resolution/duplicate
