### ISSUE TITLE
Helm release `value_yaml_files` take precidence over `values`

### ISSUE THREAD

**Issue by alex-hunt-materialize** [pulumi/pulumi-kubernetes#2188] opened 2022-09-22 18:52 UTC
### What happened?

I am attempting to use the `values-eks-cost-monitoring.yaml` file shipped with the kubecost cost-analyzer helm chart as defaults in `value_yaml_files`, and override them with `values`.

The Helm `Release` field `values` is supposed to override values from files in `value_yaml_files`, but the opposite seems to be happening.

This comment says that `values` should win:
https://github.com/pulumi/pulumi-kubernetes/blob/master/sdk/nodejs/helm/v3/release.ts#L305

### Steps to reproduce

1. Set some value in a yaml file.
2. Point to that yaml file in the helm release in the `value_yaml_files` field.
3. Override that value in `values`.

Example python code:
```python3
        helm_chart_version = "1.97.0"
        self.helm_release = k8s.helm.v3.Release(
            "kubecost",
            name="kubecost",
            chart=f"infra/helm/charts/kubecost/cost-analyzer/{helm_chart_version}/cost-analyzer",
            namespace=self.namespace.metadata.name,
            value_yaml_files=[
                pulumi.FileAsset(
                    f"infra/helm/charts/kubecost/cost-analyzer/{helm_chart_version}/cost-analyzer/values-eks-cost-monitoring.yaml"
                ),
            ],
            values=cast(
                Output[Dict[str, Any]],
                Output.from_input(zone_ips).apply(
                    lambda zone_ips: {
                        # They forgot to bump the version in the values file in 1.97.0
                        "imageVersion": f"prod-{helm_chart_version}",
                        "networkCosts": {
                            "enabled": "true",
                            "config": {
                                "destinations": {
                                    "in-zone": [
                                        "127.0.0.1",
                                        "169.254.0.0/16",
                                    ],
                                    "in-region": [
                                        cluster.mz_vpc.cidr,
                                    ],
                                    "direct-classification": [
                                        {
                                            "region": cluster.mz_vpc.region,
                                            "zone": zone,
                                            "ips": ips,
                                        }
                                        for zone, ips in zone_ips.items()
                                    ],
                                },
                            },
                        },
                        "persistentVolume": {
                            "storageClass": cluster.ebs_storage_class.metadata.name,
                        },
                        "prometheus": {
                            "server": {
                                "persistentVolume": {
                                    "size": "1024Gi",
                                    "storageClass": cluster.ebs_storage_class.metadata.name,
                                },
                            },
                        },
                    }
                ),
            ),
            opts=pulumi.ResourceOptions(
                parent=self.k8s_provider,
                provider=self.k8s_provider,
                depends_on=[
                    cluster,
                    self.namespace,
                    self.cilium_allow_within_namespace_policy,
                    self.cilium_prometheus_egress,
                ],
            ),
        )
```

Relevant parts of the values file:
https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.97.0/cost-analyzer/values-eks-cost-monitoring.yaml#L36
https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.97.0/cost-analyzer/values-eks-cost-monitoring.yaml#L129

The values file has the `imageVersion` and `prometheus.server.persistentVolue.size` fields specified, and the values in the python code setting these are ignored.

### Expected Behavior

The values in the python code in the helm release `values` field should "win", and override any values from the `value_yaml_files`.

### Actual Behavior

The values from `value_yaml_files` "win", and the values from the `values` field are ignored.

### Output of `pulumi about`

```
CLI          
Version      3.39.3
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME              VERSION
aws               5.13.0
cloudinit         1.3.0
command           0.5.2
crds              0.0.0
docker-buildkit   0.1.17
eks               0.40.0
fivetran          0.1.6
frontegg          0.2.23
honeycomb         0.0.11
kubernetes        3.21.2
kubernetes-proxy  0.1.3
linkerd-link      0.0.7
postgresql        3.6.0
postgresql-exec   0.1.1
python            unknown
random            4.7.0
tls               4.6.1

Host     
OS       fedora
Version  36
Arch     x86_64

This project is written in python: executable='/home/alex/git2/cloud/venv/bin/python3' version='3.10.6

[Stack URNs redacted]


Found no pending operations associated with alexhunt

[state org and hostname redacted]
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment] 2022-09-23 16:55
Following the code through in the provider...

1. [This test](https://github.com/pulumi/pulumi-kubernetes/blob/master/provider/pkg/provider/helm_release_test.go#L37-L40) asserts that `dest` is overriden by `src`.
2. `dest` is the first argument when testing, `src` is the second argument.
3. Therefore the second argument takes precedence over the first.
4. When we [call `mergeMaps` in the provider](https://github.com/pulumi/pulumi-kubernetes/blob/3c1b35cb3e183d572f374ff28b0505c4e412464c/provider/pkg/provider/helm_release.go#L307) the first argument is the `release.Values`, the second argument is the local `values` - which are the values deserialized from the asset.
5. Therefore the assets overwrite the Values.

I agree this stands in contradiction to the documentation comment.

@lblackstone any thoughts on if we should change the behaviour or the documentation here?

**Comment by danielrbradley** [comment] 2022-09-23 17:05
This is also a duplicate of https://github.com/pulumi/pulumi-kubernetes/issues/1986

**Comment by viveklak** [comment] 2022-09-23 17:17
Yes the behavior in the documentation is what we need. #2191 fixes this.

**Closed** 2022-09-23 18:04 UTC
Labels: kind/bug
