### ISSUE TITLE
Previews against inaccessible clusters hang for 30 seconds and then succeed

### ISSUE THREAD

**Issue by swgillespie** [pulumi/pulumi-kubernetes#349] opened 2019-01-09 19:39 UTC
I encountered this when trying to run an update against a cluster that doesn't exist anymore. What seemed to happen is that any resource that I created during the preview timed out after 30 seconds and then succeeded:

```
    I0109 11:32:04.026380   87855 round_trippers.go:386] curl -k -v -XGET  -H "Accept: application/com.github.proto-openapi.spec.v2@v1.0+protobuf" -H "User-Agent: pulumi-resource-kubernetes/v0.0.0 (darwin/amd64) kubernetes/$Format" https://146.148.15.185/openapi/v2
    I0109 11:32:34.026839   87855 round_trippers.go:405] GET https://146.148.15.185/openapi/v2  in 30000 milliseconds
    I0109 11:32:34.026884   87855 round_trippers.go:411] Response Headers:
    I0109 11:32:34.027012   87855 rpc.go:68] Marshaling property for RPC[Provider[kubernetes].Check(urn:pulumi:pyprovider::provider::kubernetes:core/v1:Pod::nginx).autonamedInputs]: apiVersion={v1}
    I0109 11:32:34.027050   87855 rpc.go:68] Marshaling property for RPC[Provider[kubernetes].Check(urn:pulumi:pyprovider::provider::kubernetes:core/v1:Pod::nginx).autonamedInputs]: kind={Pod}
    I0109 11:32:34.027059   87855 rpc.go:68] Marshaling property for RPC[Provider[kubernetes].Check(urn:pulumi:pyprovider::provider::kubernetes:core/v1:Pod::nginx).autonamedInputs]: metadata={map[annotations:{map[pulumi.com/autonamed:{true}]} name:{nginx-f9i7eb6i}]}
    I0109 11:32:34.027079   87855 rpc.go:68] Marshaling property for RPC[Provider[kubernetes].Check(urn:pulumi:pyprovider::provider::kubernetes:core/v1:Pod::nginx).autonamedInputs]: annotations={map[pulumi.com/autonamed:{true}]}
    I0109 11:32:34.027101   87855 rpc.go:68] Marshaling property for RPC[Provider[kubernetes].Check(urn:pulumi:pyprovider::provider::kubernetes:core/v1:Pod::nginx).autonamedInputs]: pulumi.com/autonamed={true}
    I0109 11:32:34.027132   87855 rpc.go:68] Marshaling property for RPC[Provider[kubernetes].Check(urn:pulumi:pyprovider::provider::kubernetes:core/v1:Pod::nginx).autonamedInputs]: name={nginx-f9i7eb6i}
    I0109 11:32:34.027144   87855 rpc.go:68] Marshaling property for RPC[Provider[kubernetes].Check(urn:pulumi:pyprovider::provider::kubernetes:core/v1:Pod::nginx).autonamedInputs]: spec={map[containers:{[{map[ports:{[{map[containerPort:{80}]}]} image:{nginx:1.7.9} name:{nginx}]}]}]}
    I0109 11:32:34.027187   87855 rpc.go:68] Marshaling property for RPC[Provider[kubernetes].Check(urn:pulumi:pyprovider::provider::kubernetes:core/v1:Pod::nginx).autonamedInputs]: containers={[{map[ports:{[{map[containerPort:{80}]}]} image:{nginx:1.7.9} name:{nginx}]}]}
    I0109 11:32:34.027234   87855 rpc.go:68] Marshaling property for RPC[Provider[kubernetes].Check(urn:pulumi:pyprovider::provider::kubernetes:core/v1:Pod::nginx).autonamedInputs]: image={nginx:1.7.9}
    I0109 11:32:34.027247   87855 rpc.go:68] Marshaling property for RPC[Provider[kubernetes].Check(urn:pulumi:pyprovider::provider::kubernetes:core/v1:Pod::nginx).autonamedInputs]: name={nginx}
    I0109 11:32:34.027259   87855 rpc.go:68] Marshaling property for RPC[Provider[kubernetes].Check(urn:pulumi:pyprovider::provider::kubernetes:core/v1:Pod::nginx).autonamedInputs]: ports={[{map[containerPort:{80}]}]}
    I0109 11:32:34.027276   87855 rpc.go:68] Marshaling property for RPC[Provider[kubernetes].Check(urn:pulumi:pyprovider::provider::kubernetes:core/v1:Pod::nginx).autonamedInputs]: containerPort={80}
```

This is a little confusing - I would have expected the preview to fail if the cluster is not responding to network requests.

**Comment by swgillespie** [comment] 2019-01-09 21:15
Here's my setup, for additional context:

1. I used a first-class provider to reference a cluster that doesn't exist
2. I created a pod using that first-class provider
3. I did a preview

When performing the preview, the first-class provider creates successfully, and the pod also creates successfully after a 30 second delay. The preview outputs that there are two resources to create and completes without errors.

What's strange is that the provider clearly didn't communicate with the cluster at all, since the cluster doesn't exist. It is clear, though, that it did *try* to do so, since the logs indicate that the provider timed out after 30 seconds after trying to `GET https://146.148.15.185/openapi/v2`.

Based on the above logs, the provider returns a reasonable-looking Pod object, so the remainder of the preview proceeds fine - but I would expect the preview to fail since the update is almost certainly doomed to fail if there's no cluster to communicate with.

**Comment by hausdorff** [comment] 2019-01-09 21:16
That certainly _sounds_ like a bug. @lblackstone I tentatively assigned this to you since you're refactoring this and I don't want to interfere... lmk if this doesn't fit and we can load balance it back to me.

**Comment by lblackstone** [comment] 2019-01-17 00:03
@hausdorff I won't get to this in M20. We can punt, or you can take it if you have extra bandwidth.

**Comment by lblackstone** [comment] 2019-05-17 17:36
Still haven't had time to look into this, and the URN issues are higher priority now. Bumping from M23

**Comment by lblackstone** [comment] 2019-08-01 16:05
I wasn't able to reproduce this failure. I tested by creating a Deployment on a local cluster, and then disabling the cluster. Subsequent actions (previews, updates, destroys) fail because the provider can't connect to the k8s apiserver.

Closing since this appears to be fixed.

**Closed by lblackstone** 2019-08-01 16:05 UTC
Labels: area/resource-management, feature/q3, kind/bug
