### ISSUE TITLE
Helm reads wrong Kubeversion: >=1.22.0-0 for v1.26.0 as v1.20.0

### ISSUE THREAD

**Issue by re-thc** [pulumi/pulumi-kubernetes#2464] opened 2023-06-21 12:53 UTC
### What happened?

Tried adding cert-manager to kubernetes cluster on Linode (LIKE) using Pulumi Typescript but wrong KubeVersion is being used.

The deployed cluster version is v1.26.0 and not 1.20.0.

### Expected Behavior

Should be able to `preview` or `up` without problems.

### Steps to reproduce

Deploy any helm chart that has a kubernetes version requirement > 1.20.0, also check linked issue in additional context.

Only minor difference is using LKE instead of EKS.

### Output of `pulumi about`

See https://github.com/pulumi/pulumi-kubernetes/issues/2224#issuecomment-1593717486 for a reference. Using the same dependencies.

### Additional context

- Similar to https://github.com/pulumi/pulumi-kubernetes/issues/2224 
- Have ensured the latest version of helm, kubernetes, pulumi, pulumi-kubernetes and everything in the stack to rule it out
- This works directly with helm

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rshade** [comment] 2023-06-21 21:44
Can we get a copy of the code in a small repro if possible?

**Comment by rquitales** [comment] 2023-06-21 22:26
Hi @re-thc,

Thank you for reporting this issue, and we apologize for the difficulties you are experiencing. After investigating the problem, I was unable to reproduce the issue on my end using a v1.26 Linode Kubernetes cluster. However, I noticed that this issue arises when a malformed or empty kubeconfig is provided to the Pulumi Kubernetes provider. It is very possible that the underlying problem you are facing is related to the kubeconfig, rather than being a compatibility issue between our provider and Linode Kubernetes.

As mentioned by @rshade, it would be helpful if you could provide a code snippet that triggers this bug. Specifically, I am interested in how you are specifying the kubeconfig file and consuming it. This information will aid in further investigation and enable us to provide you with more targeted assistance.

---

Further information while I traced through this:

1. When kubeconfig parsing fails (due to it being empty, or malformed), we mark the cluster as unreachable but continue processing: https://github.com/pulumi/pulumi-kubernetes/blob/ba4ceff549a7c1be7180da1d4671f1c1f86c1bce/provider/pkg/provider/provider.go#L676
2. The kubernetes client sets are therefore not created, so we essentially are not communicating with any Kubernetes API Servers
3. Pulumi will continue progressing such that it will attempt to template the Helm charts, but since there is no cluster access, it uses the defaults when attempting to template the chart: https://github.com/pulumi/pulumi-kubernetes/blob/ba4ceff549a7c1be7180da1d4671f1c1f86c1bce/provider/pkg/provider/invoke_helm_template.go#L313-L316
4. Since we do not have cluster access, the underlying Helm package runs in [client only mode](https://github.com/helm/helm/blob/4e447d87cd3222aa5e5ea2b38170e9d80b99c0b4/pkg/action/install.go#L241-L244) and uses [its own specified defaults which is v1.20](https://github.com/helm/helm/blob/4e447d87cd3222aa5e5ea2b38170e9d80b99c0b4/pkg/chartutil/capabilities.go#L32-L35) resulting in the version range error

_To fix this issue, I believe we'd need to ensure that the kubeconfig is specified correctly._

**Comment by WP-LKL** [comment] 2023-06-22 07:33
Hi @rquitales, how are you using the kubeconfig provider for Linode?

**Comment by rquitales** [comment] 2023-06-22 18:42
@WP-LKL For the initial run, for above's investigations, I just created an LKE cluster from the Web Console, and downloaded and used the raw kubeconfig. However, I just repeated this using the Linode provider to provision the LKE cluster instead, and it's working fine.

Note: the kubeconfig returned by the Linode provider is base64 encoded, so we'll need to decode it before we can use it with the Kubernetes provider.

Here's a Typescript example:

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as k8s from "@pulumi/kubernetes";
import * as linode from "@pulumi/linode";

const my_cluster = new linode.LkeCluster("my-cluster", {
  k8sVersion: "1.26",
  label: "my-cluster",
  pools: [
    {
      count: 3,
      type: "g6-standard-2",
    },
  ],
  region: "us-central",
  tags: ["prod"],
});

export const kubeconfig_decoded = my_cluster.kubeconfig.apply((cfg) => {
  return Buffer.from(cfg, "base64").toString("ascii");
});

const provider = new k8s.Provider("linode_k8s", {
  kubeconfig: kubeconfig_decoded,
});

const ns = new k8s.core.v1.Namespace(
  "argocd",
  {
    metadata: {
      name: "argocd",
    },
  },
  { provider: provider }
);

const argo = new k8s.helm.v3.Release(
  "argocd",
  {
    chart: "argo-cd",
    namespace: ns.metadata.name,
    repositoryOpts: {
      repo: "https://argoproj.github.io/argo-helm",
    },
    values: {
      server: {
        service: {
          type: "LoadBalancer",
        },
      },
    },
  },
  { provider: provider, parent: ns }
);

```

**Comment by rquitales** [comment] 2023-06-26 16:13
I'll be closing this issue out as it seems like we have identified the root cause and provided a solution for this. Please feel free to reopen if this is not the case.

**Closed** 2023-06-26 16:14 UTC
Labels: kind/bug, resolution/wont-fix
