### ISSUE TITLE
pulumi.com/patchForce annotation is being ignored

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi-kubernetes#2629] opened 2023-10-24 20:43 UTC
### What happened?

When attempting to patch a resource in k8s using SSA and expecting it to patch the resource successfully based on the appropriate annotation, instead I receive an error that there is a conflict. 

### Example

```
_, err := appsv1.NewDaemonSetPatch(ctx, "nginx-image",
&appsv1.DaemonSetPatchArgs{
	Metadata: metav1.ObjectMetaPatchArgs{
		Name:      p.String("nginx-daemonset"),
		Annotations: p.StringMap{
			"pulumi.com/patchForce": p.String("true"),
		},
	},
	Spec: appsv1.DaemonSetSpecPatchArgs{
		Template: corev1.PodTemplateSpecPatchArgs{
			Spec: corev1.PodSpecPatchArgs{
				Containers: corev1.ContainerPatchArray{
					corev1.ContainerPatchArgs{
						Name:  p.String("nginx"),
						Image: p.String("nginx:alpine"),
					},
				},
			},
		},
	},
}, kubernetesProviderOption); err != nil {
return err
}
```

### Output of `pulumi about`

TODO

### Additional context

Error:
```
error: resource nginx-daemonset was not successfully created by the Kubernetes API server : Server-Side Apply field conflict detected. see https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/#handle-field-conflicts-on-existing-resources for troubleshooting help
: Apply failed with 2 conflicts: conflicts with "kubectl-client-side-apply" using apps/v1:
- .spec.template.spec.containers[name="nginx"].image
- .spec.template.spec.containers[name="nginx"].image
```

Worth noting setting the env `PULUMI_K8S_ENABLE_PATCH_FORCE` results in the patch working as expected.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by phillipedwards** [comment] 2023-10-24 20:47
Also the patchForce annotation seems to be ignored as well.

**Comment by zbuchheit** [comment] 2023-10-24 20:48
adjusted the title to be more accurate

**Comment by rquitales** [comment] 2023-10-24 22:31
Unfortunately I was not able to repro this locally. I've also codified and added a test each with our Go and Nodejs SDKs in #2630 which captures that the `pulumi.com/patchForce=true` annotation works as expected.

**Comment by lukehoban** [comment] 2023-11-21 13:58
We’ve had several folks try to reproduce, but have been unable to. Closing for now, please reopen if there is new information to aid in reproducing what if any issue exists here.

**Closed by lukehoban** 2023-11-21 13:58 UTC
Labels: kind/bug, awaiting-feedback, needs-repro, resolution/no-repro

**Comment by SharpEdgeMarshall** [comment] 2024-02-29 08:33
We ended up in the same situation: the annotation is ignored but the env var works, what information could we provide to help debug the issue?
SDK: Python
pulumi-kubernetes: 4.8.0
pulumi version: 3.107
`enable_server_side_apply=True` added to the provider resource

We are adding the annotation to a Helm Chart resource using a transformation like this:
```
def add_patchForce_annotation(obj, opts):
                annotations = obj["metadata"].setdefault("annotations", {})
                annotations["pulumi.com/patchForce"] = "true"
```

**Comment by SharpEdgeMarshall** [comment] 2024-03-05 16:06
We have been able to make it work, we were using Helm Chart transformations instead of pulumi.ResourceOptions transformations.
Maybe you should document better the difference between those 2 ways of applying transformations.
