### ISSUE TITLE
k8s.core.v1.Service.get doesn't return full information

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-kubernetes#614] opened 2019-06-28 17:17 UTC
The `k8s.core.v1.Service.get(...)` function returns only minimal information. I would expect the full details of the `Service`.

Below is an example output of exported `Namespace` and `Service` resources and their corresponding information via `Service.get(...)` and `Namespace.get(...)`. Note that  `Namespace.get(...)` returns "full" information about the namespace and `Service.get(...)` returns essentially nothing.

```
10:15:15 [gcp-ts-gke-hello-world] $ pulumi up -y
Previewing update (dev):

     Type                 Name                        Plan
     pulumi:pulumi:Stack  gcp-ts-gke-hello-world-dev

Resources:
    6 unchanged

Updating (dev):

     Type                 Name                        Status
     pulumi:pulumi:Stack  gcp-ts-gke-hello-world-dev

Outputs:
    namespace      : {
        apiVersion: "v1"
        id        : "helloworld-0ercixai"
        kind      : "Namespace"
        metadata  : {
            annotations      : {
                pulumi.com/autonamed: "true"
            }
            creationTimestamp: "2019-06-28T16:56:11Z"
            labels           : {
                app.kubernetes.io/managed-by: "pulumi"
            }
            name             : "helloworld-0ercixai"
            resourceVersion  : "584"
            selfLink         : "/api/v1/namespaces/helloworld-0ercixai"
            uid              : "a1ff3200-99c5-11e9-9c46-42010aa80093"
        }
        spec      : {
            finalizers: [
                [0]: "kubernetes"
            ]
        }
        status    : {
            phase: "Active"
        }
        urn       : "urn:pulumi:dev::gcp-ts-gke-hello-world::kubernetes:core/v1:Namespace::helloworld"
    }
    namespaceViaGet: {
        apiVersion: "v1"
        id        : "helloworld-0ercixai"
        kind      : "Namespace"
        metadata  : {
            annotations      : {
                pulumi.com/autonamed: "true"
            }
            creationTimestamp: "2019-06-28T16:56:11Z"
            labels           : {
                app.kubernetes.io/managed-by: "pulumi"
            }
            name             : "helloworld-0ercixai"
            resourceVersion  : "584"
            selfLink         : "/api/v1/namespaces/helloworld-0ercixai"
            uid              : "a1ff3200-99c5-11e9-9c46-42010aa80093"
        }
        spec      : {
            finalizers: [
                [0]: "kubernetes"
            ]
        }
        status    : {
            phase: "Active"
        }
        urn       : "urn:pulumi:dev::gcp-ts-gke-hello-world::kubernetes:core/v1:Namespace::namespaceViaGet"
    }
    service        : {
        apiVersion: "v1"
        id        : "helloworld-0ercixai/helloworld-nkz21brl"
        kind      : "Service"
        metadata  : {
            annotations      : {
                pulumi.com/autonamed: "true"
            }
            creationTimestamp: "2019-06-28T16:56:12Z"
            labels           : {
                app.kubernetes.io/managed-by: "pulumi"
                appClass                    : "helloworld"
            }
            name             : "helloworld-nkz21brl"
            namespace        : "helloworld-0ercixai"
            resourceVersion  : "852"
            selfLink         : "/api/v1/namespaces/helloworld-0ercixai/services/helloworld-nkz21brl"
            uid              : "a278d0f3-99c5-11e9-9c46-42010aa80093"
        }
        spec      : {
            clusterIP            : "10.31.255.183"
            externalTrafficPolicy: "Cluster"
            ports                : [
                [0]: {
                    nodePort  : 32208
                    port      : 80
                    protocol  : "TCP"
                    targetPort: "http"
                }
            ]
            selector             : {
                appClass: "helloworld"
            }
            sessionAffinity      : "None"
            type                 : "LoadBalancer"
        }
        status    : {
            loadBalancer: {
                ingress: [
                    [0]: {
                        ip: "35.235.91.128"
                    }
                ]
            }
        }
        urn       : "urn:pulumi:dev::gcp-ts-gke-hello-world::kubernetes:core/v1:Service::helloworld"
    }
    serviceViaGet  : {
        apiVersion: "v1"
        id        : "helloworld"
        kind      : "Service"
        urn       : "urn:pulumi:dev::gcp-ts-gke-hello-world::kubernetes:core/v1:Service::serviceViaGet"
    }

Resources:
    6 unchanged

Duration: 6s

Permalink: https://app.pulumi.com/clstokes/gcp-ts-gke-hello-world/dev/updates/14
```

Full repro code at https://gist.github.com/clstokes/8d820ac6755f9616b449dae7bb3f0de1.

**Comment by lblackstone** [comment] 2020-12-21 18:53
@clstokes I was unable to reproduce, and I think you may have been using the wrong `id` for the get call. Perhaps the preview was erroneously showing minimal output for a resource that doesn't actually exist?

Here's what the output looks like for me with the following modification:
```diff
- export const serviceViaGet = k8s.core.v1.Service.get("serviceViaGet", name, { provider: clusterProvider, });
+ export const serviceViaGet = k8s.core.v1.Service.get("serviceViaGet", pulumi.interpolate `${namespaceName}/${service.metadata.name}`, { provider: clusterProvider, });
```

```
serviceViaGet  : {
      + apiVersion: "v1"
      + id        : "helloworld-800re4rj/helloworld-sae0r829"
      + kind      : "Service"
      + metadata  : {
          + annotations      : {
              + kubectl.kubernetes.io/last-applied-configuration: "{\"apiVersion\":\"v1\",\"kind\":\"Service\",\"metadata\":{\"annotations\":{\"pulumi.com/autonamed\":\"true\"},\"labels\":{\"app.kubernetes.io/managed-by\":\"pulumi\",\"appClass\":\"helloworld\"},\"name\":\"helloworld-sae0r829\",\"namespace\":\"helloworld-800re4rj\"},\"spec\":{\"ports\":[{\"port\":80,\"targetPort\":\"http\"}],\"selector\":{\"appClass\":\"helloworld\"},\"type\":\"LoadBalancer\"}}\n"
              + pulumi.com/autonamed                            : "true"
            }
          + creationTimestamp: "2020-12-21T17:55:07Z"
          + finalizers       : [
          +     [0]: "service.kubernetes.io/load-balancer-cleanup"
            ]
          + labels           : {
              + app.kubernetes.io/managed-by: "pulumi"
              + appClass                    : "helloworld"
            }
          + name             : "helloworld-sae0r829"
          + namespace        : "helloworld-800re4rj"
          + resourceVersion  : "1217"
          + selfLink         : "/api/v1/namespaces/helloworld-800re4rj/services/helloworld-sae0r829"
          + uid              : "e752c2ba-7887-4bc9-ac34-00426770db37"
        }
      + spec      : {
          + clusterIP            : "10.7.254.26"
          + externalTrafficPolicy: "Cluster"
          + ports                : [
          +     [0]: {
                  + nodePort  : 30660
                  + port      : 80
                  + protocol  : "TCP"
                  + targetPort: "http"
                }
            ]
          + selector             : {
              + appClass: "helloworld"
            }
          + sessionAffinity      : "None"
          + type                 : "LoadBalancer"
        }
      + status    : {
          + loadBalancer: {
              + ingress: [
              +     [0]: {
                      + ip: "34.105.105.157"
                    }
                ]
            }
        }
      + urn       : "urn:pulumi:pulumi-k8s-test-dev::pulumi-k8s-test::kubernetes:core/v1:Service::serviceViaGet"
    }
```

**Comment by lblackstone** [comment] 2020-12-21 18:54
Closing this out now, but feel free to reopen if you're still seeing problems with the correct `id` provided.

**Closed by lblackstone** 2020-12-21 18:54 UTC
Labels: priority/P1
