### ISSUE TITLE
AWS ALB Ingress controller has spurious errors with SSL Redirection

### ISSUE THREAD

**Issue by adamhjk** [pulumi/pulumi-kubernetes#1359] opened 2020-10-23 21:14 UTC
### Problem description

With an AWS ALB Ingress controller configured to do SSL redirection, Pulumi Up reports a failure, due to the backend being invalid. (It isn't invalid, it's just specified by the annotation.)

### Errors & Logs

Working code, without a redirect:

```
export const ingressApi = new k8s.extensions.v1beta1.Ingress("internal-api", {
  metadata: {
    name: "internal-api-ingress",
    namespace,
    annotations: {
      "kubernetes.io/ingress.class": "alb",
      "alb.ingress.kubernetes.io/scheme": "internet-facing",
      "alb.ingress.kubernetes.io/certificate-arn": "arn:aws:acm:us-east-2:835304779882:certificate/75582463-9615-40b1-9d49-cbde7cf5abb3",
      "alb.ingress.kubernetes.io/listen-ports": '[{"HTTP": 80}, {"HTTPS":443}]',
      "alb.ingress.kubernetes.io/actions.ssl-redirect": '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}',
    },
    labels: {
      app: "internal-api-ingress",
    },
  },
  spec: {
    tls: [
      {
        hosts: [ "internal-api.tclown.com" ],
      },
    ],
    rules: [
      { 
        http: {
          paths: [
            //{ 
            //  path: "/*",
            //  backend: {
            //    serviceName: "ssl-redirect",
            //    servicePort: "use-annotation",
            //  },
            //},
            { 
              path: "/*",
              backend: {
                serviceName: "tclown-sdf-service",
                servicePort: 5156,
              },
            },
          ],
        },
      },
    ],
  }
}, { provider });
```

If you uncomment the ssl-redirect line, then you will see the error. If you abort Pulumi, you'll see that everything is working just fine.

### Affected product version(s)

At least 2.12.0.

### Suggestions for a fix

Unclear. The AWS ALB Ingress Controller works in a non-standard way, by hijacking the service configuration. It very well could be producing legitimate errors that just need to be ignored.

**Comment by jaxxstorm** [comment] 2020-10-24 00:44
hi @adamhjk !

what error gets thrown here? i'll try repro this (need to get the alb ingress controller set up first) - but my suspicion is that because the service associated with the ingress never actually registers healthy in a standard k8s way, the await logic returns an error.

Can you try adding `"pulumi.com/skipAwait": "true"` as an annotation to the ingress resource?

**Comment by blampe** [comment] 2024-07-26 23:04
Dupe of https://github.com/pulumi/pulumi-kubernetes/issues/408.

**Closed by blampe** 2024-07-26 23:04 UTC
Labels: kind/bug, resolution/duplicate, area/await-logic
