### ISSUE TITLE
Differentiate between "Created" and "Healthy"

### ISSUE THREAD

**Issue by ghostsquad** [pulumi/pulumi-kubernetes#1994] opened 2022-05-26 21:07 UTC
### What happened?

Went to deploy a `service`, and the object was valid and accepted by kubernetes, thus "created", but did not become healthy (expected for this test, as I didn't create a deployment). I tried to redeploy, and it failed to "create" the service, even though the service was created, but didn't become healthy.

### Steps to reproduce

```go
_, err = corev1.NewService(ctx, "hello-world", &corev1.ServiceArgs{
	Metadata: metav1.ObjectMetaArgs{
		Name:        pulumi.String("hello-world"),
		Namespace:   pulumi.String("default"),
	},
	Spec: &corev1.ServiceSpecArgs{
		Ports: &corev1.ServicePortArray{
			&corev1.ServicePortArgs{
				Port:       pulumi.Int(8080),
				TargetPort: pulumi.Int(8080),
			},
		},
		Selector: pulumi.ToStringMap(map[string]string{"app": "doesnotexist"}),
	},
}
```

### Expected Behavior

Since creation was successful, but health was not successful, I expected that the object showed up in state, and for health simply be re-evaluated.

### Actual Behavior

I subsequent run tried to "create" the service again, but failed.

```
resource hello-world was not successfully created by the Kubernetes API server : services "hello-world" already exists
```

### Versions used

```
❯ pulumi about
CLI
Version      3.33.1
Go Version   go1.17.10
Go Compiler  gc

Plugins
NAME        VERSION
aws         4.38.1
go          unknown
kubernetes  3.19.1

Host
OS       darwin
Version  12.3.1
Arch     x86_64

This project is written in go (/Users/wmcnamee/.asdf/shims/go v1.18.2 darwin/amd64)

Backend
<REDACTED>

NAME                                        VERSION
github.com/av-elier/go-decimal-to-rational  v0.0.0-20191127152832-89e6aad02ecf
github.com/pulumi/pulumi-aws/sdk/v4         v4.38.1
github.com/pulumi/pulumi-kubernetes/sdk/v3  v3.19.1
github.com/pulumi/pulumi/sdk/v3             v3.32.1
github.com/samber/lo                        v1.21.0
k8s.io/api                                  v0.24.0
k8s.io/apimachinery                         v0.24.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lblackstone** [comment] 2022-05-31 19:27
Hi @ghostsquad -- I wasn't able to reproduce the "already exists" error that you reported. I created the Service, which was created, but failed the default readiness checks. When I ran a subsequent update, Pulumi reported that it wanted to update the Service (so that the provider could wait for readiness).

On the topic of resource readiness, you can disable the check with the `pulumi.com/skipAwait: "true"` annotation on the resource, which would allow the scenario you're describing. You can check [the docs](https://www.pulumi.com/registry/packages/kubernetes/api-docs/core/v1/service/#service) for any k8s resource for more information about this logic. Note that disabling the readiness logic can lead to problems if you have other resources depending on this resource, since Pulumi will mark it ready as soon as it is created on the cluster, and output properties may not be initialized yet.

I'm going to close this issue as resolved, but let me know if the skipAwait solution isn't working for you.

**Closed by lblackstone** 2022-05-31 19:27 UTC
Labels: kind/bug, resolution/by-design

**Comment by ghostsquad** [comment] 2022-05-31 20:04
I'll try again and see what other variables I missed that caused this issue.
