### ISSUE TITLE
Nginx-Ingress install panic with helm.v3.Release

### ISSUE THREAD

**Issue by awopenphone** [pulumi/pulumi-kubernetes#2814] opened 2024-02-05 15:53 UTC
### What happened?

Trying to install ingress-nginx fails to complete successfully. 

### Example

After pulumi up I get this result:

```
const _ingressNamespace = new k8s.core.v1.Namespace(
  'ingress-nginx',
  { metadata: { name: 'ingress' } },
  { provider: k8sProvider },
);

const _ingressNginxRelease = new helm.v3.Release(
  'ingress-nginx',
  {
    namespace: _ingressNamespace.metadata.name,
    chart: 'ingress-nginx',
    repositoryOpts: { repo: 'https://kubernetes.github.io/ingress-nginx' },
    version: '4.9.1',
    valueYamlFiles: [new pulumi.asset.FileAsset('./charts/ingress-nginx/values.yaml')],
  },
  { provider: k8sProvider, dependsOn: [_ingressNamespace] },
)
```

```
     └─ kubernetes:helm.sh/v3:Release                                     ingress-nginx                                                                                          1 error

Diagnostics:
  kubernetes:helm.sh/v3:Release (redis):
    error: Preview failed: error reading from server: EOF

  kubernetes:helm.sh/v3:Release (ingress-nginx):
    error: error reading from server: EOF

  pulumi:pulumi:Stack (infra-eks-dev-charts-system):
    panic: interface conversion: interface {} is map[interface {}]interface {}, not map[string]interface {}
    goroutine 237 [running]:
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/provider.excludeNulls({0x10273f7e0?, 0x14001fb8780?})
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/helm_release.go:1322 +0x2d0
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/provider.excludeNulls({0x10273d920?, 0x14001fb8210?})
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/helm_release.go:1332 +0x214
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/provider.mergeMaps(0x14001fb8210, 0x14001fb8240?, 0x0)
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/helm_release.go:1309 +0xe4
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/provider.decodeRelease(0x10205f9dd?, {0x14001d599e0, 0x82})
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/helm_release.go:312 +0x338
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/provider.(*helmReleaseProvider).Check(0x14000f0d880, {0x102b64620, 0x14001fb8060}, 0x1400100f0e0)
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/helm_release.go:355 +0x3ac
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/provider.(*kubeProvider).Check(0x140006eb380, {0x102b64620, 0x14001fb8060}, 0x1400100f0e0)
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/provider.go:1295 +0xfb8
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Check_Handler.func1({0x102b64620, 0x14001fb8060}, {0x10296b360?, 0x1400100f0e0})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.101.1/proto/go/provider_grpc.pb.go:557 +0x74
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x102b64620, 0x14001f7de90}, {0x10296b360, 0x1400100f0e0}, 0x1400070cc40, 0x14001f49a28)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2e8
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Check_Handler({0x102ac5a00?, 0x140006eb380}, {0x102b64620, 0x14001f7de90}, 0x14001f78070, 0x14000a82680)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.101.1/proto/go/provider_grpc.pb.go:559 +0x12c
    google.golang.org/grpc.(*Server).processUnaryRPC(0x1400029a5a0, {0x102b72bc0, 0x140001e1860}, 0x14001fa4fc0, 0x140009bf920, 0x10438e2d0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:1374 +0xb44
    google.golang.org/grpc.(*Server).handleStream(0x1400029a5a0, {0x102b72bc0, 0x140001e1860}, 0x14001fa4fc0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:1751 +0x7cc
    google.golang.org/grpc.(*Server).serveStreams.func1.1()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:986 +0xb4
    created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 76
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:997 +0x160
```

### Output of `pulumi about`

❯ pulumi about    
CLI          
Version      3.104.2
Go Version   go1.21.6
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.20.1
awsx        2.5.0
docker      4.5.0
docker      3.6.1
kubernetes  4.7.1
nodejs      unknown

Host     
OS       darwin
Version  14.2.1
Arch     arm64
Dependencies:
NAME                VERSION
@types/node         18.19.7
jest                29.7.0
@pulumi/aws         6.20.1
@pulumi/awsx        2.5.0
@pulumi/kubernetes  4.7.1
@pulumi/pulumi      3.104.2
@swc/jest           0.2.29
@types/jest         29.5.11

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment] 2024-02-06 18:32
Looks like this is the same panic as the one you hit in https://github.com/pulumi/pulumi-kubernetes/issues/2684. As @rquitales suggested there, it looks like we're having trouble parsing your values file, so if you're able to share the contents of that file, that might help us reproduce.

**Comment by rquitales** [comment] 2024-02-08 01:26
Ah! I've just run into this issue coincidentally as well and am currently drafting a fix for this.

**Closed** 2024-02-09 21:05 UTC
Labels: kind/bug, awaiting-feedback, impact/panic
