### ISSUE TITLE
NamespacePatch - Resource already exists

### ISSUE THREAD

**Issue by SoJoh** [pulumi/pulumi-kubernetes#2194] opened 2022-09-29 06:36 UTC
### What happened?

Whenever I'm using it to patch an existing namespace, pulumi will fail, telling me that this resource already exists. This seems to be the whole point of that resource, to be applied if the namespace does already exist. The namespace to be mutated is created by the same provider.
If I use the NamespacePatch for a namespace name that does not exist already, this namespace is created by it.

### Steps to reproduce

1. Create a namespace like this
```
this.gitlabRunnerNamespace = new k8s.core.v1.Namespace(
            cluster.name + "-eks-gitlab-runner-" + suffix,
            {
                metadata: {
                    name: "gitlab-runner" + suffix,
                    labels: {
                        "openpolicyagent.org/webhook": "ignore"
                    }
                }
            },
            {
                provider: cluster.asfEksCluster.provider
            }
        );
```
2. ``` pulumi up ``` 
3. After some time I came back, enabled SSA and added the patch resource (in another package, that's why the variable names differ). This package is imported to the main script. 
```
this.namespacePatch = new k8s.core.v1.NamespacePatch(
                namespaceName + "-patch", {metadata: {
                        name: namespaceName, // same namespace name as for namespace from step 1
                        annotations: {
                            "pulumi.com/patchForce" : "true"
                        },
                        labels: {
                            "my-annotation": "disabled"
                        }
                    }}, {
                    provider: dawOptions.k8sProvider // Is the same provider as during namespace creation in step 1 
                })
            );
``` 
4. ``` pulumi up```

```
 +  kubernetes:core/v1:NamespacePatch gitlab-runner-0-patch create 
 +  kubernetes:core/v1:NamespacePatch gitlab-runner-0-patch creating 
 +  kubernetes:core/v1:NamespacePatch gitlab-runner-0-patch creating error: resource default/gitlab-runner-0 was not successfully created by the Kubernetes API server : namespaces "gitlab-runner-0" already exists
 ```

### Expected Behavior

- Pulumi should patch the resource because it already exists. It should not try to create it.

### Actual Behavior

``` 
+  kubernetes:core/v1:NamespacePatch gitlab-runner-0-patch creating error: resource default/gitlab-runner-0 was not successfully created by the Kubernetes API server : namespaces "gitlab-runner-0" already exists 
```

### Additional context

We are using a packaging approach. 
The patch resides in another package than the resource to create the namespace.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iridian-ks** [comment] 2023-01-04 23:48
I know this could be unhelpful, but I'm getting the same issue with DaemonSetPatch.

```
 +   └─ kubernetes:apps/v1:DaemonSetPatch  ekslab/aws-node-patch  **creating failed**     1 error


Diagnostics:
  kubernetes:apps/v1:DaemonSetPatch (eks-lab/aws-node-patch):
    error: resource kube-system/aws-node was not successfully created by the Kubernetes API server : daemonsets.apps "aws-node" already exists
```

Agree with the original author, the entire point of Patch is to update an existing resource so unclear why an error message like this is even in the code path.

**Comment by lblackstone** [comment] 2023-01-05 22:50
@iridian-ks Can you provide reproduction steps for this error? I wasn't able to trigger it locally when I looked into this previously. As you note, the point of Patch resources is to modify existing resources, so this is likely a bug.

**Comment by lblackstone** [comment] 2023-07-13 18:11
Closing this out since we didn't get a repro. We can reopen if additional information is available.

**Closed by lblackstone** 2023-07-13 18:11 UTC
Labels: kind/bug, awaiting-feedback, resolution/no-repro, area/server-side-apply
