### ISSUE TITLE
Error updating Helm Chart values: failed to fully initialize or become live: the body of the request was in an unknown format   

### ISSUE THREAD

**Issue by brpaz** [pulumi/pulumi-kubernetes#1077] opened 2020-04-18 11:20 UTC
### Problem description

Hello. I have installed [Velero](https://velero.io/) to back up my k8s cluster with Pulumi and the official helm chart.

Velero have a Custom Resource Definiton to create Backup Scheules and that can be defined in the Helm values file as such:

```js
values: {
   schedules: {
        clusterbackup: {
          schedule: "30 2 * * *",
          snapshotVolumes: true,
          template: {
            excludedNamespaces: ["velero", "kube-system"],
          },
        },
      },
}
```

Everything works fine when I create a Schedule, but If I try to update some value I got the error below.

Not sure if it´s an issue of Pulumi or Helm itself.

### Errors & Logs

```
 * the Kubernetes API server reported that "velero/velero-clusterbackup" failed to fully initialize or become live: the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json, application/apply-patch+yaml
```
### Affected product version(s)

Pulumi 1.14
Pulumi Kubernetes: 1.6.0
Kubernetes Version: 1.16

**Comment by lblackstone** [comment] 2020-04-20 16:33
This is probably the same issue as #1061

**Comment by joeduffy** [comment] 2020-08-12 00:51
@lblackstone @metral I am hitting this issue trying to provision the fluent-bit Helm chart: https://hub.helm.sh/charts/fluent/fluent-bit. Since #1061 is marked fixed, is this a different root cause?

**Comment by joeduffy** [comment] 2020-08-12 00:52
(Even stranger, I then tore down the stack, and retried, and everything came up quickly.)

**Comment by manast** [comment] 2020-08-14 12:51
@brpaz do you mind to share the code you used for deploying velero with pulumi? I have no issues to deploy it manually using helm, but with pulumi I have been struggling for days without look. I am using the latest version of Pulumi (2.8.2) and one of the errors I cannot get rid of is:
```    manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
    manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
    manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
    manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
    manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
    manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
    manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
    manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
    manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
    manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
    manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
```
Not sure if that is the reason why the pods never manages to get ready either... I deploy my chart with this code:
```ts
const velero = new k8s.helm.v3.Chart(
      "velero",
      {
        repo: "vmware-tanzu",
        chart: "velero",
        // version: "2.21.2",
        values: {
          configuration: {
            provider: "gcp",
            backupStorageLocation: {
              name: "default",
              bucket: bucket.id.apply((id) => id),
            },
          },
          volumeSnapshotLocation: {
            name: "default",
            config: {
              snapshotLocation: gcp.config.region,
            },
          },
          image: {
            repository: "velero/velero",
            tag: "v1.4.2",
            pullPolicy: "IfNotPresent",
          },
          initContainers: [
            {
              name: "velero-plugin-for-gcp",
              image: "velero/velero-plugin-for-gcp:v1.1.0",
              volumeMounts: [
                {
                  mountPath: "/target",
                  name: "plugins",
                },
              ],
            },
          ],
          credentials: {
            existingSecret: serviceAccountSecretVelero.id.apply((id) => id),
          },
          deployRestic: true,
        },
        namespace: veleroNamespace.id.apply((id) => id),
      },
      {
        providers: { kubernetes: provider },
        parent: this,
        dependsOn: [bucket, serviceAccountSecretVelero, veleroNamespace],
      }
    );
  }
```

**Comment by lblackstone** [comment] 2022-12-21 20:51
We have fixed a bunch of Helm bugs in the provider since this issue was active, and also added the [helm.v3.Release](https://www.pulumi.com/registry/packages/kubernetes/api-docs/helm/v3/release/) resource now, so I'm going to close this out. Please open a new issue if you're encountering this problem on recent versions of the provider.

**Closed by lblackstone** 2022-12-21 20:51 UTC
Labels: kind/bug, resolution/no-repro
