### ISSUE TITLE
Cannot upgrade helm charts that change from extensions/v1beta1/Deployment to apps/v1/Deployment

### ISSUE THREAD

**Issue by nesl247** [pulumi/pulumi-kubernetes#624] opened 2019-07-08 20:50 UTC
I was trying to upgrade external-dns from 1.7.x to 2.1.1, and it failed. It fails because they upgrade the from `Deployment` in `extensions/v1beta1` to `apps/v1`. Pulumi does not detect the conflict and delete the original deployment first.

**Comment by lblackstone** [comment] 2019-07-09 23:34
Closing as duplicate of #573 

See https://github.com/pulumi/pulumi-kubernetes/issues/546#issuecomment-497909547 for a workaround

**Closed by lblackstone** 2019-07-09 23:34 UTC
