### ISSUE TITLE
PR was auto-merged despite test failure

### ISSUE THREAD

**Issue by thomas11** [pulumi/pulumi-kubernetes#2303] opened 2023-02-07 19:45 UTC
### Problem description

#2301 was set to auto-merge (squash) and was merged even though its CI run had [a failure](https://github.com/pulumi/pulumi-kubernetes/actions/runs/4108442549/jobs/7089297963).

Branch protection configuration at the time:
<img width="800" alt="Screenshot 2023-02-07 at 12 18 44 PM" src="https://user-images.githubusercontent.com/12074/217358520-7806240a-c406-4d11-928b-df734182dc44.png">

**Comment by t0yv0** [comment] 2023-02-13 22:25
I've looked at this briefly. I think you're correct in that for this to work, every test step must be in Required Checks! Otherwise automerge just proceeds. Sentinel depending on the test matrix does not seem to help it figure out it shouldn't proceed.

We have this bit of infra where we supposedly manage branch protections:

https://github.com/pulumi/ci-mgmt/blob/master/infra/providers/index.ts

Notices that @danielrbradley PR https://github.com/pulumi/ci-mgmt/pull/301 this has changed to include all the "test" workflows as required checks for every language.

It seems that it's there but we couldn't quite roll it out since it's all-or-nothing and some providers haven't caught up with ci-mgmt yet, plus there's permissions issues.

**Comment by t0yv0** [comment] 2023-02-13 22:26
A few ways forward:

- Option A can set the required checks manually in pulumi-kubernetes

- Option B can sync branch protections to ci-mgmt across the entire set of repos! For repos that haven't updated targets to the new ci-mgmt yet, it would mean branch protections now list non-existent CI steps. We can fix that case-by-case by manually editing those, I don't think there's going to be a lot of providers.

- Any more ideas?

**Comment by t0yv0** [comment] 2023-02-17 20:40
The root cause should be fixed now. Branch protections have synced https://github.com/pulumi/ci-mgmt/actions/runs/4207151571/jobs/7301581877 via ci-mgmt for Kubernetes, and now list out test steps explicitly. I believe this fixes the root cause here.

**Closed** 2023-02-17 20:40 UTC
Labels: kind/bug, kind/engineering, resolution/fixed
