### ISSUE TITLE
Enabling SSA errors when working with ECK

### ISSUE THREAD

**Issue by KaoruDev** [pulumi/pulumi-kubernetes#2139] opened 2022-08-15 19:19 UTC
### What happened?

Received an error:

```
  kubernetes:elasticsearch.k8s.elastic.co/v1:Elasticsearch (family):
    error: error reading from server: EOF
    panic: fatal: An assertion has failed: path: [spec nodeSets 0 podTemplate metadata creationTimestamp]  |  v: <nil>  | old: <nil>  |  oldInput: <nil>
    goroutine 231 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.37.1/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0x80?, {0x2289b8c?, 0x8?}, {0xc002985668?, 0xc002fe5620?, 0x1dd52e0?})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.37.1/go/common/util/contract/assert.go:33 +0xed
    github.com/pulumi/pulumi-kubernetes/provider/v3/pkg/provider.(*patchConverter).addPatchValueToDiff(0xc0029
```

When I tried to update an `elasticsearch` object after turnning on `enableServerSideApply`

I see something similar with the CRDs:

```
  kubernetes:apps/v1:StatefulSet (elastic-system/elastic-operator):
    error: Preview failed: 1 error occurred:
        * the Kubernetes API server reported that "elastic-system/elastic-operator" failed to fully initialize or become live: use `pulumi.com/patchForce` to override the conflict: Apply failed with 4 conflicts: conflicts with "pulumi-resource-kubernetes" using apps/v1:
    - .spec.template.spec.containers[name="manager"].env[name="OPERATOR_NAMESPACE"].valueFrom.fieldRef
    - .spec.template.spec.containers[name="manager"].env[name="POD_IP"].valueFrom.fieldRef
    - .spec.template.spec.containers[name="manager"].resources.requests.cpu
    - .spec.template.spec.containers[name="manager"].resources.requests.cpu
```

### Steps to reproduce

1. Create a provider with `enableServerSideApply` omitted.
2. Deploy ECK's CRDs via `k8s.yaml` from  https://download.elastic.co/downloads/eck/2.1.0/crds.yaml and operator: `https://download.elastic.co/downloads/eck/2.1.0/operator.yaml`
3. Run Pulumi up
4. Set `enableServerSideApply` to `true`, run again and see errors.

### Expected Behavior

Make switch seemingless.

### Actual Behavior

Error gets thrown

### Versions used

CLI
Version      3.33.2
Go Version   go1.17.10
Go Compiler  gc

Host
OS       ubuntu
Version  20.04
Arch     x86_64

`@pulumi/kubernetes` is at `3.20.3`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by KaoruDev** [comment] 2022-08-15 20:04
Updated ECK to `2.3.0` and no dice still have the same problem 😞

**Comment by lblackstone** [comment] 2022-08-16 21:18
I wasn't able to reproduce the panic, but the second error is a validation error that can be resolved with `patchForce`. Since the resources were created with a different manager, you need to explicitly force the apply as stated in the error message. Here's an example that worked for me:

```ts
// Create a Provider with SSA enabled.
const provider = new k8s.Provider("k8s", {
    enableServerSideApply: true,
});

new k8s.yaml.ConfigGroup("test", {
    files: ["crds.yaml", "operator.yaml"],
    transformations: [
        // Add the "patchForce" annotation to take ownership of the resources with SSA.
        (obj: any, opts: pulumi.CustomResourceOptions) => {
            if (obj.metadata.annotations) {
                obj.metadata.annotations["pulumi.com/patchForce"] = "true"
            } else {
                obj.metadata.annotations = {"pulumi.com/patchForce": "true"}
            }
        },
    ]
}, {provider})
```

**Comment by lblackstone** [comment] 2022-09-22 18:56
Any further problems here, or can this issue be closed out?

**Comment by KaoruDev** [comment] 2022-09-23 18:44
I'm sorry for the lack of response,  here things have been backed up, let's
close this for now and I'll circle back with my results. Thank you!

**Closed** 2022-11-14 23:37 UTC
Labels: kind/bug, resolution/no-repro, area/server-side-apply

**Comment by KaoruDev** [comment] 2023-02-16 13:24
You're snippet worked! Thank you very much @lblackstone !

**Comment by same-id** [comment] 2023-04-23 04:49
@lblackstone 

I had the same problem with a Helm Chart which I solve with the following snippet (Golang), which took me some time to brew since I had to double click on `helm.NewChart` follow through the code to `parseChart` look at the transformations code there, specifically there is:
```
	if args.SkipAwait {
		transformations = yaml.AddSkipAwaitTransformation(transformations)
	}
```

And then make my own:

```
               Transformations: []func(state map[string]interface{}, opts ...pulumi.ResourceOption){
                       func(obj map[string]interface{}, opts ...pulumi.ResourceOption) {
                               metadata := obj["metadata"].(map[string]interface{})
                               if annotations, ok := metadata["annotations"].(map[string]interface{}); ok {
                                       annotations["pulumi.com/patchForce"] = "true"
                               } else {
                                       metadata["annotations"] = map[string]string{"pulumi.com/patchForce": "true"}
                               }
                       },
               },
```

Then I found this hidden issue on GitHub - and understood that I could have solve it much faster had I found it before.

I think this has to be promoted to either:
1. Add `args.patchForce` just like `skipAwait` because either-wise this snippet has to be guessed
2. Add this to https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/#helm-charts

Hope it will help other folks
