### ISSUE TITLE
Panic on non-string `kubeconfig`

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-kubernetes#1032] opened 2020-03-15 20:12 UTC
A user reported the panic below.  This appears to be due to the `kubeconfig` property being set to something other than a string, and a call to `.StringValue()` panicing.  

In general, there are a lot of calls to `.StringValue()` and similar in this package that are not guarded with `.IsString()` checks and are thus likely to panic instead of cleanly error on malformed inputs.  We likely should audit (and test) these more holistically.

```
    panic: interface conversion: interface {} is resource.PropertyMap, not string
    goroutine 28 [running]:
    github.com/pulumi/pulumi/pkg/resource.PropertyValue.StringValue(...)
    	/home/travis/gopath/pkg/mod/github.com/pulumi/pulumi@v1.6.1/pkg/resource/properties.go:359
    github.com/pulumi/pulumi-kubernetes/pkg/provider.parseKubeconfigPropertyValue(0x2386280, 0xc0001fea50, 0x2475423, 0xa, 0xc0001b2508)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/pkg/provider/util.go:85 +0x169
    github.com/pulumi/pulumi-kubernetes/pkg/provider.(*kubeProvider).DiffConfig(0xc000014000, 0x26e1260, 0xc0001fe9f0, 0xc0001380e0, 0xc000014000, 0x2275301, 0xc00031a0c0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/pkg/provider/provider.go:278 +0x61b
    github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_DiffConfig_Handler.func1(0x26e1260, 0xc0001fe9f0, 0x23a5e80, 0xc0001380e0, 0x23c0a00, 0x33070c0, 0x26e1260, 0xc0001fe9f0)
    	/home/travis/gopath/pkg/mod/github.com/pulumi/pulumi@v1.6.1/sdk/proto/go/provider.pb.go:1504 +0x86
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x26e1260, 0xc000577200, 0x23a5e80, 0xc0001380e0, 0xc00000cb20, 0xc00000cb40, 0x0, 0x0, 0x26a05e0, 0xc0000cf7b0)
    	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20171105060200-01f8541d5372/go/otgrpc/server.go:61 +0x36e
    github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_DiffConfig_Handler(0x2402f60, 0xc000014000, 0x26e1260, 0xc000577200, 0xc0000de3c0, 0xc0004d2040, 0x26e1260, 0xc000577200, 0xc000331300, 0x101f)
    	/home/travis/gopath/pkg/mod/github.com/pulumi/pulumi@v1.6.1/sdk/proto/go/provider.pb.go:1506 +0x14b
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc00034e300, 0x26fdc00, 0xc00045b500, 0xc00015a200, 0xc000436180, 0x32d3258, 0x0, 0x0, 0x0)
    	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:998 +0x46a
    google.golang.org/grpc.(*Server).handleStream(0xc00034e300, 0x26fdc00, 0xc00045b500, 0xc00015a200, 0x0)
    	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:1278 +0xd97
    google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00039bd30, 0xc00034e300, 0x26fdc00, 0xc00045b500, 0xc00015a200)
    	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:717 +0xbb
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:715 +0xa1
```

**Comment by metral** [comment] 2020-03-24 21:50
This occurs when the kubeconfig used in the k8s provider is not stringified, and instead is passed as an object of `Output<t>`.

The workaround is to use a string

```
const kubeconfig = cluster.kubeconfig.apply(JSON.stringify)
const provider = new k8s.Provider("provider", {kubeconfig: kubeconfig});
```

Related: https://github.com/pulumi/pulumi-eks/issues/359

**Comment by lukehoban** [comment] 2020-03-25 15:30
We should do one or both of:
1. Have a better error message here (type check in our code, not let this get through to serialization code to report the error).
2. Actually support `string | object` here, and JSON-stringify an object input.  I'm not exactly sure what this looks like in a purely cross-platform compatible form, and it's likely something we want to solve for as a general schema model concept.

**Comment by EronWright** [comment] 2024-01-27 01:23
Closing this as a duplicate of #1231, which was resolved by adding support for an object-typed resource value.

**Closed** 2024-01-27 01:24 UTC
Labels: kind/bug, resolution/duplicate, impact/panic
