### ISSUE TITLE
StatefulSet replaced unexpectedly.

### ISSUE THREAD

**Issue by timmyers** [pulumi/pulumi-kubernetes#619] opened 2019-07-03 18:06 UTC
`StatefulSets` are replaced for simple changes to the template spec.  This causes the entire `StatefulSet` to be replaced, instead of just updated triggering a rolling deploy of the `Pods`.

New `PVC`s result, and the entire point of a `StatefulSet1 is destroyed.

Example:
```typescript
const sstest = new k8s.apps.v1.StatefulSet('sstest', {
    metadata: {
      namespace: namespace.metadata.name,
    },
    spec: {
      selector: {
        matchLabels: {
          app: 'sstest',
        },
      },
      serviceName: 'sstest',
      replicas: 1,
      template: {
        metadata: {
          labels: {
            app: 'sstest',
          },
        },
        spec: {
          containers: [{
            name: 'sstest',
            image: 'nginx',
            imagePullPolicy: 'Always',
            resources: {
              requests: {
                cpu: '250m',
                memory: '512Mi',
              },
            },
            volumeMounts: [{
              name: 'db',
              mountPath: '/data',
              readOnly: false,
            }],
          }],
        },
      },
      volumeClaimTemplates: [{
        metadata: {
          name: 'db',
        },
        spec: {
          accessModes: ['ReadWriteOnce'],
          resources: {
            requests: {
              storage: '1Gi',
            },
          },
          storageClassName: 'gp2',
        },
      }],
    },
  }, defaultOpts)
```

Once this is applied:
```
❯ ktl get statefulset
NAME              READY   AGE
sstest-fph5jvef   1/1     5m42s

❯ ktl get pvc
NAME                   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
db-sstest-fph5jvef-0   Bound    pvc-07ff4749-9dbc-11e9-ae2c-12d97a56d4ba   1Gi        RWO            gp2            6m8s
```

Update the cpu request in the template to `350m`:
```
❯ pulumi up
Previewing update (main):

     Type                            Name            Plan        Info
     pulumi:pulumi:Stack             lightning-main              
 +-  └─ kubernetes:apps:StatefulSet  sstest          replace     [diff: ~spec]
 
Resources:
    +-1 to replace
    6 unchanged

Do you want to perform this update? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:main::lightning::pulumi:pulumi:Stack::lightning-main]
    > pulumi:pulumi:StackReference: (read)
        [id=dev]
        [urn=urn:pulumi:main::lightning::pulumi:pulumi:StackReference::infrastructure]
        name: "dev"
        --outputs:--
        outputs: {
            kubeConfig: "{\"apiVersion\":\"v1\",\"kind\":\"Config\",\"clusters\":[{\"cluster\":{\"server\":\"https://38AF9757E9F7108601C8D138BE9C94C0.yl4.us-east-1.eks.amazonaws.com\",\"certificate-authority-data\":\"LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1ETXdPREUxTWpFMU5Wb1hEVEk1TURNd05URTFNakUxTlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXhQClhxVFBCWkdMcWpQeEVVMEhlN3d5b2xhdi82QVFZOUNQaUtPNER6eStNTkJZSWhGQkhTQjlvelZKb29WdHozbTYKTGJ4dnFRK21ReWwvNURnM3A1akRrR1NJbVdMaDJYQnFYejhBNHRoNG83Qm80V2VSOUZsY1BPR2R0NHdIL1dsUApyTDh1ZHEwTjJqMFI1QnVvS2VOSXBleVBVbm5PVitDekZhS0sxU0d0NDJLTysxeXc0MDhRNUo4TzhzK3g0THhSClVHYkQxZXZlamZZN1NadGpYWmFabnBKbUJuRVpQV0N1eWdESTArdUNKMU5xcGFwMnJ0cUxiTmFnOVNXV1JTM2sKTU1iOVo4TktUQk9hbVlnb0IyRmRuSDMzZVZXNmFabFRQaTUvNzNPc3ladVRtQTJpWXE5bXp2WTl6Tkg3Wm04egpGK01lVEErRHNmSmllb3hpQi9jQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFKY044Q2trUmlnZkNxaisyZ1FXZ1d6UWYybW8KWWI5OWVwbUNkNWhRZ0JaOWw0WWxsVHJwWVVRQXAzOW1nb2hoQ1B6Wklra3JiS3pKMmRzYkcyb2ptRTk2UGZxSApZSm9mZTFLaFg1QlpRVGEwTm9FdmdJa2JkazV6T1JPUTBtZUJrMVcxN0Z5bmlMNCttbzl4SnhJaVc4RTQ4WG1mCmlOTTR2UGxKTWZ4OS9NNkczTEVvcmZETXJ1MjNRMmdDNlFTT2hJQ3JHbmdiZWlZUnhFQkxHTnVlSHFUVTlhaFYKN0txOHJHWk44MUhlQlRUOGFJNzF4VE0xTzNnRjEwSFRYSGZTWWYxS3FLT2YxVjBlRm8wcEgrcXRqcTRoTHdadgpJU2NrYW0rY0FVRjJxOXBSUCsyWHRxbEtlaW45blNzL3AwcHNwQUl1MU5lTVVadjFMSmtVRVhnMDRLdz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=\"},\"name\":\"kubernetes\"}],\"contexts\":[{\"context\":{\"cluster\":\"kubernetes\",\"user\":\"aws\"},\"name\":\"aws\"}],\"current-context\":\"aws\",\"users\":[{\"name\":\"aws\",\"user\":{\"exec\":{\"apiVersion\":\"client.authentication.k8s.io/v1alpha1\",\"command\":\"aws-iam-authenticator\",\"args\":[\"token\",\"-i\",\"infrastructure\"]}}}]}"
        }
    ++kubernetes:apps/v1:StatefulSet: (create-replacement)
        [id=lightning/sstest-fph5jvef]
        [urn=urn:pulumi:main::lightning::kubernetes:apps/v1:StatefulSet::sstest]
        [provider=urn:pulumi:main::lightning::pulumi:providers:kubernetes::infrastructure::4ae1f6ee-c651-431e-ab0d-8123dd853a0e]
      ~ spec: {
          ~ template            : {
              ~ spec    : {
                  ~ containers: [
                      ~ [0]: {
                              ~ resources      : {
                                  ~ requests: {
                                      ~ cpu   : "250m" => "350m"
                                    }
                                }
                            }
                    ]
                }
            }
        }
    +-kubernetes:apps/v1:StatefulSet: (replace)
        [id=lightning/sstest-fph5jvef]
        [urn=urn:pulumi:main::lightning::kubernetes:apps/v1:StatefulSet::sstest]
        [provider=urn:pulumi:main::lightning::pulumi:providers:kubernetes::infrastructure::4ae1f6ee-c651-431e-ab0d-8123dd853a0e]
      ~ spec: {
          ~ template            : {
              ~ spec    : {
                  ~ containers: [
                      ~ [0]: {
                              ~ resources      : {
                                  ~ requests: {
                                      ~ cpu   : "250m" => "350m"
                                    }
                                }
                            }
                    ]
                }
            }
        }
    --kubernetes:apps/v1:StatefulSet: (delete-replaced)
        [id=lightning/sstest-fph5jvef]
        [urn=urn:pulumi:main::lightning::kubernetes:apps/v1:StatefulSet::sstest]
        [provider=urn:pulumi:main::lightning::pulumi:providers:kubernetes::infrastructure::4ae1f6ee-c651-431e-ab0d-8123dd853a0e]
```

After applying:
```
❯ ktl get statefulset
NAME              READY   AGE
sstest-sof9wx8u   1/1     48s
❯ ktl get pvc
NAME                   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
db-sstest-fph5jvef-0   Bound    pvc-07ff4749-9dbc-11e9-ae2c-12d97a56d4ba   1Gi        RWO            gp2            8m50s
db-sstest-sof9wx8u-0   Bound    pvc-1f97e6d8-9dbd-11e9-ae2c-12d97a56d4ba   1Gi        RWO            gp2            61s

**Comment by lblackstone** [comment] 2019-07-03 18:17
Yeah, this looks like an oversight in our k8s provider. Even if we do replace the StatefulSet, the PV should definitely not change.

/cc @hausdorff

**Comment by timmyers** [comment] 2019-07-03 18:19
I would think replacing the `StatefulSet` in cases like this would also be pretty unfortunate even if it he PV's stayed the same.

**Comment by hausdorff** [comment] 2019-07-25 19:06
I can't reproduce this. What version of the provider are you using, @timmyers ?

**Comment by timmyers** [comment] 2019-07-25 23:51
I'm using `"@pulumi/kubernetes": "0.25.2"`.

**Comment by timmyers** [comment] 2019-07-25 23:52
It also seems that this bug in conjunction with https://github.com/pulumi/pulumi-kubernetes/issues/644 is causing my statefulsets to be replaced on any `apply` operation.

**Comment by hausdorff** [comment] 2019-08-07 18:06
@timmyers reports that this was fixed in one of the recent releases. We'll close for now, but let's re-open if the issue re-appears.

**Closed by hausdorff** 2019-08-07 18:06 UTC
Labels: area/await-logic, area/community, area/resource-management, feature/q3, kind/bug, priority/P1
