### ISSUE TITLE
Generate separate files for each input/output type

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-kubernetes#888] opened 2019-11-22 19:42 UTC
For TypeScript and C#, we currently generate very large `input.ts` and `output.ts` files with all types.  We should break these up into individual files per class.

**Comment by lblackstone** [comment] 2023-07-13 18:43
This isn't specific to pulumi-kubernetes, so I'm going to close as a duplicate of https://github.com/pulumi/pulumi/issues/11668

**Closed by lblackstone** 2023-07-13 18:43 UTC
Labels: kind/enhancement, resolution/duplicate
