### ISSUE TITLE
Support helm.Chart with helm hooks

### ISSUE THREAD

**Issue by gobengo** [pulumi/pulumi-kubernetes#555] opened 2019-05-04 16:58 UTC
Pulumi program: https://gist.github.com/gobengo/590a88e3b951fa3f66c8d8e963bf34a0

I am trying to use the latest wordpress chart (version 5.9.0) to test out pulumi-kubernetes' `helm.Chart`. The pulumi kubernetes docs for helm use a much earlier one.

```
const wordpressChart = new k8s.helm.v2.Chart(`${namespaceName}-wordpress`, {
	namespace: namespaceName,
	repo: "stable",
	version: "5.9.0",
	chart: "wordpress",
	transformations: [
		addNamespaceTransformation(namespaceName),
		removeHelmHooksTransformation()
	]
});
```

However, when I `pulumi up`, it ends up failing because this helm chart includes [a `helm.sh/hook: test-success` annotation](https://github.com/helm/charts/blob/master/stable/wordpress/templates/tests/test-mariadb-connection.yaml). The mariadb chart it composes has [a test hook](https://github.com/helm/charts/blob/master/stable/mariadb/templates/test-runner.yaml) as well, so there are two that fail.

Pulumi seems to be unaware of hook semantics (understandable). The end result is that the hook pods get created at the same time (sometimes) before the app Pods they depend on (i.e. mariadb), and so they fail with exit code 1, which causes the pulumi deployment to fail as well.

I was able to work around this by providing a transformation created with
```typescript
function removeHelmHooksTransformation() {
	return (o: any) => {
		if ( ! o) return
		if (o.metadata && o.metadata.annotations && o.metadata.annotations['helm.sh/hook']) {
			console.log('skipping helm hook', o.metadata)
			// transforms in nodejs expects you to mutate input object, not return a new one :/
			// https://github.com/pulumi/pulumi-kubernetes/blob/4b01b5114df3045cecefd2ff3e2f2ed64430e3dd/sdk/nodejs/yaml/yaml.ts#L2214
			for (const key in o) {
				delete o[key]
			}
			Object.assign(o, {
				kind: "List",
				apiVersion: "v1",
				metadata: {},
				items: [],
			})
			return
		}
		return o
	}
}
```

Ideally, pulumi-kubernetes would be aware of helm hook semantics and would, e.g., wait for other Pods to be deployed and ready before creating Pods with the `helm.sh/hook: test-success` annotation. In lieu of full semantic support, it would be nice to maybe just not deploy pods with that annotation at all (and warn with a link to this issue or a more appropriate one).

**Comment by gobengo** [comment] 2019-05-04 18:07
Worth noting that https://github.com/pulumi/pulumi-kubernetes/issues/511 would be at least some way of supporting these charts without modification, but ofc with the overhead of running and configuring Tiller securely.

**Comment by hausdorff** [comment] 2019-07-13 04:55
This might involve a helm provider proper. Should we do this now, or should we be waiting for Helm 3?

**Comment by lukehoban** [comment] 2019-07-25 21:04
@hausdorff @lblackstone What's the proposal for addressing this?

**Comment by lblackstone** [comment] 2019-07-29 16:32
I'm not very familiar with Helm hooks, but it looks like a pretty big list of scenarios that it supports: https://github.com/helm/helm/blob/master/docs/charts_hooks.md#the-available-hooks

AFAICT, Pulumi can natively handle all of the lifecycle hooks (pre/post/crd install hooks), so we probably just need to specially handle the `test-success` and `test-failure` annotations.

For now, I'm inclined to skip deploying Pods with the `helm.sh/hook: test-success` or `helm.sh/hook: test-failure` annotation -- these Pods are intended to be a short-lived test, and aren't part of the application.

**Comment by hausdorff** [comment] 2019-07-29 23:39
I'm not sure that we'll ever support lifecycle hooks, but certainly not in Q3—I'll remove the label. In the mean time, we can skip the test hooks and document that our Helm support is limited to the semantics of `helm template`.

**Comment by Place1** [comment] 2020-06-11 02:08
The workaround posted in this issue no longer works for me.

I get an error saying there's no `metadata.name` on the List.

After adding a metadata.name to the List I get a `apiVersion does not have both a group and a version: "v1"`

**Comment by lblackstone** [comment] 2020-06-11 16:05
@Place1 I have a PR open to fix the regression you reported in #1156. The workaround will be valid again once that merges.

**Comment by shinebayar-g** [comment] 2021-01-04 22:31
Looks like [ingress-nginx](https://github.com/kubernetes/ingress-nginx) uses helm hooks to deploy admission-webhook things. For this limitation we cannot deploy **ingress-nginx**.

**Comment by draconisNoctis** [comment] 2021-01-06 09:48
@shinebayar-g 
Although the documentation of ingress-nginx mentioned, that only Helm v3 is supported a workaround is to use the `k8s.helm.v2.Chart`.
Helm 2 doesn't support the hooks, so the annotations are ignored.
Pulumi Helm 3 doesn't support them neither and removing any entry with the annotation **before** processed by the transformations. So it isn't even possible to remove the annotation in an transformation.

**Comment by lblackstone** [comment] 2021-02-04 23:07
@shinebayar-g @draconisNoctis We fixed a bug in the v3 SDK in #1335 that was likely the cause of the issues you were seeing. Can you give it a try with the `v2.8.0` k8s provider and let me know if you're still having problems? Thanks!

**Comment by Jean-Baptiste-Lasselle** [comment] 2021-02-08 10:51
Thank you so much for your PR @lblackstone , I am indeed myself facing the same issue in nginx helm chart and its admission webhooks. I amvery much expecting the pulumi release which will include your PR

**Comment by shinebayar-g** [comment] 2021-02-18 23:49
@lblackstone I deployed [ingress-nginx](https://kubernetes.github.io/ingress-nginx/deploy/#using-helm) chart as `k8s.helm.v3.Chart` resource today. It worked like a charm. All ingress-nginx resources with `helm.sh/hook` annotations deployed successfully.

**Comment by bob-bins** [comment] 2021-02-20 09:07
The transformation function in the original comment no longer works. Here's an updated one (in Typescript) in case someone else needs it.

```
import * as k8s from "@pulumi/kubernetes"
import * as pulumi from "@pulumi/pulumi"

const removeHelmHooksTransformation = (
  o: pulumi.ResourceTransformationArgs
): pulumi.ResourceTransformationResult => {
  if (o.props?.metadata?.annotations?.["helm.sh/hook"]) {
    const {
      "helm.sh/hook": junk,
      "helm.sh/hook-delete-policy": junk2,
      ...validAnnotations
    } = o.props.metadata.annotations
    return {
      props: {
        ...o.props,
        metadata: {
          ...o.props.metadata,
          annotations: validAnnotations,
        },
      },
      opts: o.opts,
    }
  }
  return o
}

// example usage
const ingressNginx = new k8s.yaml.ConfigFile(
  "ingress-nginx",
  {
    file:
      "https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.44.0/deploy/static/provider/aws/deploy.yaml",
  },
  {
    provider: eksCluster.provider,
    transformations: [removeHelmHooksTransformation],
  }
)
```

**Comment by maxromanovsky** [comment] 2021-03-03 21:18
Is it possible to suppress Diagnostics messages  in `pulumi up` cause by Helm hookssuch as this one:
```
  kubernetes:rbac.authorization.k8s.io/v1:RoleBinding (ingress-nginx-internal/ingress-nginx-internal-admission):
    warning: This resource contains Helm hooks that are not currently supported by Pulumi. The resource will be created, but any hooks will not be executed. Hooks support is tracked at https://github.com/pulumi/pulumi-kubernetes/issues/555
```

**Comment by bob-bins** [comment] 2021-03-04 18:47
If you're looking to suppress only those messages, I don't think that's possible. But you can use the [transformation function I posted above](https://github.com/pulumi/pulumi-kubernetes/issues/555#issuecomment-782591897 ) to remove the helm hook annotations so it won't be an issue.

**Comment by maxromanovsky** [comment] 2021-03-04 22:24
@bob-bins thank you for the tip! I thought there's more idiomatic approach :)

Anyway, here's the transformation very similar to @bob-bins, but in Python:
```python
def remove_helm_hooks(obj):
    if 'metadata' in obj and 'annotations' in obj['metadata']:
        for key in list(obj['metadata']['annotations'].keys()):
            if key in ['helm.sh/hook', 'helm.sh/hook-delete-policy']:
                del obj['metadata']['annotations'][key]
```

**Comment by gerrywastaken** [comment] 2021-03-30 16:00
> I'm not sure that we'll ever support lifecycle hooks

@hausdorff In this case isn't it better in the docs and errors to advise against using Chart when hooks are involved and instead pushing people towards more appropriate methods of adding a package of resources. Just removing blindly ignoring/removing hooks probably isn't a great idea, but at the moment it's the only solution presented.

**Comment by shinebayar-g** [comment] 2021-04-13 18:19
@lblackstone Can this issue closed and clear those warnings? :)

**Comment by shinebayar-g** [comment] 2021-04-26 20:57
> @shinebayar-g @draconisNoctis We fixed a bug in the v3 SDK in #1335 that was likely the cause of the issues you were seeing. Can you give it a try with the `v2.8.0` k8s provider and let me know if you're still having problems? Thanks!

Hi, @lblackstone can this issue considered as fixed now? If yes it would be awesome to remove these warnings https://github.com/pulumi/pulumi-kubernetes/issues/1454

**Comment by bartsmykla** [comment] 2021-06-30 11:09
@lblackstone Have you maybe had another look on this issue? :-)

**Comment by lblackstone** [comment] 2021-08-19 18:48
Hey, sorry for the delayed response here. I just opened #1682 to give users the option to disable these warnings. 

Relatedly, we're hard at work on a new approach to managing Helm resources with Pulumi that will also support all hooks. If you're interested, the work in progress can be found here: https://github.com/pulumi/pulumi-kubernetes/pull/1677 Feedback is welcome, so chime in on that PR if you have comments on the approach!

**Comment by viveklak** [comment] 2021-09-14 23:51
#1677 has been merged and Helm Release support is in public preview with v3.7.0 of the Kubernetes provider/sdk. As discussed in https://www.pulumi.com/blog/full-access-to-helm-features-through-new-helm-release-resource-for-kubernetes/, hooks are a good reason to consider Helm Release over the chart resource. Closing.

**Closed by viveklak** 2021-09-14 23:51 UTC
Labels: kind/enhancement, resolution/fixed

**Comment by JoaRiski** [comment] 2021-09-18 21:38
Slightly related, I've opened an issue over at helm (https://github.com/helm/helm/issues/10153) asking about the future of helm hooks overall, given that their non-declarative nature doesn't really fit the rest of the kubernetes ecosystem.

**Comment by JordanP01** [comment] 2023-07-04 08:49
Hello, I try to deploy velero with helm: https://vmware-tanzu.github.io/helm-charts version 4.1.1 and pulumi.

**Comment by JordanP01** [comment] 2023-07-04 09:18
Hello, I try to deploy velero with pulumi:

helm: https://vmware-tanzu.github.io/helm-charts
version 4.1.1

But I have theses warnings:

```
kubernetes:core/v1:ServiceAccount (velero/velero-server-upgrade-crds):
    warning: This resource contains Helm hooks that are not currently supported by Pulumi. The resource will be created, but any hooks will not be executed. Hooks support is tracked at https://github.com/pulumi/pulumi-kubernetes/issues/555 -- This warning can be disabled by setting the PULUMI_K8S_SUPPRESS_HELM_HOOK_WARNINGS environment variable

  kubernetes:rbac.authorization.k8s.io/v1:ClusterRole (velero-upgrade-crds):
    warning: This resource contains Helm hooks that are not currently supported by Pulumi. The resource will be created, but any hooks will not be executed. Hooks support is tracked at https://github.com/pulumi/pulumi-kubernetes/issues/555 -- This warning can be disabled by setting the PULUMI_K8S_SUPPRESS_HELM_HOOK_WARNINGS environment variable

  kubernetes:batch/v1:Job (velero/velero-upgrade-crds):
    warning: This resource contains Helm hooks that are not currently supported by Pulumi. The resource will be created, but any hooks will not be executed. Hooks support is tracked at https://github.com/pulumi/pulumi-kubernetes/issues/555 -- This warning can be disabled by setting the PULUMI_K8S_SUPPRESS_HELM_HOOK_WARNINGS environment variable

  kubernetes:velero.io/v1:VolumeSnapshotLocation (velero/default):
    warning: This resource contains Helm hooks that are not currently supported by Pulumi. The resource will be created, but any hooks will not be executed. Hooks support is tracked at https://github.com/pulumi/pulumi-kubernetes/issues/555 -- This warning can be disabled by setting the PULUMI_K8S_SUPPRESS_HELM_HOOK_WARNINGS environment variable

  kubernetes:velero.io/v1:BackupStorageLocation (velero/default):
    warning: This resource contains Helm hooks that are not currently supported by Pulumi. The resource will be created, but any hooks will not be executed. Hooks support is tracked at https://github.com/pulumi/pulumi-kubernetes/issues/555 -- This warning can be disabled by setting the PULUMI_K8S_SUPPRESS_HELM_HOOK_WARNINGS environment variable

  kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding (velero-upgrade-crds):
    warning: This resource contains Helm hooks that are not currently supported by Pulumi. The resource will be created, but any hooks will not be executed. Hooks support is tracked at https://github.com/pulumi/pulumi-kubernetes/issues/555 -- This warning can be disabled by setting the PULUMI_K8S_SUPPRESS_HELM_HOOK_WARNINGS environment variable
```

Did you have any suggestions for making it work ?

thanks in advance for your help

**Comment by omidraha** [comment] 2023-07-23 21:59
Hi, I want to use this `aws-efs-csi-driver`  helm chart from  here: 

https://artifacthub.io/packages/helm/aws-efs-csi-driver/aws-efs-csi-driver

But I received this warning:
```
Diagnostics:
  kubernetes:storage.k8s.io/v1:CSIDriver (efs.csi.aws.com):
    warning: This resource contains Helm hooks that are not currently supported by Pulumi. The resource will be created, but any hooks will not be executed. Hooks support is tracked at https://github.com/pulumi/pulumi-kubernetes/issues/555 -- 
```
**Info**
```python
kubernetes.helm.v3.Chart(
        f"efs-csi-driver{DEPLOY_NAME_PREFIX}",
        kubernetes.helm.v3.ChartOpts(
            chart="aws-efs-csi-driver",
            version="2.4.7",
            fetch_opts=kubernetes.helm.v3.FetchOpts(
                repo="https://kubernetes-sigs.github.io/aws-efs-csi-driver/"
            ),
            namespace=namespace.metadata.name,
            values={
                "logLevel": "debug",
                "replicaCount": "1",
                "region": "us-west-2",
            },
        ),
        pulumi.ResourceOptions(
            provider=provider,
            parent=namespace,
        )
    )
```

**Comment by usrbinkat** [comment] 2023-07-24 04:26
@omidraha

I see you are using the `kubernetes.helm.v3.Chart` resource which does not have any support for helm hooks. 

Take a look at the `kubernetes.helm.v3.Release` resource instead.

Read about both [HERE](https://www.pulumi.com/registry/packages/kubernetes/api-docs/helm/v3/)

**Comment by iyobo** [comment] 2023-12-02 20:16
The helm release is pretty "black boxy" in its approach to helm generated resources. This causes all sorts of issues sometimes with regards to deterministic pulumi state

**Comment by holms** [comment] 2024-07-25 21:03
So it's 2024 in here and I have this:

```
Diagnostics:
  kubernetes:batch/v1:Job (kube-system/secrets-store-csi-driver-keep-crds):
    warning: This resource contains Helm hooks that are not currently supported by Pulumi. The resource will be created, but any hooks will not be executed. Hooks support is tracked at https://github.com/pulumi/pulumi-kubernetes/issues/555 -- This warning can be disabled by setting the PULUMI_K8S_SUPPRESS_HELM_HOOK_WARNINGS environment variable

  kubernetes:batch/v1:Job (kube-system/secrets-store-csi-driver-upgrade-crds):
    warning: This resource contains Helm hooks that are not currently supported by Pulumi. The resource will be created, but any hooks will not be executed. Hooks support is tracked at https://github.com/pulumi/pulumi-kubernetes/issues/555 -- This warning can be disabled by setting the PULUMI_K8S_SUPPRESS_HELM_HOOK_WARNINGS environment variable

  kubernetes:rbac.authorization.k8s.io/v1:ClusterRole (secrets-store-csi-driver-keep-crds):
    warning: This resource contains Helm hooks that are not currently supported by Pulumi. The resource will be created, but any hooks will not be executed. Hooks support is tracked at https://github.com/pulumi/pulumi-kubernetes/issues/555 -- This warning can be disabled by setting the PULUMI_K8S_SUPPRESS_HELM_HOOK_WARNINGS environment variable

  kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding (secrets-store-csi-driver-keep-crds):
    warning: This resource contains Helm hooks that are not currently supported by Pulumi. The resource will be created, but any hooks will not be executed. Hooks support is tracked at https://github.com/pulumi/pulumi-kubernetes/issues/555 -- This warning can be disabled by setting the PULUMI_K8S_SUPPRESS_HELM_HOOK_WARNINGS environment variable

  kubernetes:rbac.authorization.k8s.io/v1:ClusterRole (secrets-store-csi-driver-upgrade-crds):
    warning: This resource contains Helm hooks that are not currently supported by Pulumi. The resource will be created, but any hooks will not be executed. Hooks support is tracked at https://github.com/pulumi/pulumi-kubernetes/issues/555 -- This warning can be disabled by setting the PULUMI_K8S_SUPPRESS_HELM_HOOK_WARNINGS environment variable

  kubernetes:core/v1:ServiceAccount (kube-system/secrets-store-csi-driver-upgrade-crds):
    warning: This resource contains Helm hooks that are not currently supported by Pulumi. The resource will be created, but any hooks will not be executed. Hooks support is tracked at https://github.com/pulumi/pulumi-kubernetes/issues/555 -- This warning can be disabled by setting the PULUMI_K8S_SUPPRESS_HELM_HOOK_WARNINGS environment variable

  kubernetes:core/v1:ServiceAccount (kube-system/secrets-store-csi-driver-keep-crds):
    warning: This resource contains Helm hooks that are not currently supported by Pulumi. The resource will be created, but any hooks will not be executed. Hooks support is tracked at https://github.com/pulumi/pulumi-kubernetes/issues/555 -- This warning can be disabled by setting the PULUMI_K8S_SUPPRESS_HELM_HOOK_WARNINGS environment variable

  kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding (secrets-store-csi-driver-upgrade-crds):
    warning: This resource contains Helm hooks that are not currently supported by Pulumi. The resource will be created, but any hooks will not be executed. Hooks support is tracked at https://github.com/pulumi/pulumi-kubernetes/issues/555 -- This warning can be disabled by setting the PULUMI_K8S_SUPPRESS_HELM_HOOK_WARNINGS environment variable
```

What should I do? This is default chart for aws from aws itself. Pulumi version is latest ATM.

**Comment by jabalsad** [comment] 2025-04-12 01:56
Should we reopen this ticket if we're still getting a warning for it?
