### ISSUE TITLE
i/o timeout when creating EKS cluster

### ISSUE THREAD

**Issue by adaniline-traderev** [pulumi/pulumi-kubernetes#447] opened 2019-02-22 14:03 UTC
Creation of EKS cluster failed with i/o timeout error

```
    Type                                          Name                                Status       
 +   pulumi:pulumi:Stack                           devops-eks-cluster-test1            created                 2 messages
 +   ├─ eks:index:Cluster                          eksCluster                          created                 
 +   │  ├─ eks:index:ServiceRole                   eksCluster-eksRole                  created                 
 +   │  │  ├─ aws:iam:Role                         eksCluster-eksRole-role             created                 
 +   │  │  ├─ aws:iam:RolePolicyAttachment         eksCluster-eksRole-90eb1c99         created                 
 +   │  │  └─ aws:iam:RolePolicyAttachment         eksCluster-eksRole-4b490823         created                 
 +   │  ├─ eks:index:ServiceRole                   eksCluster-instanceRole             created                 
 +   │  │  ├─ aws:iam:Role                         eksCluster-instanceRole-role        created                 
 +   │  │  ├─ aws:iam:RolePolicyAttachment         eksCluster-instanceRole-03516f97    created                 
 +   │  │  ├─ aws:iam:RolePolicyAttachment         eksCluster-instanceRole-3eb088f2    created                 
 +   │  │  └─ aws:iam:RolePolicyAttachment         eksCluster-instanceRole-e1b295bd    created                 
 +   │  ├─ kubernetes:yaml:ConfigGroup             eksCluster-dashboard                created                 
 +   │  ├─ aws:ec2:SecurityGroup                   eksCluster-eksClusterSecurityGroup  created                 
 +   │  ├─ pulumi-nodejs:dynamic:Resource          eksCluster-cfnStackName             created                 
 +   │  ├─ aws:iam:InstanceProfile                 eksCluster-instanceProfile          created                 
 +   │  ├─ aws:eks:Cluster                         eksCluster-eksCluster               created                 
 +   │  ├─ pulumi:providers:kubernetes             eksCluster-eks-k8s                  created                 
 +   │  ├─ pulumi-nodejs:dynamic:Resource          eksCluster-vpc-cni                  **creating failed**     1 error
 +   │  ├─ aws:ec2:SecurityGroup                   eksCluster-nodeSecurityGroup        created                 
 +   │  ├─ kubernetes:core:ConfigMap               eksCluster-nodeAccess               **creating failed**     1 error
 +   │  ├─ kubernetes:storage.k8s.io:StorageClass  ekscluster-gp2                      created                 
 +   │  ├─ aws:ec2:SecurityGroupRule               eksCluster-eksClusterIngressRule    created                 
 +   │  └─ aws:ec2:LaunchConfiguration             eksCluster-nodeLaunchConfiguration  created                 
 >-  └─ pulumi:pulumi:StackReference               identityStack                       read                    
 
Diagnostics:
  pulumi:pulumi:Stack (devops-eks-cluster-test1):
    unable to recognize "/var/folders/t4/n_45p27975n46db78hygnd900000gn/T/tmp-5531wnrkLvrWcBxq.tmp": Get https://1A079166478E00F6CBC69F3C9F16BA5E.yl4.us-east-1.eks.amazonaws.com/api?timeout=32s: dial tcp 54.161.223.176:443: i/o timeout
    unable to recognize "/var/folders/t4/n_45p27975n46db78hygnd900000gn/T/tmp-5531wnrkLvrWcBxq.tmp": Get https://1A079166478E00F6CBC69F3C9F16BA5E.yl4.us-east-1.eks.amazonaws.com/api?timeout=32s: dial tcp 54.161.223.176:443: i/o timeout
 
  pulumi-nodejs:dynamic:Resource (eksCluster-vpc-cni):
    error: Plan apply failed: Command failed: kubectl apply -f /var/folders/t4/n_45p27975n46db78hygnd900000gn/T/tmp-5531wnrkLvrWcBxq.tmp
    unable to recognize "/var/folders/t4/n_45p27975n46db78hygnd900000gn/T/tmp-5531wnrkLvrWcBxq.tmp": Get https://1A079166478E00F6CBC69F3C9F16BA5E.yl4.us-east-1.eks.amazonaws.com/api?timeout=32s: dial tcp 54.161.223.176:443: i/o timeout
    unable to recognize "/var/folders/t4/n_45p27975n46db78hygnd900000gn/T/tmp-5531wnrkLvrWcBxq.tmp": Get https://1A079166478E00F6CBC69F3C9F16BA5E.yl4.us-east-1.eks.amazonaws.com/api?timeout=32s: dial tcp 54.161.223.176:443: i/o timeout
 
  kubernetes:core:ConfigMap (eksCluster-nodeAccess):
    error: Plan apply failed: Get https://1A079166478E00F6CBC69F3C9F16BA5E.yl4.us-east-1.eks.amazonaws.com/api?timeout=32s: dial tcp 54.161.223.176:443: i/o timeout
```

**Comment by lukehoban** [comment] 2019-02-22 17:17
I believe this is a dupe of https://github.com/pulumi/pulumi-eks/issues/65.

**Closed by lukehoban** 2019-02-22 17:17 UTC
