### ISSUE TITLE
Using a file provider, after a change in manifest, it will always show a diff

### ISSUE THREAD

**Issue by bluegumcity** [pulumi/pulumi-kubernetes#2819] opened 2024-02-12 20:33 UTC
### What happened?

Using a file provider to create manifests. After initial manifest has been created, any changes to the code for that manifest, will forever show up as diff

### Example

```
import * as k8s from '@pulumi/kubernetes'

// Define the deployment configuration
const deploymentName = 'nginx-deployment'
const replicaCount = 2
const image = 'nginx:latest'

const yamlProvider = new k8s.Provider('yaml', {
  renderYamlToDirectory: `.`,
  kubeconfig: '',
  cluster: '',
  context: '',
})

// Create the deployment resource
const deployment = new k8s.apps.v1.Deployment(
  deploymentName,
  {
    metadata: {
      name: deploymentName,
    },
    spec: {
      replicas: replicaCount,
      selector: {
        matchLabels: {
          app: deploymentName,
        },
      },
      template: {
        metadata: {
          labels: {
            app: deploymentName,
          },
        },
        spec: {
          containers: [
            {
              name: 'nginx',
              image: image,
              ports: [
                {
                  containerPort: 80,
                },
              ],
            },
          ],
        },
      },
    },
  },
  { provider: yamlProvider }
)
```

Run this once. Now, if you change the port to 81 and run it again, you will get a diff on the port as expected.

However, if you run it a third, fourth etc time, it will keep showing that port diff.

### Output of `pulumi about`

```
CLI          
Version      3.105.0
Go Version   go1.21.6
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.22.0
aws-native  0.89.0
awsx        2.5.0
docker      4.5.1
docker      3.6.1
eks         2.2.1
kubernetes  4.7.1
nodejs      unknown

Host     
OS       fedora
Version  39
Arch     x86_64

This project is written in nodejs: executable='/nix/store/rzi8a9f7m16n674hvdp6vcmhs19yfzjp-nodejs-20.5.0/bin/node' version='v20.5.0'

Current Stack: organization/nginx/prod

TYPE                           URN
pulumi:pulumi:Stack            urn:pulumi:prod::nginx::pulumi:pulumi:Stack::nginx-prod
pulumi:providers:kubernetes    urn:pulumi:prod::nginx::pulumi:providers:kubernetes::yaml
kubernetes:apps/v1:Deployment  urn:pulumi:prod::nginx::kubernetes:apps/v1:Deployment::nginx-deployment


Found no pending operations associated with prod

Backend        
Name           mblaptop
URL            file://~/tmp/pulumi-bug
User           magnus
Organizations  
Token type     personal

Dependencies:
NAME                VERSION
@pulumi/aws         6.22.0
@pulumi/awsx        2.5.0
@pulumi/eks         2.2.1
@pulumi/pulumi      3.105.0
@types/node         18.19.15
@pulumi/aws-native  0.89.0

Pulumi locates its logs in /run/user/1000 by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by soujiro32167** [comment] 2024-05-30 14:37
Potential duplicate of https://github.com/pulumi/pulumi-kubernetes/issues/3026#issuecomment-2136265687

**Comment by blampe** [comment] 2024-05-30 14:43
> Potential duplicate of [#3026 (comment)](https://github.com/pulumi/pulumi-kubernetes/issues/3026#issuecomment-2136265687)

Indeed!

@bluegumcity and @soujiro32167 we haven't officially released the fix yet but alpha releases are always available. You should be able to use `[4.13.0-alpha.1716993802](https://www.npmjs.com/package/@pulumi/kubernetes/v/4.13.0-alpha.1716993802)` (or similar in your language's package manager) to confirm the fix.

**Closed** 2024-05-30 14:43 UTC
Labels: impact/usability, kind/bug, resolution/duplicate, area/yaml
